### ISSUE TITLE
Prepare for and conduct Lead Provider user research sessions

### ISSUE THREAD

**Issue by kerry-b-dfe** [DFE-Digital/register-early-career-teachers#106]
## Why?
We would like to conduct research sessions with lead providers.

## What?
To find out more about their data needs, non-standard participants and potential impacts of changes to the school registration journey.

## When?
- [x] Session 1 - Tuesday, Sept 10 at 3pm
- [x] Session 2 - Thursday, Sept 19 at 1pm
- [x] Session 3 - Tuesday, Sept 24th at 1pm
- [x] Session 4 - Friday, October 11th at 1:30pm
- [x] Session 5 - Tuesday, October 15th at 10am
(Edited to reflect rescheduled sessions)

## Helpful links or other information
[User research board](https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=a~w3oybAMSbU&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e)
[Discussion guide](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Test%20and%20prep/User%20Research/Lead%20provider%20discussion%20guide%20-%20ECF%202.0.docx?d=w656c4f06c5dd4c3ca1c8d3047ae066a2&csf=1&web=1&e=AJ1Qdj)
[Sign up sheet](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Test%20and%20prep/User%20Research/Note%20Taker%20Sign%20Up.xlsx?d=w492d489fd5f24c54b3f134e7ee9042db&csf=1&web=1&e=CRiAlO&nav=MTVfe0EwNTBDQjA0LTA0NzYtNDgyOC05M0U4LUY5QzYxRkNFNzQ3Qn0)

**Comment by kerry-b-dfe** [comment]
- [ ] Book session with Nathan to run through research questions and plan
- [ ] Book session with team to run through research questions and plan
- [ ] Prepare discussion guide, consent forms etc
- [ ] Attend policy and engagement LP catch ups to promote sessions
- [ ] Distribute recruitment info and links to providers

**Comment by kerry-b-dfe** [comment]
Call with Nathan - can find his feedback as the green sticky notes on the Lucid board

**Comment by kerry-b-dfe** [comment]
Trialling using this frame to gather team input on research:


![Image](https://github.com/user-attachments/assets/4f7e9a86-424c-49fe-8b6d-86de429a6dbc)

**Comment by gracecbrennan** [comment]
Board of research questions is created and @gracecbrennan to book session with team to run through.

**Comment by claire-hughez** [comment]
Kerry to add discussion guide link.

Will join engagement sessions and send recruitment emails this week.

Will ping out the glossary stuff too.

**Comment by kerry-b-dfe** [comment]
[Discussion guide](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Test%20and%20prep/User%20Research/Lead%20provider%20discussion%20guide%20-%20ECF%202.0.docx?d=w656c4f06c5dd4c3ca1c8d3047ae066a2&csf=1&web=1&e=AJ1Qdj)

**Comment by kerry-b-dfe** [comment]
- [x] Conversation with Faisal from schools team - discussion guide shared, comments to be incorporated into 
- [x] Joe from NPQ team added questions on research plan
- [x] Discussion with Colin around best way to promote sessions
- [x] Provider email invite written
- [x] Provider email invite shared with Nathan to check terminology
- [x] Provider email invite shared with Anna Knight to be sent to LPs

**Comment by kerry-b-dfe** [comment]
- [x] Created 'Provider research sessions' calendar to enable easier tracking and booking of LP sessions
- [x] Integrated with Calendly so LPs can book sessions without clashing

**Comment by gracecbrennan** [comment]
Provider invites have been sent out - Capita won't be joining. 

Contracts managers have asked to be mindful of bid in process

**Comment by gracecbrennan** [comment]
Corey ran the session in Kerry's absence yesterday. 

@claire-hughez to include notes on this ticket.

**Comment by claire-hughez** [comment]
[https://educationgovuk.sharepoint.com/:w:/r/sites/teacherservices/_layouts/15/doc.aspx?sourcedoc=%7B16e48985-d96c-4aee-a55b-5549333b313f%7D&file=10th%20september%202024%20lp%20ur%20notes.docx&action=default&mobileredirect=true](Notes for the UR on 10th September)

**Comment by claire-hughez** [comment]
Next session is on the 30th.

**Comment by kerry-b-dfe** [comment]
- Sent out participant information sheets
- Sent out consent forms
- Moved sign up sheet to main doc
-  Two new sessions added

**Comment by gracecbrennan** [comment]
Kerry analysing outputs from TeachFirst session last week. 

Also prepping for session with ambition tomorrow.

**Comment by gracecbrennan** [comment]
Kerry is analysing each session as it's happening, with one more planned for Monday

**Comment by gracecbrennan** [comment]
UCL have now expressed interest in taking part. 

Kerry is continuing with analysis on other sessions.

**Comment by gracecbrennan** [comment]
@kerry-b-dfe is going to share link to slidedeck 

2 more providers to be booked in next week.

**Comment by gracecbrennan** [comment]
@kerry-b-dfe hoping to share complete 1st deck today.

**Comment by gracecbrennan** [comment]
@gracecbrennan to check in with Kerry on 1st slide deck

**Comment by gracecbrennan** [comment]
@gracecbrennan to help book a date in for playback

**Comment by claire-hughez** [comment]
1:30 on Wednesday for playback.

**Comment by kerry-b-dfe** [comment]
[Intro to lead providers and ECF digital services](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Test%20and%20prep/User%20Research/Provider%20research/Lead%20providers%20and%20ECF%20-%20An%20introduction%20to%20providers%20and%20the%20Teacher%20CPD%20digital%20services.pptx?d=w18f413c4746d48e0881c87d519a302b3&csf=1&web=1&e=vIpSGD)

[Research playback](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Test%20and%20prep/User%20Research/Provider%20research/ECF%20LP%20Research%20Play%20Back.pptx?d=wf79dadb4fa734ff191578f50593260aa&csf=1&web=1&e=1fZqLF)


[Playback recording](https://educationgovuk-my.sharepoint.com/:v:/g/personal/grace_brennan_education_gov_uk/EbKjd-ZPBFhGp4egfuGWW98ByMwzInm4gf5SG9cwYdynsg?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view)
