### ISSUE TITLE
Prototype an 'add mentor' journey 

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#128]
Once ticket #107 has ideated on potential options for documenting mentor training and mentoring, prototype an 'add a mentor' journey that is a siloed journey that includes eligibility checks for mentor training and an add a mentor journey that is an extension of adding an ECT - this journey will just state who is mentoring 

## Description

This ticket is to create a prototyped journey for a school user to add a new mentor, including specifying when a mentor is training. 

## Why? What's the need?

School users need to add information about their mentors to the service, specifically when a mentor is training and receiving funding. We need to create a user journey in prototype form to test to capture that information. We will focus on capturing the following about the mentor:
- TRN
- Date of birth
- Email
- Name (confirm based on other details / or input)
- National insurance (this may not be present in all scenarios)
_- Programme choice (provider / school led)_ - No longer needed
- Who they're mentoring (?) (option to add later)
_- Whether mentor is doing mentor training (?)_ - No longer needed

## Success criteria / when is this ticket done?
- Created a clickable prototype which captures the above information and can be tested with users
- A journey which collects information needed in one transaction
- Create a variant of a confirmation message with different onwards journey based on if there's an outstanding action (such as tell us who this mentor is mentoring)
- Create a variant for capturing name vs confirming a name we've pulled back
- Consider how to connect to adding an ECT without a mentor, and also if adding a mentor without an ECT connected to them requires further action

## What's out of scope
- ITT mentor training
- Default settings for programme choice & AB are still to be decided, so this design will be designed as if there is no existing default
- Other pages such as homepage & sign in flow - prototype for this will consist of placeholder designs for those.
- Adding multiple mentors at the same time, or adding a new ECT at the same time as a mentor
- Answering over multiple transactions, i.e. checklist, or save and return later (this may be explored in another ticket)

## Helpful links or other information
- [Design board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?viewport_loc=120559%2C9024%2C21547%2C10517%2C0_0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)

**Comment by JSJohal** [comment]
Consider programme provider / DP questions

**Comment by gracecbrennan** [comment]
Awo think she'll be able to get this drawn up before going on leave at the end of the day today.

**Comment by aabdi18** [comment]
current frame on lucid [here](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=Fc5~Ywx8rH0A&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) which shows some of the research points from analysis and the proposed add a mentor journey screenshots (needs discussion and iterations)

**Comment by JSJohal** [comment]
After discussing with Claire, put this back into not started for now. Research outputs from the first round may shape some changes to this ticket, so decided to wait for that.

**Comment by mason-emily** [comment]
For reference, I've added a frame to explain the different scenarios for mentors training with the same or different provider to their ECT(s): https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=aXPb3fuAoVm9&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b

**Comment by claire-hughez** [comment]
I think it's good to focus on:
- The UR findings on trying to add a mentor when adding an ECT
- Potentially stopping users from adding a mentor until they've registered an ECT

**Comment by claire-hughez** [comment]
We'd need to think through transfers for this. In theory, a mentor could transfer to a different school without any ECTs. They could still be eligible for training if historically they did mentor an ECT at their old school. This might be tricky.

**Comment by gracecbrennan** [comment]
Plan is to prototype basic journey first which Awo will make a start on today

**Comment by aabdi18** [comment]
At a good place with the happy path of the journey, 
next steps are looking at scenarios where mentor has transferred/school has changed details etc
Going to start looking at the ineligible for training route

**Comment by gracecbrennan** [comment]
Looked at some more of the things suggested in meeting with Nathan. 

A few more things to add in before this gets moved into review :)

**Comment by gracecbrennan** [comment]
Core prototype pages are agreed so this can be built in the prototype kit now. 

Awo will share some of the content for review with the team today.

**Comment by gracecbrennan** [comment]
@JSJohal is going to pick up alongside his ticket to get into prototype

**Comment by JSJohal** [comment]
Not managed to pick this up as of yet in terms of getting into prototype. Will start looking at it next.

In the meantime, Dom's suggest [content tweaks on the Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?viewport_loc=112927%2C-23645%2C8334%2C4068%2C0_0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b), which can be reviewed

CC @claire-hughez

**Comment by gracecbrennan** [comment]
Dom has reviewed content and Jas is going to start looking at this today.

**Comment by gracecbrennan** [comment]
Jas has been adding to prototype and we're not far off being ready to take into research.

**Comment by JSJohal** [comment]
[Latest designs in prototype](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/setup-scenario-1) and on [this GitHub branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3).
[Screenshots on this Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b).

Flows are generally complete, but still to be reviewed as an overall incl content.

**Comment by JSJohal** [comment]
I've made flow changes to the journey based on the review we did, these can be seen on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) and they're also in the [prototype (password is review)](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/setup-scenario-1).

May still be some content changes outstanding - suggest these are made on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) for now by @Dom-Collins and I can pick them up to put them into the prototype afterwards.

If any changes need to be made in the prototype while I'm on leave, they can be made on the [v3 prototype branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3) and they'll automatically deploy to the Heroku prototype environment. Probably easiest way would be to create a new branch off of the [v3 prototype branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3) to make changes, and then do a PR back into the v3 branch.

I've added checkmarks to the post-its for where I've made changes on the Lucid board
