### ISSUE TITLE
Design a prototype for viewing added ECTs

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#130]
## Why? What's the need?

We've prototyped an 'add ECT' journey to be tested, and will also be prototyping a journey to add / assign mentors. This ticket is for prototyping a design for 'viewing' ECTs that have been added, as well as actions that still need to be taken. There's a lo-fi ideation ticket (#194) for this which has already drawn up some ideas and options.

Requirements:
A prototype where users can:
- View a list of their ECTs
- Search or filter to see certain ECTS or mentors if necessary - start with minimum with caveat to add more as we learn
- See the state of their ECTs - statuses not created yet so don't need to get too hung up on tags etc
- See any key information about the ECT or mentor record that might be useful before clicking into individual records - think about flagging records without mentors / mentors without ECTs
- Entry point for adding ECT
- Consider if viewing mentors will be separated or part of this design

## Success criteria / when is this ticket done?
- Created a prototype which covers the requirements above. There will be other scenarios such as unhappy path / less common which will need to be designed for possibly at a later stage.

## What's out of scope
- Complex / unhappy path scenarios that aren't listed above

## Helpful links or other information
- [Design board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?viewport_loc=120559%2C9024%2C21547%2C10517%2C0_0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)

> Some other context on viewing ECTs and mentors via Slack:
> - Academic year can be unhelpful and often confuses people more - e.g in the instance where an ECT transfers in their year 2, the school sees them as new, but they would technically be an earlier academic year
> - No longer training but off to one side - completed training or no longer training at their school records, the SIT wants to see the current, but they may need to refer back to the old ones - essentially schools seem to worry when records stay on their screen when they're completed or the ECT has gone elsewhere, so content to help mitigate this might help, and being really clear on the current status of the ECT/mentor
> - It’s easy to send someone across to another school, but have to contact helpdesk if they leave teaching and don’t go directly to another school - this is a slightly separate point, but this came up in our UR too about ECTs staying on their screen when they've left but not to another school

**Comment by JSJohal** [comment]
May add other info such as academic year / cohort based on analysis

**Comment by gracecbrennan** [comment]
This has been moved back into progress.

**Comment by JSJohal** [comment]
Pausing this to pick up tickets of higher priority in this sprint, such as #372

**Comment by claire-hughez** [comment]
Can have records page with names ready for UR round, but not any other kind of landing page with alerts or guidance.

**Comment by gracecbrennan** [comment]
Jas picked this up yesterday - having a catch up with Claire to agree next steps.

**Comment by claire-hughez** [comment]
Jas has done that very draft design, I'd find it really helpful if:
- we gathered the needs, problems and insights that exist here at the moment (particularly on statuses)
- we have a look at how we want to iterate and improve that page
- we have some sort of session to gather insights from the team

Some examples of needs I've written on the spot I can think of:
- As a school user, I need to know what my responsibilities and duties are for registering an ECT and mentor with DFE, so I can fulfil them, get funding and training for those participants and ease my anxiety!
- As a school user, I need to understand the status of my ECT or mentors, so I can understand if I need to act to get their training and funding sorted
- As a school user, I need to quickly locate ECT or mentor records so I can make changes or updates when things differ

**Comment by JSJohal** [comment]
Next steps:
- exploring basic filtering such as name, TRN, status / call to action
- playing back basic info on the view page such as name, TRN, start date(?), mentored by, some sort of status and call to action
- more complex status understanding and mapping will happen separately
- consideration around hierarchy of ECTs and mentors - a few things to think here about entry point for adding a mentor (1 or more)

**Comment by gracecbrennan** [comment]
Work ongoing to action next steps above.

**Comment by JSJohal** [comment]
Ongoing - in progress. Will continue working on today, no blockers.

**Comment by claire-hughez** [comment]
Timebox to end of day, would be good to catch up and finish today.

**Comment by JSJohal** [comment]
Have caught up with @claire-hughez and decided to end this ticket at this point pending further analysis into statuses / filters.
Here's the screenshot of where we've paused it:
![image](https://github.com/user-attachments/assets/72629588-235a-4ef0-a7d0-0e8b9a83c67f)
This is in the prototype in the `v4` branch, so we can progress in upcoming sprints for research.
