### ISSUE TITLE
Find out what data we actually need about an early career teacher and their induction and training 👾 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#18]
## Why

We’ve talked about the  structure of the data model, but this largely rests upon knowing what data we actually need to collect from our different user groups.

We felt it was unclear what is the data we actually need to be collecting, so this ticket will aim to clarify that.

## What

Find out:

- What data we currently collect in ECF1 and what it is used for
- If there’s any data we currently collect that does not have a use
- If there is data we should be collecting, but we are not currently in ECF1

‌

[From previous disco] For each process within the service and related to our service purposes and agreed future vision, we need to map out:

- the data we need
- why the service requires that data
- who / where can we best get that data from
- how we validate and verify it’s correct
- How we will keep the data up-to-date

## Context & links

Can use the service rules and funding summary.

Previous disco stakeholder links:

- [Stakeholder interview notes](https://educationgovuk.sharepoint.com/:f:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/0.%20CPD%20Programme/2023%20CPD%20disco%20(CPD%20or%20ECF%20and%20NPQ)/User%20research/Stakeholder%20Sessions/Stakeholder%20interview%20notes?csf=1&web=1&e=pmsNW7 "‌")
- [PDF of boards](https://educationgovuk.sharepoint.com/:b:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/0.%20CPD%20Programme/2023%20CPD%20disco%20(CPD%20or%20ECF%20and%20NPQ)/User%20research/Stakeholder%20Sessions/Stakeholder%20sessions.pdf?csf=1&web=1&e=cRfj3y "‌")
- [Board I walked through](https://lucid.app/lucidspark/11592bb7-b22e-4958-be58-788dd00138e2/edit?view_items=R7yiFBb44r4E&invitationId=inv_aafa318f-f41e-4758-9803-3e70d4006fbf "‌")

## Who knows about this

@mason-emily @claire-hughez

**Comment by kas-madrigal** [comment]
@mason-emily want to have a chat about this? I left a bunch of post-its

**Comment by gracecbrennan** [comment]
Kas and Emily are going to catch up on this today before chasing Nathan

**Comment by claire-hughez** [comment]
Catchup happened, now this is nearly done

**Comment by gracecbrennan** [comment]
Emily needs to cross reference this with Nathan's scheduling documents but is planning to finish this one off today

**Comment by mason-emily** [comment]
https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=y01YD2y_B7-k&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6

**Comment by JSJohal** [comment]
Thanks, this looks great. This will be super helpful to use as part of #60!

**Comment by gracecbrennan** [comment]
@mason-emily to share with lpdob team for comments

**Comment by mason-emily** [comment]
We definitely need the following fields:

- School URN (school admin will be logged in so we'll know it)
- TRN
- Full name 
- DoB (don't keep, use to check TRN)
- National insurance number (don't keep, use to check TRN)
- Email
- Programme choice

We might also want:
- Whether participant is doing a non-standard induction (reduced, extended, part time, late start)
- Start date 
- Lead provider & Delivery partner pairing (from a pre-defined list)

**Comment by peteryates** [comment]
Eventually I think so, but initially ABs will be claiming ECTs.

**Comment by claire-hughez** [comment]
We might want to specify - I thought that list was just data from schools. We already get an induction start date from ABs, so I thought it was a 'maybe' for schools.

**Comment by mason-emily** [comment]
This was what we need to collect from schools, and start date was referring to start date at the school not induction start date. I think we'll carry on updating that list today so isn't a final version yet!

**Comment by gracecbrennan** [comment]
Another session happening this morning with Tony and Pete to discuss.

**Comment by JSJohal** [comment]
> ### ECTs
> We definitely need the following fields from schools to register ECTs:
> 
> * School URN (school admin will be logged in so we'll know it)
> * TRN
> * DoB (don't keep, use to check TRN)
> * National insurance number (don't keep, use to check TRN)
> * Email (clarify if personal or school)
> * Programme choice
> * Appropriate body
> 
> We might also want:
> 
> * Whether participant is doing a non-standard induction (reduced, extended, part time, late start)
> * Start date at the school
> * Lead provider & Delivery partner pairing (from a pre-defined list)
> * Full name (can we get this from DQT if we don't need it to check)
> 
> We will also need these fields separate to the initial registration:
> 
> * Mentor assigned to ECT
> 
> ### Mentors
> We definitely need the following fields from schools about mentors:
> 
> * School URN (school admin will be logged in so we'll know it)
> * TRN
> * DoB (don't keep, use to check TRN)
> * National insurance number (don't keep, use to check TRN)
> * Email
> * Programme choice
> 
> We might also want:
> 
> * Whether participant is doing non-standard training (part time, late start, replacement)
> * Start date at the school
> * Lead provider & Delivery partner pairing (from a pre-defined list)
> * Whether mentor has completed ITT mentor training? (can probably get this from within DfE)
> * Whether mentor is doing mentor training? (could also be separate to the registration journey)
> * Full name
> 
> We will also need these fields separate to the initial registration:
> 
> * ECT(s) mentor is assigned to

Thank you - this is super helpful!

A few musings I had:

1) Do we _always_ need the ECT / mentor National insurance number? I think in the ECF1 journey we only ask for it sometimes - I've gone through in staging envs a fair few times where it's not asked NINO but only asked name, DoB, TRN - is NINO asked if something doesn't match?

2) Appropriate body: assuming we can continue doing this as a default on an academic year level? Although you can currently choose a different appropriate body to the default when adding an ECT as in ECF1.

3) Programme choice: assuming that would be at a academic year level - as in ECF1, there's no option of selecting a different programme choice / type when adding an ECT.

4) Do we know why we don't we ask school users about their lead provider / delivery partner pairing in ECF1? We do ask if it's changed if they're a returning user, but don't ask them to select their new pairing. ECF1 lets school users add ECTs even if there's no confirmed lead provider / delivery partner pairing yet (cause it's not been confirmed by the LP).

**Comment by mason-emily** [comment]
> Do we always need the ECT / mentor National insurance number? I think in the ECF1 journey we only ask for it sometimes - I've gone through in staging envs a fair few times where it's not asked NINO but only asked name, DoB, TRN - is NINO asked if something doesn't match?

No you're right, we only need it when we can't match the participant in DQT using TRN and DoB (and possibly first name, tbc)

> Appropriate body: assuming we can continue doing this as a default on an academic year level? Although you can currently choose a different appropriate body to the default when adding an ECT as in ECF1.

Yep we definitely still need the concept of a default AB for the year, but some ECTs might have a different AB to the default - I can try and ask for some data on this to see how common that is

> Programme choice: assuming that would be at a academic year level - as in ECF1, there's no option of selecting a different programme choice / type when adding an ECT.

Yep need a default for this too - but in cases where people transfer into a school they can keep their old LP so a different one to the default

> Do we know why we don't we ask school users about their lead provider / delivery partner pairing in ECF1? We do ask if it's changed if they're a returning user, but don't ask them to select their new pairing. ECF1 lets school users add ECTs even if there's no confirmed lead provider / delivery partner pairing yet (cause it's not been confirmed by the LP).

In ECF1 it's the LP's role to claim schools and anything before that happens offline. We have #35 to explore improving that process

**Comment by claire-hughez** [comment]
Tejas also told us that the new TRS API should allow you to search by name and DOB, instead of TRN and DOB. 

This hasn't been built yet, but might be an easier way to validate who the teacher is and that they have QTS later.

**Comment by mason-emily** [comment]
From speaking to Nathan:
- Start date at school for ECTs should be a 'definitely need'. Previous confusion around misreading the q and reporting DoB, and language issue around contracts start date.
- For non-standard mentors - whether they are doing the training part time which might be different from if they're working part time. We'd be interested to know both.
- Hierarchy of ECTs vs mentors - could we 'add the ECT's mentor' and playback that a mentor is eligible and can 'opt in' or 'opt out' of training.
