### ISSUE TITLE
Check data model so far against the data model problems we found in the discovery

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#205]
## Why?
We need to test if our suggested data model solves the problems that occur in the ECF1 data model.

We wrote a list of problems back in the discovery, so we can use this to see if we've addressed most or all of the issues.

## What?
Check the new data model against the issues with the ECF1 data model, [in the second sheet here](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B7CB1C50C-33EC-48BC-B3FB-95593A457C96%7D&file=ECF%20Pain%20points%20log.xlsx&action=default&mobileredirect=true)

**Comment by peteryates** [comment]
@peteryates and @tonyheadford to review and pull out the things we can check now.
