### ISSUE TITLE
Create list of changes we're considering for ECF2 and meet with LPDOB to assess their feasibility for the API

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#206]
## Why?
We've already discussed a lot of changes we'd like to make to how schools register ECTs and mentors.

We also need to consider how this will impact the lead provider API.

Some changes might be impossible or we at least need to think in detail about how we do them.

## What?
- Write a list of changes we're currently considering making for ECF2
- Look at how they might impact the API
- Check this with the LPDOB team, and assess its feasibility

## Helpful links or other information
https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B1D59BFB1-0747-4BA0-A062-C4437BA01CB3%7D&file=Changes%20we%27re%20planning%20to%20test%20for%20ECF2%20that%20will%20impact%20the%20API.xlsx&action=default&mobileredirect=true

**Comment by gracecbrennan** [comment]
@peteryates to review changes that Claire has drafted

**Comment by JSJohal** [comment]
@claire-hughez doc looks good! 🔥

**Comment by gracecbrennan** [comment]
Waiting on LP team to get back on availability for review

**Comment by claire-hughez** [comment]
Will put in meeting for in 2 weeks

**Comment by gracecbrennan** [comment]
Claire has shared summary of session on slack.

Claire is going to write tickets to follow up from session.
