### ISSUE TITLE
Export important artefacts from Lucidspark to Sharepoint ⭐ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#22]
## What?
Export important artefacts from Lucidspark to Sharepoint so we can use them for any Lucidspark outages and we don't lose them.

**Comment by kerry-b-dfe** [comment]
[Sharepoint lucid folder](https://educationgovuk.sharepoint.com/:f:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Discovery/Lucid%20boards?csf=1&web=1&e=owwSNx)

**Comment by gracecbrennan** [comment]
Boards have been saved as view only and pdfs downloaded ahead of next week.
