### ISSUE TITLE
As a team, organise and discuss insights from partnership research

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#220]
## Why?
The insights from this ticket https://github.com/DFE-Digital/ecf2/issues/35 should be discussed with the team. There are a few discussion points I've left (screenshot below). 

![Image](https://github.com/user-attachments/assets/d28e0483-e06c-48f0-9b4e-70a250aa0fee)

## What?

I've learned 3 very important things throughout this process.

Partnership reporting will work well ONLY if other steps of the process work well. This is because we depend on ABs on the AB portal to record cohort and academic year, which are intrinsic to correct partnership reporting. LP use this data to then submit a partnership and connect those data points to contracts but the initial inputs happen earlier on in the process.

As with induction data we have an overly-complicated system of time tracking that requires input from multiple sources isolated from each other (schools, ABs and LP). They are in different systems, happening in a non-sequential way for a system that requires them to be very sequential in order to succeed. On top of this, users don't understand the entire process and do not understand our requests or their responsibility in them.

Redesign of induction data and LP partnership should come hand in hand as LP partnership is last the service journey flow and uses the same data points. If induction data and time tracking is redesign correctly, partnership user flow could be much easier for us and for users.

## Helpful links or other information

Semi-Final lucid
https://lucid.app/lucidspark/94ab3793-b960-403b-b598-3676caf8ccb3/edit?view_items=pfc-Hk2izg8~&invitationId=inv_87d98967-2b2c-4df5-8cd7-620e14fc8093

Kas walkthroughs to listen to at 1000000x speed before the session
https://www.loom.com/share/61c5e7fcf7c6462991114f4ceac061f5?sid=9aedb567-3ffe-4f95-bd08-69c1e1af6210 

https://www.loom.com/share/c9923aaecd17436181c1fbf8bee505a0?sid=ad78328d-72a8-42fa-aff2-c4d7ebd84f8b

**Comment by kas-madrigal** [comment]
Please schedule a call for this at some point that's fun @JSJohal @aabdi18 @Dom-Collins particularly fun for you!

**Comment by gracecbrennan** [comment]
Kerry to pick up when they are back

**Comment by claire-hughez** [comment]
Kas to put in a call for this to go over insights

**Comment by gracecbrennan** [comment]
This is happening Tuesday next week

**Comment by gracecbrennan** [comment]
Kas is prepping for this session tomorrow today :)
