### ISSUE TITLE
Analysis into what could go wrong with signing into the service for schools

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#229]
## Why?
DFE Sign in is going to be introduced for school users in Register early career teachers.

We want to consider what problems or unhappy paths there might be with its use, so we can design solutions or mitigations.

## What?
- Look into journey of signing into DfE Sign In (Awo might be helpful for this)
- Identify unhappy endings/paths or issues
- Make recommendations for mitigations or solutions

**Comment by claire-hughez** [comment]
We should look into this design history and potentially find others for when other services have implemented DFE sign in:

https://becoming-a-teacher.design-history.education.gov.uk/manage-school-placements/signing-in-to-the-service/

Really clear list of unhappy paths here

**Comment by gracecbrennan** [comment]
Emily started on Friday - looking through DfE sign-in journeys

**Comment by gracecbrennan** [comment]
@mason-emily is nearly complete on this and will add link to the ticket

**Comment by gracecbrennan** [comment]
Hoping to finish off today

**Comment by mason-emily** [comment]
https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=XlAe0iunKKqJ&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6

**Comment by gracecbrennan** [comment]
@claire-hughez @JSJohal @kas-madrigal to review

**Comment by JSJohal** [comment]
@mason-emily this is great! Really helpful. Added a few comments on the board

**Comment by claire-hughez** [comment]
This is great. The screenshots make it much easier to understand too. Wrote some thoughts on next steps on the board.

From what I can see, approvers can't grant access unless the user has requested it?

@kas-madrigal and @emily-prudence-dfe should also have a look at this. The things we need to ticket up, they'll need to ticket up for appropriate body sign in too I think!

**Comment by gracecbrennan** [comment]
Emily is catching up with Jas to agree tickets on next steps
