### ISSUE TITLE
Check content defining appropriate body with the AB and Regs team

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#243]
## Why?
We went through the prototype to add an ECT. 

Feedback suggested checking with the AB and regulation team about how we'd define appropriate bodies.

They might have advice on how to explain it to users.

## What?
- Check content around asking users to give the appropriate body with the AB reg team
-

**Comment by Dom-Collins** [comment]
Will reach out to korin.wilshaw@education.gov.uk today to ask for a review of suggested content on the 'Add an ECT' flow.

**Comment by gracecbrennan** [comment]
Dom is going to chase Korin on this today

**Comment by Dom-Collins** [comment]
Chased Korin who is on leave till today. Instead, Evie Evans replied in her stead to say: 

"Apologies once again we have had a couple of urgent deadlines and it is only me in the team today. Are you ok if we come back on this on Monday?"

Response due today.

**Comment by gracecbrennan** [comment]
No response just yet - will chase today

**Comment by Dom-Collins** [comment]
This is in progress. I'm currently using Korin's input to iterate the AB definitions.

**Comment by Dom-Collins** [comment]
[Content to define ABs](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/EfcPfBhXN3ZKlgbWmTzq1_YBUUk6nJShMLdZ9rl6Igey4Q?e=OumpKk)

**Comment by Dom-Collins** [comment]
Responded to feedback from @claire-hughez, I'll share with Korin and then finalise content to be added to prototype.

**Comment by gracecbrennan** [comment]
A revised draft has gone to Korin and she is due to confirm on Monday

**Comment by Dom-Collins** [comment]
Review of draft due back today from Korin.

**Comment by gracecbrennan** [comment]
Korin did come back on this yesterday. 

will then see how this content performs in testing

**Comment by Dom-Collins** [comment]
@claire-hughez here is the [AB content ](https://github.com/DFE-Digital/ecf2-prototype/pull/12) Do you feel like this is in a good place? Shall I prototype it?

**Comment by gracecbrennan** [comment]
@JSJohal to add to the prototype

**Comment by gracecbrennan** [comment]
This has now merge with ticket #372
