### ISSUE TITLE
Address problem of when the DQT name is out of date but we want to pass on an updated name to lead providers

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#245]
## Why?
We know that 1 in 5 mentor records in CPD have at least a surname that does not match what is stored in DQT.

We're worried that playing back the name from DQT and not asking for an updated name might risk:
- Schools dropping out of the registration of ECTs or mentors
- An out of date name being passed to lead providers which leads to confusion in setting up training for ECTs
- A rise in support tickets querying the name shown for ECTs or mentors

## What?
How can we try to mitigate these risks in the adding an ECT and adding a mentor journey?

We'd like to explore asking schools to give us an updated name when it's incorrect and test this with users.

**Comment by JSJohal** [comment]
Started ideating on this on the [IxD board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?viewport_loc=166815%2C43844%2C8658%2C4226%2C0_0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b), will continue with it further today

**Comment by JSJohal** [comment]
Looking at content for this with @Dom-Collins for a few ideas I've pulled together on the board. Will review again and possibly re-draft ideas based on how feasible / useful we think they are

**Comment by gracecbrennan** [comment]
Jas is going to catch up with Claire later to discuss some questions on this

**Comment by JSJohal** [comment]
Discussed this with Claire & Dom today.
Some more work to do on content regarding phrasing of question, [comments are here on the board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=k9laLolFr0Q-&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)

**Comment by gracecbrennan** [comment]
Jas needs to review Dom's content changes and will add to prototype - then we can decide next steps on this

**Comment by JSJohal** [comment]
![Image](https://github.com/user-attachments/assets/be27e16b-73cc-4700-a4fb-0626bf6a353f)
Latest content / design for this page, a couple of tweaks identified to make:
- be more explicit with the hint text that the name won't change on the record and the SIT needs to tell the ECT to also change the name using the AYTQ service
- consider changing 'Teaching Regulation Agency records' to 'teaching record'

**Comment by claire-hughez** [comment]
To just give complete clarity on my point, the last sentence there, 'If these details are incorrect, go back and check details', I don't think sufficiently differentiates from when the name is incorrect for the right person.

I think that last sentence needs to make clear 'If this is not the person you were trying to register as an early career teacher, go back and check details'.

**Comment by JSJohal** [comment]
@Dom-Collins is reviewing content as mentioned above

**Comment by gracecbrennan** [comment]
@Dom-Collins has updated the content and @JSJohal has started adding into prototpye

**Comment by JSJohal** [comment]
![Image](https://github.com/user-attachments/assets/fad27ec9-7904-4cc1-b755-86d420792c5a)
Added into [new version of the prototype](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/review-ect-details) (p: review) as in the screenshot above.
