### ISSUE TITLE
Appropriate Bodies delivery planning

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/register-early-career-teachers#248]
## Why?

The database of qualified teachers and existing TRA owned AB portal must be switched off by April 2025. The business case and funding runs out so we won't have money or a mandate to delay this work any further. 

The TRA will find migrating induction data to TRS significantly less risky if a replacement AB portal is created. 

As owners of induction data, and because of doing an induction discovery in 2024, CPD are best placed to decide what an AB MVP could look like and plan how to get there

## What?

Drafting here https://lucid.app/lucidspark/17be7960-2487-4c49-bdb6-15c144f8c2fb/edit?view_items=~H89a72.7RjP&invitationId=inv_8fa9969b-e457-4912-b015-1ada6a848ff1

## Out of scope 

- Deciding people plans post go-live
- Migration planning - this will be covered with TRA Transformation separately
- AB Comms - this will be covered with Colin separately

## Helpful links or other information

**Comment by claire-hughez** [comment]
Planning data migration with TRA this morning.

**Comment by emily-prudence-dfe** [comment]
Moving this to done as roadmaps are combined [here](https://lucid.app/lucidspark/5948b629-f160-4955-978d-996cb6b8689f/edit?viewport_loc=-19154%2C8333%2C2846%2C1478%2C0_0&invitationId=inv_5e8f1ff0-1a91-4bc6-b8e8-b5dd12b7a838)

Further delivery planning work as part of BAU roadmapping
