### ISSUE TITLE
Run session for lead providers to get their thoughts on the data model and problems to address for 2.0 ☁ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#25]
## Why

We want to check in with lead providers to see  if our suggested data model makes sense for them.

We also want to understand if we’ve covered their problems and issues in the discovery, and if there’s any more useful data we could gather.

We might want to highlight any potential impacts 2.0 changes would have on them.

## What

- Create schedule for session
- Create slides
- Plan how to gather feedback from LPs
- Run session

## Context & links

?

**Comment by claire-hughez** [comment]
Run a session with lead providers so we can confirm the problems we've identified, demonstrate data model and any prototype ideas and highlight any possible impacts on them ☁️

**Comment by gracecbrennan** [comment]
We did agree August for this session with LPs. 

Claire is going to make a start on this.

**Comment by claire-hughez** [comment]
For this, we should:
- send them bits of reading in advance
- collect feedback beforehand
- have conversations around questions and concerns
- run session walking through session
- make sure to take notes in session

**Comment by claire-hughez** [comment]
Lead providers are off on annual leave for a bit, so hoping to wait a few more days before a follow up email.

We can't schedule it in until then.

No updates or info from then yet.

Will either be very end of August on the 29th. Or a separate session in early September. No response on problem collation either, but Mili will chase again.

**Comment by gracecbrennan** [comment]
A session to be organised with the team to discuss how we want to use the session and what we want to get out of it. 

@gracecbrennan to schedule.

**Comment by claire-hughez** [comment]
Notes from previous LP meetings:
- Include mentions to sandbox and testing
- Include mentions of dual running
- Include deviation from happy path, changes that happen to ECTs

**Comment by claire-hughez** [comment]
Would be good to ask for each lead provider's technichal representatives to come to that session.

Some lead providers might not have that though, so we should ask.

We think the data model stuff should be simple and a brief overview of the problems and that we're working to make it that efficient.

They're interested in the API and potentially what schools will be doing.

Trying to be more reliable and consistent. They might not need to know the details.

How we're doing the project and how we're approaching the work.

We'll want feedback as they go, MVP will be iterated. Get more of an idea of what we're doing. Maybe not too much detail.

Is there anything we can currently do to reassure them on dual running (having records in the old contract, e.g. CIP FIP DIY, and new records, e.g. School-led and provider-led). 

Let's ask if the 2025 changes to programme types are retrospective or not.

**Sandbox and testing**
NPQ are about to launch their MVP, it's a sandbox with liveish data that lead providers can test against. Giving them a realistic testing environment.

We'll be trying to copy and learn lessons from how that sandbox and testing work goes for ECF2. We'll be kept updated with the teams responsible for that and try to do something similar with any issues addressed.

**Comment by claire-hughez** [comment]
There might be helpful reasoning for why we're focusing on the data model in here: https://teacher-cpd.design-history.education.gov.uk/ecf-v2/designing-the-database-first/

**Comment by gracecbrennan** [comment]
@claire-hughez and @kerry-b-dfe to discuss proposal for session with lead providers

**Comment by claire-hughez** [comment]
On ECF2 release date, we’re not having this in ready for 2025. But releasing a new service for 2025 when there’s a lot of changes and beginning of cycle is quite risky. We’re planning to do it outside registration peak. It will be after registration peak. After the peak but before the next registration cycle.

Minimise impact on lead providers. The changes in temrs with integrating with API will be similar to NPQ separation.

**Comment by gracecbrennan** [comment]
Met with policy and engagement team yesterday to discuss and test ideas. 

@claire-hughez to input ideas from that session into slides.

**Comment by claire-hughez** [comment]
https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B4D9CDF18-4B0E-4B06-A6A1-2F0433E62797%7D&file=Lead%20provider%20session.pptx&action=edit&mobileredirect=true

**Comment by gracecbrennan** [comment]
@claire-hughez is going to keep chipping away at this ticket this sprint (and looking to confirm date with Mili)

**Comment by gracecbrennan** [comment]
For review please @kerry-b-dfe and @mason-emily !

**Comment by claire-hughez** [comment]
This will now be October 2nd. Would be good to get @kerry-b-dfe's review - think Emily M already reviewed it.

**Comment by kerry-b-dfe** [comment]
Reviewed.
Have added comments and added in a form for them to express interest in research sessions at the end.

**Comment by gracecbrennan** [comment]
@gracecbrennan to check and suggest changed and add new team members

**Comment by gracecbrennan** [comment]
Check if there's any next steps on this and then look to close
