### ISSUE TITLE
Create proposal for how services should be separated and named in ECF2 ✏ 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#26]
## Why

In the current ECF services, all users gain access from 1 login page:

[https://manage-training-for-early-career-teachers.education.gov.uk/](https://manage-training-for-early-career-teachers.education.gov.uk/ "smartCard-inline")

We should consider if we wanted that to include, or if we want a better alternative.

There is evidence in discovery findings that access to the service is a painpoint, and terminology used to refer to the services is inconsistent.

## What

Create a proposal to include:

- how should the services for the different user groups (AB, internal, schools, and could potentially consider LPs for later) be separated
- should they all be accessed from the same url
- what could we explore or do next to name them
- please take into account check data for ABs and how later ABs will need to submit induction data in the same service

## Context & links

???

**Comment by Dom-Collins** [comment]
[Initial front page ideas for ABs and school users.](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/ESsxdLL6wqVFgAbMaEfMIYgBvV05ryFuSCZA5_dqFFpicw?e=TtYXhM)

**Comment by gracecbrennan** [comment]
@Dom-Collins is going to have a look at comments and respond today.

**Comment by mason-emily** [comment]
Dom has responded to most comments, working on last ones today

**Comment by gracecbrennan** [comment]
This ticket is now complete :)
