### ISSUE TITLE
Design variants of 'which AB' screen for independent / BSO schools

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#261]
## Why? What's the need?

We've prototyped an add ECT journey as part of #124. However, we've need to create variants for independent & BSO schools which provide specific options to them for AB.

## Success criteria / when is this ticket done?
- Create wireframes / design in prototype for asking AB for independent schools (that has ISTIP) as an option

## What's out of scope
We don't need the one for British over seas schools. They don't need to register ECTs.

## Helpful links or other information

> Insight from Nathan regarding circa 80% of schools using same DP as AB
> 
> 80% figure is definitely only relating to state-funded schools
> 
> It's n/a for all British Schools Overseas (BSOs) and for most independent schools because they are not state-funded and cannot access DfE-funded training [with the exception of a few hundred independent schools in receipt of "Section 41" funding
> 
> So if an independent school chooses Istip as their AB, they are most likely going to pick CIP / DIY / "School-led" for their training. If they do have S41 funding, then Istip are not a training delivery partner and the school will use someone else for training
> 
> And likewise, if a BSO chooses ESP as their AB, they have to pick CIP / DIY / "School-led" for their training

**Comment by claire-hughez** [comment]
Try to replicate ECF 1.

**Comment by claire-hughez** [comment]
@JSJohal to add screenshots.

**Comment by claire-hughez** [comment]
Wouldn't need the overseas one. But would need the independent one, as they could be state funded if Section 41.

**Comment by claire-hughez** [comment]
Awo is looking at this.

**Comment by gracecbrennan** [comment]
We don't need the BSO. We only need to cover the Independent schools.

**Comment by aabdi18** [comment]
Added a radio option for ISTIP and slightly tweaked the question 

![Image](https://github.com/user-attachments/assets/f05b8372-400f-4aff-b549-9ed8d57be55f)

not sure if there needs to be a statement for if the type of AB isn't listed like in ECF1 'if any of your ECTs work with a different AB you can tell us later'

**Comment by gracecbrennan** [comment]
Awo and Jas to catch up and check whether additional statement is needed

**Comment by JSJohal** [comment]
![Image](https://github.com/user-attachments/assets/0f7e4995-1e95-427b-a784-2bf47b6d7738)
Slight change to heading after discussing with @aabdi18.

Still need to review content for the 'details' (drop-down), as it's not accurate to say ABs are TSHs, as for this small group (independent schools that receive funding), they have ISTIP as an option also (which isn't a TSH).
GitHub link to prototype page here: https://github.com/DFE-Digital/ecf2-prototype/blob/v4/app/views/v4/other-pages/add-ect/funded-ind-appropriate-body.html

CC: @claire-hughez @robthompson16

**Comment by gracecbrennan** [comment]
Rob and Jas to have a chat on this today

**Comment by gracecbrennan** [comment]
Content has been reviewed and updated. 

@claire-hughez to have a look.

**Comment by claire-hughez** [comment]
looks good to me! :)
