### ISSUE TITLE
Confirm process for DQT records with active flags (alerts)

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#276]
## Why?
In ECF1, we check a participant's DQT record for 'active flags' when they are registered. If there is a flag, the product/support team manually notify the policy & engagement team who review and confirm whether the flag can be overridden to make the participant eligible for training/mentoring.

## What?
- We need to confirm the process for active flags in ECF2 - replicate the as is or potential improvements?
- We need to confirm what TRS data we need for this & how to get it

## Helpful links or other information
https://ukgovernmentdfe.slack.com/archives/C03RM65L928/p1704982399800289

**Comment by mason-emily** [comment]
Spoke to Colin:
- Numbers of ECF participants with active flags is extremely low - Colin estimates 2 in the last 18 months.
- In ECF1, active flags block eligibility for funding until Policy & Engagement team have manually reviewed and overwritten. The manual review involves looking up the participant's DQT record and checking the notes section for the relevant entry that explains the flag. 
- 99% of the time we can ignore the flag and allow the participant to be eligible - we mainly look for teacher misconduct / if the person is barred from teaching.

There will be [changes to alerts](https://educationgovuk.sharepoint.com/:p:/r/sites/TRATransformationTeamDocs/Shared%20Documents/General/TRS%20Products/Alerts%20Migration/Alerts%20data%20governance%20proposal.pptx?d=w16158508212a421093596a6b0dd8a4c9&csf=1&web=1&e=ep70gv) in the TRS migration. I need to confirm what specific DQT data we use in ECF1 and if there will be any changes to this. 

Suggest we can probably use a very similar manual process since numbers are so low - possibly more specific to an alert type if there's something better available. Also need to consider how we will surface those few cases.

**Comment by gracecbrennan** [comment]
There's some work happening on the AB side of things that will inform what we do. 

Suggestion that this is now dependent on that happening firs to avoid duplication.

**Comment by mason-emily** [comment]
Dependent on bod squad ticket #516 - we'll probably be able to copy the same rules for RECT

**Comment by claire-hughez** [comment]
reviewed!

**Comment by gracecbrennan** [comment]
Emily will take a look at the comments in thsi

**Comment by claire-hughez** [comment]
Emily is writing up a comment, kinda agreed. Quick design ticket for extra dead end page.

**Comment by mason-emily** [comment]
We've confirmed it is the policy steer that the only alert serious enough where a teacher wouldn't be funded for training would be if they were barred from teaching (for both ECTs and mentors). There is an edge case where a school might want to add a mentor for mentoring only who is barred from teaching, because it's at the school's discretion, but it is very unlikely this would happen.

We want to take a similar approach to how alerts are handled for the AB portal (which is already being built). The proposed approach for Register ECTs is to:
- Block ECTs and mentors from being registered by a school if their TRS record has an alert in the category of 'prohibition from teaching'. We will need a 'dead end' page that blocks the journey in this case. This page should not surface information about why the ECT or mentor is blocked from registration as that is sensitive information and not the purpose of our service.
- For all other alerts on an ECT or mentor's TRS record, we will allow the school to register them as normal and will not surface any information about the alerts.

@claire-hughez anything missing?

**Comment by mason-emily** [comment]
Design ticket created: https://github.com/DFE-Digital/register-early-career-teachers/issues/715
