### ISSUE TITLE
Plan questions to bring to engagement sessions with lead providers

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#285]
## Why?

After our engagement session and UR, there might be some follow up questions we have for lead providers.

## What?
- Plan questions
- Send them over to the policy and engagement team with at least 2 working days notice

**Comment by gracecbrennan** [comment]
will reschedule for when Emily.M is back in

**Comment by claire-hughez** [comment]
What to ask them:
1. Priority of knowing DP, versus just a school's indication of interest to work with their LP
2. Multiple SITS

**Comment by claire-hughez** [comment]
https://educationgovuk.sharepoint.com/sites/TeacherServices/_layouts/15/doc.aspx?sourcedoc={766b8187-9f10-4d29-8b50-b79425b4ea2d}&action=edit

**Comment by gracecbrennan** [comment]
@gracecbrennan @kerry-b-dfe @mason-emily to review slides for first session

**Comment by gracecbrennan** [comment]
I've reviewed - slides are super clear and cover parts LPs are going to be interested in. 

I had one question on the API slide but might just need clarification for my own understanding.

**Comment by gracecbrennan** [comment]
This is on the agenda to discuss with programme leads. 

We will also put it in front of policy and lpdob

**Comment by mason-emily** [comment]
Checking with policy and engagement later today

@kerry-b-dfe to look over too
