### ISSUE TITLE
Investigate the use of optional fields in reg journey

### ISSUE THREAD

**Issue by consult1815** [DFE-Digital/register-early-career-teachers#286]
We want to understand how frequently and how accurately schools complete the optional fields when registering their participants to understand whether or not to continue requesting they complete these fields.

**Comment by claire-hughez** [comment]
Claire and Emma catching up today

**Comment by claire-hughez** [comment]
Transfer journeys treat this different. Need to focus on some other work first.

**Comment by gracecbrennan** [comment]
This is paused atm and will be picked back up again on Monday

**Comment by gracecbrennan** [comment]
Is hoping to pick this back up tomorrow.

**Comment by claire-hughez** [comment]
Emma H to ask Tony about question to get some info for this ticket.

**Comment by gracecbrennan** [comment]
Emma has run the analysis and has insights which she will share for review.

**Comment by gracecbrennan** [comment]
Emma will add deets to this ticket

**Comment by consult1815** [comment]
Here's the analysis on FIP schools added ABs on the register service for the 2023 Academic Year. Here are those findings + the absolute value & percentage breakdowns across the groups. I'll add this to the ticket and Sharepoint if you'd like to look at the analysis in more detail. Let me know if you have any questions, I'm happy to chat through these findings.

**Top Line: The vast majority of Schools and ECTs have ABs provided and this is most often provided at the point of registration. Schools that report their AB after their training details more often than not appear to provide this before registering their ECTs, ensuring those ECTs have ABs at the time of registration.**

80% of FIP schools in 2023 provided their AB and 92% of ECTs had their AB provided at some point. This was most frequently provided during registration. 69% of schools provided their AB during registration compared with 90% of ECTs who had their AB confirmed/provided in registration.

83% of ECTs have their AB provided in Reg and it matches the school AB. 7% of ECTs will have an AB provided that doesn't align with what is currently what the school has reported as the school's AB (Either the school has a different AB or they haven't provided an AB in their training details)

12% of schools add their AB after providing their training details. Of the ECTs at these schools, 599 (34% of all 2023 FIP ECTs) had their AB confirmed as the same as their school's AB in registration indicating that their schools had already updated the system with their AB prior to registering their ECTs. 376 ECTs (21% of 2023 FIP ECTs) had their AB updated post registration and their provided AB matched the AB added later by their school, indicating the school had not provided their AB prior to registering ECTs.

*Whether an AB was added in registration was determined by whether the AB id was assigned to the corresponding school cohort or induction record within 15 minutes of its creation.

**Comment by consult1815** [comment]
Slack chat link: https://ukgovernmentdfe.slack.com/archives/C06V31R0Z17/p1727434268722669
