### ISSUE TITLE
Investigate how frequently ECT's are assigned a mentor in their registration journey

### ISSUE THREAD

**Issue by consult1815** [DFE-Digital/register-early-career-teachers#287]

**Comment by gracecbrennan** [comment]
On my ticket, I've clarified how we collect mentor associations in our data model and have pulled the data I need. I'm going to analyse it this morning and will share my findings today.

**Comment by claire-hughez** [comment]
No updates yet, tomorrow or Friday

**Comment by gracecbrennan** [comment]
Emma has so time to look at this today

**Comment by gracecbrennan** [comment]
Nathan is taking a look over this and it will be shared later

**Comment by consult1815** [comment]
[ECT & Mentor Registration Timelines.pptx](https://github.com/user-attachments/files/17489154/ECT.Mentor.Registration.Timelines.pptx)

**Comment by consult1815** [comment]
Presentation Link: https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Analysis/ECT%20Mentor%20Registration%20and%20Assignment%20Timeline%20Analysis%20-%20Presentation.pptx?d=w8b12a130a5af44a096ebf4a4c8509c6f&csf=1&web=1&e=hwizBE

Analysis Link: https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Analysis/ECT%20Mentor%20Registration%20and%20Assignment%20Timeline%20Analysis.xlsx?d=w07463a024bc44367a9eef44daded4e7f&csf=1&web=1&e=u7LZa8
