### ISSUE TITLE
Design for when an ECT already has an induction completion date and cannot be registered

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#317]
## Why?
One of the unhappy paths in the Add ECT journey is when an ECT already has an induction completion date on their DQT/TRS record. This means they have already completed induction and would not be eligible for further funded ECT training. These ECTs should not be allowed to be added to the service.

## What?
- Consider design for when the TRN & DoB check on the Find an ECT page find an ECT that already has an induction completion date
- Consider how to point them to support if somethings gone wrong

## Helpful links or other information
https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=stv~2N7D9QMz&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6

**Comment by gracecbrennan** [comment]
Jas has just added placeholder page to prototype - will catch up on this one today with Rob too

**Comment by robthompson16** [comment]
I've created some draft content here: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

Is there anywhere else we can point a user to if they think there's an error? How likely is this scenario?

**Comment by JSJohal** [comment]
https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=TquoU1yRy1dS&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b

This looks good to me @robthompson16!

**Comment by claire-hughez** [comment]
Has the question been answered on whether or not we should point to contact support or their AB?
