### ISSUE TITLE
Design for when an ECT has an induction status of 'exempt' and cannot be registered for training

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#318]
## Why?
One of the unhappy paths in the Add ECT journey is when an ECT an an induction status of 'exempt' on their DQT/TRS record. This means they are exempt from induction and would not be eligible for further funded ECT training. These ECTs should not be allowed to be added to the service.

## What?
- Consider design for when the TRN & DoB check on the Find an ECT page find an ECT that has a status of exempt.
- Consider how to point them to support if somethings gone wrong

## Helpful links or other information
https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=stv~2N7D9QMz&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6

**Comment by robthompson16** [comment]
Created some draft content here: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

Do we want to include a list of possible reasons for exemption?

**Comment by gracecbrennan** [comment]
@claire-hughez and @mason-emily to review please

**Comment by JSJohal** [comment]
https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=Chwoyx.H8fsj&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b

@robthompson16 looks good. Not sure about adding the possible reasons someone might be exempt - wondering if it may add confusion, and also about how many reasons there could be

**Comment by claire-hughez** [comment]
I think we should be more specific here than just ineligible. I think saying they are exempt from having to serve induction in schools but are fine to teach or something is important. Someone could be ineligible for other reasons.

**Comment by robthompson16** [comment]
@claire-hughez what do you think of v2?
![image](https://github.com/user-attachments/assets/6d2b07ad-dd57-492d-9cb1-bf9eeee7e8b3)

**Comment by mason-emily** [comment]
Are they definitely always still fine to teach if they're exempt?

**Comment by JSJohal** [comment]
![image](https://github.com/user-attachments/assets/d11194b1-c5a5-488c-91df-1a0205200667)

https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-ect/induction-status-exempt (p: review)
