### ISSUE TITLE
Design for when an ECT is already registered for ECT training at the school and cannot be re-registered for training

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#320]
## What?
- Tell the school that they've already added that person as an ECT 
- Point them to support if needed

## Helpful links or other information
https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=stv~2N7D9QMz&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6

**Comment by claire-hughez** [comment]
Could this be used for mentors too?

**Comment by claire-hughez** [comment]
@mason-emily to add content

**Comment by robthompson16** [comment]
I've drafted some content here: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

I have a question around whether a user would require any additional support in this scenario.

This content would also work for trying to add a mentor who's already been registered

**Comment by claire-hughez** [comment]
Is it more helpful to say 'ECTNAME has already been registered at your school'

As we'll have more than 1 user per school, it might be a different person that registered them, so 'you' feels a bit less accurate here

**Comment by robthompson16** [comment]
Like your suggestion @claire-hughez but is it ok to say 'your school'? Sorry but still a bit unclear about it all! 

For the moment I've left it as '[ECT name] has already been registered' which might be sufficient anyway

**Comment by claire-hughez** [comment]
HEy Rob! I think 'your school' is fine because it's always the same.

My worry with using 'your' for 'YOUR ECTs' or 'YOUR mentors', is that mentors and ECTs have an ECT or have a mentor, and I think it could get confusing

**Comment by JSJohal** [comment]
![image](https://github.com/user-attachments/assets/980480e3-dd9c-4a84-8a20-e72883e210a8)

https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-ect/ect-already-registered (p: review)
