### ISSUE TITLE
Find all the unhappy paths when adding a mentor

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#322]
## Why?
We want to make sure we've considered all the unhappy paths that can be reached whilst registering a mentor.

We need to do this so we can design the pages users see when DQT checks fail or something else hasn't worked successfully. 

## What?
- Consider the add a mentor journey and what could go wrong
- List all these unhappy paths and any ideas for how to help with them
- This should pass to design to consider how to help users in these unhappy paths afterwards (e.g. filling in a support form, re-entering details)
- An output of this could be a map (without visuals) of these different unhappy paths and endings. We could populate this later with wireframes/visuals of adding a mentor in the new service.

One example of an unhappy ending here is when the school user has a DFE Sign in account, but has not been given approval to access the Register early career teachers service.

## Out of scope
Actually mocking up or prototyping pages in these unhappy paths.

**Comment by mason-emily** [comment]
https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sHSbGs2FFnE0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b

**Comment by claire-hughez** [comment]
Toby brought up the good point:

How do we handle name, when the mentor used to be an ECT?

For example, if an ECT with the name John Smith is registered in our service, but the name is overrode to be John Smith-Bryant, if they're later registered as a mentor, what name do we use?

**Comment by mason-emily** [comment]
Review with Nathan scheduled tomorrow and review with Jas, Tony & Claire on Thursday

**Comment by mason-emily** [comment]
Map here: https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=J.CkAzqM6qu1&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6
