### ISSUE TITLE
Add the appropriate body flow for recording an induction outcome

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/register-early-career-teachers#340]
The claim flow allows an appropriate body to record an induction outcome for an ECT. It's fully outlined in https://github.com/DFE-Digital/register-early-career-teachers/discussions/253.

![Image](https://github.com/user-attachments/assets/17e034bb-8ee8-4169-a847-8a31722e4036)

**Comment by peteryates** [comment]
Sorry I did this already in #405.
