### ISSUE TITLE
Validation on number of terms

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/register-early-career-teachers#341]
Discussion [here](https://github.com/DFE-Digital/register-early-career-teachers/discussions/410)

### What?

We need to define validation rules for terms, because policy has changed and the legacy AB Portal is not in alignment with this.

### Why?

The long-term vision for calculating the number of terms of induction time an ECT has served is to be able to do this automatically, this is not possible currently with the data we have available about ECTs. For the MVP of an AB Portal replacement, a decision has been made to continue to ask ABs to manually input the number of terms an AB has completed at the end of each induction period.

The legacy AB Portal only allows terms to be recorded in integers. This was in alignment with previous policy, which only allowed for full terms to "count" towards an induction. The policy has since been updated to allow fractions of terms to "count" against an induction, with specific rules accounting for working patterns, and the validation on the new AB service should align with these policy rules. The guidance referred to can be found [here](https://assets.publishing.service.gov.uk/media/661d459fac3dae9a53bd3de6/Appropriate_bodies_guidance_induction_and_the_early_career_framework.pdf)

**Comment by claire-hughez** [comment]
Need to talk with the team first how to technically do this.

**Comment by claire-hughez** [comment]
Will talk through on Thursday.

**Comment by kas-madrigal** [comment]
Next steps

- Request conversation with policy team to ask if we can bin terms off entirely.
- Ask induction support team (Komal) the value and behaviour of terms. What would they find easier to track, half terms or decimals? (agenda for Tuesday)
- We plan to test half terms and one decimal place in round 2

**Comment by gracecbrennan** [comment]
Didn't get around to discussiong with Phil yday but tied in with extension conversation

**Comment by claire-hughez** [comment]
Emily P will share some stuff around extensions which is tied in

**Comment by gracecbrennan** [comment]
Another call needs to happen with Korin on this as it's more of a complex thing to check

**Comment by gracecbrennan** [comment]
Korin is on leave - this will need to be handed over to Kas to pick up next week. 

Or maybe Joe??

**Comment by gracecbrennan** [comment]
Meeting with Korin happening tomorrow.

**Comment by gracecbrennan** [comment]
Doing it on a half-term basis doesn't give us the specificity we need. Decimal is probably the best-fit.

**Comment by gracecbrennan** [comment]
@joe-harrison-dfe to add notes from meeting

**Comment by joe-harrison-dfe** [comment]
Summary notes:
- Decimals are more helpful as they are more specific
- Half-terms not ideal as wouldn't account for facts within policy as it restricts you to half terms
- Would still need rounding for decimals as it goes to one decimal place. 
- As it is done using decimals in ECT manager, shouldn't be a problem getting ABs to use this measure
- As long as we are recording employment period as well as induction period then should be all fine as we have the 2 years of total employment eligibility rule to consider as well.

**Comment by gracecbrennan** [comment]
This is going to be reviewed in catch-up today with a view to close.
