### ISSUE TITLE
Research on extension inductions

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#352]
## Why?
Clarify extension decision-making. Is it going to affect the steps upstream and downstream of the CPD journey for internal teams as well as end users?

## What?

- Initial research done. 
- I have a call with grant funding on Friday 27th Sep and are in conversations with TRA. 
- Will create a short summary tracking the research and conclusion.

**Comment by gracecbrennan** [comment]
Kas is chatting with TRA on this and has a call with grant funding team on Friday.

**Comment by kas-madrigal** [comment]
I spoke with grant funding on Friday, we are OK to get rid of extension status and not yet completed status. They are doing a final check with their code to make sure nothing will be broken. I think we need to keep this for TRA's sake but not create any user flows for it, a hidden 'extended' status but no 'not yet completed' status.
