### ISSUE TITLE
Confirm we have exhausted system rule 'unhappy paths' on AB portal

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#354]
## Why?
To make sure we have covered all bases before redesigning any system rules necessary. 

## What?
We need to schedule a call with Evie 
Prepare call with an activity/task to help her go through the process with us

**Comment by kas-madrigal** [comment]
we are waiting on Evie to schedule a call

**Comment by claire-hughez** [comment]
Going to cover this with Phil and Komal.

**Comment by claire-hughez** [comment]
Emily is writing this up, 99% there, so Phil and Komal can comment on it. Emily P will send this over today.

**Comment by gracecbrennan** [comment]
@emily-prudence-dfe has shared this on channel for review and will follow up with Phil and Komal tomorrow

**Comment by gracecbrennan** [comment]
Dependent on alerts and the conversation around how they will be cleared up. 

This will then be included in the summary doc

**Comment by claire-hughez** [comment]
No logic in the TRS to build anything to distinguish alert.

AB service will show the alert, but won't block it from being continued.

Can't block them as it has to be conditional on type of alert.
