### ISSUE TITLE
Match unhappy user paths to system unhappy paths

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#355]
## Why?
This exercise will help decide how many new flows in the AB portal need to be user journeys and how many need to be system/service rules. 

## What?
Create a new map that overlaps the two existing maps 
- Unhappy user journeys
- System unhappy paths

**Comment by kas-madrigal** [comment]
I am on this.

**Comment by gracecbrennan** [comment]
Kas is going to continue analysis on this today

**Comment by kas-madrigal** [comment]
- Release - done
- Reduce - kinda done?? not a thing apparently
- Transfer - done 
- Extended - done

There are questions to be resolved, I have asked devs in TRA and Komal in support AB portal team

**Comment by gracecbrennan** [comment]
Kas and Emily catching up on this today

**Comment by kas-madrigal** [comment]
Have updated these in the excali directly to be consistent with the way we are doing lofi stuff but can add this to a doc if necessary

https://excalidraw.com/#json=DZ0rZ4TLZ9rqqWSRnnapc,5jZGI136mZbJpyQGmAEV-Q

**Comment by gracecbrennan** [comment]
@peteryates @emily-prudence-dfe @edujackedu to review
