### ISSUE TITLE
Write design history our our new service name

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#363]
## Why?
We have a name! Register early career teachers.

We should explain why we've chosen this name, and how it tested.

## What?

- [x] Write design history entry
- [ ] Release the design history entry

**Comment by gracecbrennan** [comment]
First draft almost ready for review.

**Comment by Dom-Collins** [comment]
Didn't get round to reviewing this before sharing, will do so after AL.

**Comment by Dom-Collins** [comment]
[Design history draft](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/Ee_KhEV-3WdMlVCpMo-Ki4MBVohpz21acqzRZJXJrmRHSQ?e=IE0mWR)

**Comment by Dom-Collins** [comment]
Hi @claire-hughez @JSJohal please can you have a look at the [DH first draft ](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/Ee_KhEV-3WdMlVCpMo-Ki4MBVohpz21acqzRZJXJrmRHSQ?e=IE0mWR)for naming the SIT service?

**Comment by claire-hughez** [comment]
Dom, this looks great. Left some thoughts in the doc. Thank you for writing such a clear and thorough design history.

**Comment by gracecbrennan** [comment]
Dom will address comments today
