### ISSUE TITLE
Engage with the strategic design team on the guidance they're planning for ECF

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#369]
## Why?
In our last UR round, many users expressed anxiety and the need for reassurance about when and where to register their ECTs.

They were confused about the sequence of who they need to register their ECTs (and mentors) with, and when they know they're done.

In particular, we agreed as a team that where we feel we need guidance is explaining to schools the wider registration ecosystem beyond just the DfE digital service, and how it all connects together.

We also agreed that we need to make it clearer that registration should be done with DfE, on Register ECTs, first.

## What?
- Reach out to Strategic Design
- Talk about our UR findings
- Find out about their guidance work
- Plan next steps

## Out of scope
We're not writing any guidance in this ticket. We're trying to work out what to do next and make sure we stay aligned.

## Helpful links or other information
[Slide 14 in Rose's UR Playback](https://educationgovuk.sharepoint.com/:p:/s/TeacherServices/EdPoJBQRvptFvqslZ9aSrRcBrAPm62_i6zigfdnFd1-YUQ?e=dTcfBj)

**Comment by gracecbrennan** [comment]
Tagged Esther and Eric - who should hopefully come back when they return from leave

**Comment by gracecbrennan** [comment]
Going to meet with SDT on thursday in office
