### ISSUE TITLE
Make simple content changes to the prototype from research

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#370]
## Why?
There were some small content changes that we think will make the service clearer for school users.

## What?

- [x] Tweak heading when you input TRN and DOB from 'Add' to 'Find an ECT'
- [x] When asking the SIT for an ECT's email address, add content on how they can update the email given later
- [x] Add info from the toggle section to the radio buttons on the programme choice page and mention provider-led is funded by DFE
- [x] Add hint text that the default choices they set won't impact already added ECTs
- [x] Consider tweaking content on time off timetable funding on frontpage before sign in

## Out of scope
Surfacing all the details they need for registering ECTs and mentors is in another ticket.

## Helpful links or other information
[UR findings here](https://educationgovuk.sharepoint.com/:p:/s/TeacherServices/EdPoJBQRvptFvqslZ9aSrRcBrAPm62_i6zigfdnFd1-YUQ?e=dTcfBj)

**Comment by Dom-Collins** [comment]
Responded to small content changes, [see PR](https://github.com/DFE-Digital/ecf2-prototype/pull/12)

**Comment by gracecbrennan** [comment]
@JSJohal to merge in Dom's absence

**Comment by JSJohal** [comment]
merged into https://github.com/DFE-Digital/ecf2-prototype/tree/v3 which will in turn be merged into main when design work for sprint completed
