### ISSUE TITLE
Surface specific pieces of information needed for registration of ECTs and mentors on frontpage of schools service

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#371]
## Why?
School users don't have much time. In research, they reported that they'd put time aside to register ECTs and mentors, and want to know as soon as possible what information they need in order to register them.

They want to know before they even sort out sign in what pieces of info they need, so they can gather it from the ECT, mentor or admin staff at the school.

They feel like otherwise, they might go to the form to register an ECT, and find out they don't have the vital pieces of info they need. This will block them and waste their time.

## What?
Surface the specifc information needed to add an early career teacher or mentor

This would be:
- TRN
- DOB
- name
- email address (might be worth mentioning it can be updated later?)
- appropriate body
- school led or provider led 
- delivery partner
- lead provider
- start date
- what ECTs and mentors are assigned together

## Helpful links or other information
[UR findings here](https://educationgovuk.sharepoint.com/:p:/s/TeacherServices/EdPoJBQRvptFvqslZ9aSrRcBrAPm62_i6zigfdnFd1-YUQ?e=dTcfBj)

**Comment by claire-hughez** [comment]
Wait for this until adding a mentor has been sorted at least.

**Comment by gracecbrennan** [comment]
Draft is complete if @JSJohal / @claire-hughez can review

**Comment by claire-hughez** [comment]
reviewed, thanks Dom

**Comment by JSJohal** [comment]
looks good to me!
