### ISSUE TITLE
Work out how to solve the problems found in UR in asking schools for AB, LP and DP information

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#372]
## Why?
In user research, school users were very confused when we asked them about ABs and DPs.

Several users thought 'provide training' meant their lead provider. However, they liked the autocomplete.

Some users also expected to be asked about their AB first, which they more readily relate to and which is more established terminology.

In particular, they were confused when their AB and DP was the same, and thought it must've been their lead provider they needed to give.

Users also did not use the toggles to understand the questions or terms used more.

## What?
- Work out how we can solve the problems found in UR when asking schools for their AB, LP and DP
- Remove toggles

## Out of scope

We have another ticket for trying to tackle the problems where DP and AB name differs, and working out acronyms used for them

## Helpful links or other information

Some helpful ideas from the [UR playback](https://educationgovuk.sharepoint.com/:p:/s/TeacherServices/EdPoJBQRvptFvqslZ9aSrRcBrAPm62_i6zigfdnFd1-YUQ?e=dTcfBj) were:
- Russian doll model—starting with induction (AB) and then moving to what falls beneath that 
- Consider an agnostic approach to solving this, perhaps users select their LP and then we show them eligible DPs 
- Users most readily relate to their AB, which is also more established terminology. Consider asking for AB first and then ask if DP is the same entity
- Consider in-service guidance about the differences between LP, DP and AB or design the service in a way that does not rely on terminology 
- Trying to incorporate using the phrase 'Teaching school hub' more
- Possible to just ask LP & AB and not DP?

**Comment by gracecbrennan** [comment]
Jas is going to start work on this one today

**Comment by gracecbrennan** [comment]
WIP

**Comment by JSJohal** [comment]
Good discussion with team today regarding the different options.

To take forward:
- design a version which asks for AB and then asks if the DP is the same - conscious of the language we use here regarding TSH's, and not to use language such as DP which can be confusing
- design a version where we ask AB and then LP - with this option, we'd be using the LP answer to notify the LP and leave the DP to be reported by the LP

Plan is to flesh these two out as part of the prototype for the next round of testing and figure out how we'd like to test both.

**Comment by gracecbrennan** [comment]
Most of this is into prototype - except the content. 

Will review in session with Claire and Awo later and look to close.

**Comment by JSJohal** [comment]
Spoke about this today.
Bits to do:
- keep language around DP
- look to show LP within the DP question (gathered from AB choice)
- create secondary version with just LP question after AB

**Comment by gracecbrennan** [comment]
This was also reviewed yday and points above will be worked on by Jas today.

**Comment by JSJohal** [comment]
Been working on this on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=LjVeo73YnG3C&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)

**Comment by gracecbrennan** [comment]
Another catch up with Claire today and this might change slightly

**Comment by gracecbrennan** [comment]
A few things to tweak on flow changes today

**Comment by JSJohal** [comment]
I've made flow changes to the journey based on the review we did, these can be seen on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) and they're also in the [prototype (password is review)](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/setup-scenario-1).

May still be some content changes outstanding - suggest these are made on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) for now by @Dom-Collins and I can pick them up to put them into the prototype afterwards.

If any changes need to be made in the prototype while I'm on leave, they can be made on the [v3 prototype branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3) and they'll automatically deploy to the Heroku prototype environment. Probably easiest way would be to create a new branch off of the [v3 prototype branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3) to make changes, and then do a PR back into the v3 branch.

I've added checkmarks to the post-its for where I've made changes on the Lucid board

**Comment by mason-emily** [comment]
@claire-hughez & @aabdi18  might look at updating content in the prototype if Dom isn't back today
