### ISSUE TITLE
Consider how to ask school users for when the ECT is starting

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#381]
## Why?
If we're asking schools for the lead provider and delivery partner for an ECT, we need to understand when the ECT is starting.

We could rely on the logic that ECF1 uses, [which is detailed here.
](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B204706ED-50A6-4568-AA04-FA3F76BF78C0%7D&file=How%20the%20service%20determines%20cohorts.pptx&action=edit&mobileredirect=true)
However, it is probably more accurate and easier to ask schools for an indication of when the ECT is starting.

This is also still valuable for lead providers, even if we don't ask schools for LP or DP information.

## What?
- Add to prototype a question on when the ECT is starting at the school
## Helpful links or other information
The slides detail how it works in ECF1.

![Image](https://github.com/user-attachments/assets/9e5b1fba-cc82-48c2-b3d5-2f80a2a05ccf)
![Image](https://github.com/user-attachments/assets/5c3c4510-bab0-4b02-abf1-c7dc91f5f4c2)

**Comment by JSJohal** [comment]
![image](https://github.com/user-attachments/assets/008d50f9-4e14-4fcf-97a2-50f2cdb7cb2f)
![image](https://github.com/user-attachments/assets/ecb41829-2b7e-41c8-bbeb-079c3b3172a3)

Couple of draft screenshots

**Comment by JSJohal** [comment]
I've added two possible design options in the comment above for capturing start date, any preference on which to proceed with?
@claire-hughez @RoseAsaf @kerry-b-dfe @Dom-Collins

**Comment by JSJohal** [comment]
Possible content need to uncouple this question from training and focus on induction and working at the school.

**Comment by JSJohal** [comment]
[Latest designs in prototype](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/setup-scenario-1) and on [this GitHub branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3).
[Screenshots on this Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b).

Flows are generally complete, but still to be reviewed as an overall incl content.

**Comment by Dom-Collins** [comment]
> I've added two possible design options in the comment above for capturing start date, any preference on which to proceed with? @claire-hughez @RoseAsaf @kerry-b-dfe @Dom-Collins

Personally I prefer the month/year approach as it allows the user to be more specific about their start date and feels clearer to me. I will need to tweak that line below the question to make clear that we want to know the date the induction started/ended- not when the training started/ended.

**Comment by JSJohal** [comment]
I've made flow changes to the journey based on the review we did, these can be seen on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) and they're also in the [prototype (password is review)](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/setup-scenario-1).

May still be some content changes outstanding - suggest these are made on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=sPqgD44DXunV&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) for now by @Dom-Collins and I can pick them up to put them into the prototype afterwards.

If any changes need to be made in the prototype while I'm on leave, they can be made on the [v3 prototype branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3) and they'll automatically deploy to the Heroku prototype environment. Probably easiest way would be to create a new branch off of the [v3 prototype branch](https://github.com/DFE-Digital/ecf2-prototype/tree/v3) to make changes, and then do a PR back into the v3 branch.

I've added checkmarks to the post-its for where I've made changes on the Lucid board
