### ISSUE TITLE
Install and configure the DfE Wizard gem

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#383]
We'll be building several small (5-7 page) multi-step forms over the coming months and want to build them in a consistent way.

Following on from [the discussion](https://github.com/DFE-Digital/register-early-career-teachers/discussions/37) we have decided to give [dfe-wizard](https://github.com/DFE-Digital/dfe-wizard) a try.

It's probably more than we _need_, but it's already being used in DfE and is actively maintained, so it's worth considering.

## Tasks

* [x] Install and configure the dfe-wizard gem
* [ ] See how easy it might be to retrofit the AB claim journey. The paths are all nice, try to maintain them (do this as a separate PR)

**Comment by claire-hughez** [comment]
Jas will add the prototype link when he's finished it in the next day or 2

**Comment by gracecbrennan** [comment]
Getting a basic flow set-up with dummy data and will come back to discuss with other devs when this is ready.

**Comment by JSJohal** [comment]
[Prototype link](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/setup-scenario-1) for the version we're taking into research, password is review.

**Comment by TobyRet** [comment]
I have created a local branch and set up the DFE Wizard gem with a very simple flow. I have a conversation booked in today with Tomas Destefi from Apply to discuss the DfE Wizard gem and Apply's experiences with using it. 

@gracecbrennan it would be good to get clarification on expectations with regards as to what comes next for this ticket (retrofit the AB claim journey).

**Comment by TobyRet** [comment]
@claire-hughez - one of the outstanding tasks is to retrofit to an AB journey but should this ticket now be marked as complete given we will be starting on an ECT2 journey? 

CC: @mason-emily @peteryates

**Comment by peteryates** [comment]
Yeah I think we'll leave retrofitting for now, the AB journey only has 2 pages of questions so we can do it later when the pattern's established.

**Comment by claire-hughez** [comment]
Sounds good to me both. :)
