### ISSUE TITLE
Define round 1 user research priorities

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/register-early-career-teachers#396]
## Why?

We need to conduct research with appropriate bodies to understand more about how to meet their needs in a new service. 

## What?

- Workshop ideas for round 1 of user research
- Define priorities for the first round of user research with ABs

**Comment by gracecbrennan** [comment]
Meeting with AB team to talk through objectives in one and two.

**Comment by claire-hughez** [comment]
Putting together research plan (overarching view of what we're doing to end of year, with objectives and assumptions) and discussion guide for round 1. Recruitment begins today, Colin is sending out comms to the TSHs. Monitoring the form and will keep people updated.

**Comment by claire-hughez** [comment]
Recruitment is really good! 17 replies. Recruitment will be next week, and the round the week after.

Getting artefacts and discussion guide ready. You'll send some artefacts over tomorrow.

**Comment by gracecbrennan** [comment]
Rose will be sharing discussion guide today with Kas and Emily

**Comment by gracecbrennan** [comment]
Discussion guide frist draft is complete. A few questions left to iron out and then this will go to wider team.

Recruitment for 6 Abs is starting today. Hope to do round Friday,Monday, Tuesday

**Comment by gracecbrennan** [comment]
The round is going to happen Monday and Tuesday next week.

Still need to: 
- reach out to non TSH ABs
- Figuring out name to test 
- Getting artefacts ready
- Getting broader participation (TRA team to contribute to DG and fill up observation slots)

Also working with Emma.H to retrieve some search term data

**Comment by gracecbrennan** [comment]
We have recruited four people. 

Still looking for a non TSH AB - will follow up with Emily and Phil 

Discussion guide will be shared after lunch.

**Comment by claire-hughez** [comment]
Recruitment is done, need some more signups. So will ask people today.

6 participants signed up. Link is in the register Slack channel.

Will get infrastructure set up for rounds. Please sign up!
