### ISSUE TITLE
Decide on extension user flow post research

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#414]
What? 
We've done research on extensions, I have left a reccomendation on this page, it would be helpful for us to resolve together in a meeting. https://excalidraw.com/#json=DZ0rZ4TLZ9rqqWSRnnapc,5jZGI136mZbJpyQGmAEV-Q 

**About this ticket** 
![image](https://github.com/user-attachments/assets/d51cf1b0-1d67-4fda-a612-50d2d20b36f1)

**What we need to discuss** (from screenshot). 
The only thing that would be helpful from what I can see in the extensions research is to know whether an ECT has had an extension recorded. I would suggest it is a true/false data point and something to be raised on the admin console (whatever it is we create) for support team and grant funding team to view as it would explain extra declarations from LPs. This should be recorded in every version of the 'release' journey (release, outcome or change programme) as the ECT could be taking a break but not changing AB, changing school but not AB, etc... In the as-is when an ECT is released they are removed from the list of teacher an AB can see but I think we should allow them to see this data specially for extensions in case LPs need to have the AB resubmit information for any reason.

The AB needs to approve an extension with the LP so it's not (in theory, UR to test) an 'easy' process. I think we'd need to allow for 1 extension to happen per AB and record the stop(end, release) date of that ECT from the AB. What I don't know is if it's allowed on the policy to have extensions approved per AB you transfer to if you have justified absences (so the 'automatic' extension, not the extension related to not meeting standards)

**Comment by kas-madrigal** [comment]
Extension - 

- Extending number of terms someone needs to do 
- The automatic extension (absent for 30 days) has nothing to do with meeting standards and doesn't need approval from TRA/ABs
- The extension related to not meeting standards is a one-off extension from TRA/AB 
- LPs also submit declarations as proof of extra training for an extension

**Comment by claire-hughez** [comment]
Talking through extensions in more detail next Tuesday with Phil.

**Comment by gracecbrennan** [comment]
Emily is going to work on this today

**Comment by peteryates** [comment]
Yeah there's ~200 records with non 'Term' statuses (Days, Weeks, Months, Years) and we plan on converting them to Terms when we import them so we only have one unit to deal with.

**Comment by emily-prudence-dfe** [comment]
After clarifying with policy, it's technically possible (but unlikely) that multiple extensions can be added to an induction.
Ideally we'd be able to differentiate between extensions. e.g. if an ECT was granted an extension of 1 term, then got to the end of that term and didn't meet the teaching standards, they could have another 1 term extension added. The ECT would be able to appeal at each point they were awarded the extension, so it's useful to know which is which.
I think this has implications on our planned data model for extensions - we'd assumed a 1:1 relationship between inductions and extensions, but in reality it's 1:many. We don't necessarily need to build a way to support multiple extensions on the front end on day 1, but I think we should try to get the data model right.
We confirmed we're ok to record them all in terms.
