### ISSUE TITLE
Add AB claim flow exit/unhappy paths (checking the ECT's details)

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#418]
### **Screen 2**
![Image](https://github.com/user-attachments/assets/8b10c30c-d5fc-406f-a96a-ef2e9c3794d6)

Exits - system
- In the as-is a record may not be displayed if the teacher’s date of birth held within the database is incorrect. In order to update personal details, the teacher will needs to contact the TRA directly to have this rectified. **Maybe an idea to have a in-service form with the request to send to whatever form of admin console we create for the support team?**
- Teacher is currently undergoing induction with an AB, so if another AB tries to submit data for them it won't update the record. Can we surface a contact of the AB that needs to release the ECT?

Exits - policy
- There is currently a status which is 'transition arrangements' and someone can be eligible for this, what is it and what do we do about it?Quote: 'Individuals eligible for transition arrangements have until 1 September 2023 to complete induction within 1 year. Whether an individual is eligible for transition arrangements will also affect whether you need to return information on the ‘induction programme type’ for that individual'. If the individual is eligible for transition arrangements, then the ‘Induction programme type’ will be blank.![Image](https://github.com/user-attachments/assets/6879aa13-92c5-4a68-be9a-9c9fe97a679e)

There a few alerts 
- Currently an alert appears if the ECT has any of the following, surely if they have one of these they can't be claimed right? There are no other actions to take in the system any of the following happen. 
--has been prohibited from teaching 
--may be the subject of a suspension or conditional order imposed by the General Teaching Council (prior to its abolition) that is still current 
--has failed to successfully complete their induction or probation period 
--has been the subject of a decision by the Secretary of State not to impose a prohibition 7 order following a determination by a professional conduct panel of unacceptable professional conduct, conduct that may bring the teaching profession into disrepute or conviction of a relevant offence
--potentially has a restriction imposed by the Disclosure and Barring Service (DBS)
- Alert - If they don't have QTS the record will still show but have a blank field in the QTS date section. If they don't have QTS the teacher cannot be claimed.
- Alert - If the ECT has previously failed induction, they cannot do induction again and therefore can't be claimed.
- Alert - If an early career teacher did their initial teacher training (ITT) through an accredited ITT provider who is also that same AB, the AB cannot claim that teacher.
- Alert - ECTs may be serving their induction at an AB. For example, they may work at a teaching school hub that is also an AB. If this is the case, the AB cannot claim that teacher.
- Alert (naughty list) - if the teacher has any teaching restrictions placed against them, teacher cannot be claimed. 
- Alert - if a teacher has an active alert against their record, currently the data is till stored but it flags an internal warning in case DfE/TRA needed to examine the case in more detail. **Is this still relevant?**  
- Teacher holds exempt, passed, or passed in wales induction statuses. Teacher has already completed, or does not need to complete, induction. They should not therefore be undergoing induction. **Note, there may be cases in CPD where they want someone to undergo the induction training even if they don't need to undergo the 'statutory element' of induction. What do we do there?**
- Alert - If the ECT has previously completed induction, they cannot do induction again and therefore can't be claimed.
- Alert - if the ECT is already claimed by the AB it cannot be claimed again

**Comment by gracecbrennan** [comment]
This has been spilt into different tickets. Will mark as done.
