### ISSUE TITLE
Analyse admin console for AB portal feature scope

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#425]
Decisions so far

- `AB Admin console` should just be part of the `main admin portal`
- [Designs from TRA are in this link ](https://www.figma.com/design/jyjMrGDo6Af79dPXkGwh4t/TRS-Console?node-id=854-9571&t=FGGTeKhrhZGU5l7H-1)

Action points 
- Must liaise with John King on TRA side to have overview of work done from BA/Dev perspective

Summary of analysis requirements
- Objective of the admin console is to help us diagnose data mismatches and errors in induction data. The same code is used for updates from ABs or support so it is not a large piece of coding work to build this console. 
- The data we need on the console is limited (ECT TRN, ECT name, induction status, induction status, AB name, ID) + induction period per ECT. However it's the connections with TRS that need really strong service rules. Some cases to unpack include 
--Update date in admin console and TRS - how do we keep data in synch and clean?
--Only update TRS if I'm updating first induction start date but not second induction date.

**Comment by claire-hughez** [comment]
Writing down insights, messy on a board right now. Meeting with me to go through how we can document this.

**Comment by claire-hughez** [comment]
Will leave a thread for bod squad to leave comments.

**Comment by claire-hughez** [comment]
If anyone else has any insights/research, share it

**Comment by gracecbrennan** [comment]
Kas has made a couple of tables that they have shared with team - going to have a chat with team on this today

**Comment by gracecbrennan** [comment]
This is ongoing

**Comment by kas-madrigal** [comment]
Presenting tables to TRA today and will start doing lofi designs this week to present back to Komal

**Comment by gracecbrennan** [comment]
Got some feedback yesterday and still in progress

**Comment by kas-madrigal** [comment]
https://educationgovuk-my.sharepoint.com/:x:/r/personal/kas_madrigal_education_gov_uk/Documents/Admin%20console%20data%20considerations.xlsx?d=w0bf2a240d8334f328a8013bd88cc81db&csf=1&web=1&e=P56YYV summary of conclusions from data analysis and data points still to be clarified. Good topic of conversation for TRA meeting next monday @emily-prudence-dfe

**Comment by kas-madrigal** [comment]
The flow to edit our 3 main data points from CPD to TRS could be an easy fix from a IxD point but it raises multiple conversations. https://lucid.app/lucidspark/17be7960-2487-4c49-bdb6-15c144f8c2fb/edit?view_items=ubvkxQslHjBx&invitationId=inv_8fa9969b-e457-4912-b015-1ada6a848ff1 

![Image](https://github.com/user-attachments/assets/af0933d4-79b9-400b-8bf1-dd36b00e74cc)


1. The admin console as it stands has well-known and documented pain points for users. Are we setting up even more teams for a difficult experience without addressing? There are quick wins that we could implement from previous research, when, how and within what scope is the question. @claire-hughez 
2. I am blocked on developing further any new UI for the admin console until we agreed upon a) dfe sign in process, b) extensions, c) exemptions, d) active/inactive ABs. Some of these are dependent on the team, some I am waiting for Komal to respond (she is unwell at the moment).

**Comment by kas-madrigal** [comment]
Questions for chat with Pete 

- Who owns admin console code now?
- Filter and sort functionalities, how hard are they to do?
- What do you think of the suggested changes?
- Go over excel sheet with him for admin console - done

**Comment by peteryates** [comment]
> * Who owns admin console code now? No-one reaaaaaally.

This is the situation in ECF1, in ECF2 it belongs to the team ECF2 team.

From an AB portal point of view we mainly have to worry about the data we're capturing in #472.

So, we have:

* Appropriate bodies:
    - `id`
    - `name` (make editable by admins)
    - `dfe_sign_in_organisation_id` (make editable by admins)
    - `local_authority_code` (make editable by admins)
    - `establishment_number` (make editable by admins)
* Teachers
   -  `trn` (probably not editable, we might need to consider merging duplicates further down the line but imo that's post MVP)
   -  `first_name` (not editable - sourced from  TRS)
   - `last_name` (not editable - sourced from TRS)
   - `extension_length_in_terms` (editable)
*  Induction periods
   - `appropriate_body_id` (probably not editable - not sure how a situation might arise where an IP belongs to the wrong AB)
   - `started_on` (editable)
   - `finished_on` (editable)
   - `number_of_terms` (editable)

Some of these things will trigger an update that needs to be sent via the TRS API. For example:

* if the start date of the first induction period changes we need to update the `induction_start_date` in TRS accordingly
* if the finish date of the final (completing) induction period changes we need to update the `induction_completion`date` in TRS accordingly (should we allow this?)

So, in terms of screens I think we'll need:

* a list of appropriate bodies #360 
* a page where we can view a single appropriate body
    - it should show the AB details and have a list of teachers who the AB is currently managing
    - the teacher list should link to the teacher record
* a list of teachers #427 
* a page where we can view a teacher's details (also #427)
   - the view page should have a induction section that lists their induction status, periods, etc
   - each induction period should be viewable and editable

**Comment by gracecbrennan** [comment]
Emily is going to pick up with Kas today to create a better defined ticket

**Comment by gracecbrennan** [comment]
Claire and Grace to pick up with Kas when they are back

**Comment by gracecbrennan** [comment]
Joe and Theo had a catch up on what Theo is covering

**Comment by gracecbrennan** [comment]
Kas is going to pick this one up today

**Comment by gracecbrennan** [comment]
Mostly catching up on Theo's work yesterday. This is going to need to be broken up for next Sprint.

**Comment by gracecbrennan** [comment]
There's a session happening on Monday with Theo and TRA on this .

**Comment by gracecbrennan** [comment]
Session happening today
