### ISSUE TITLE
Create front page for Register early career teachers for schools

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#429]
## Why?
Pete has set it up so that the production environment will show the appropriate body interface as the homepage for the register ECTs domain.

However, in the longer term, we know that this will need to be the schools frontpage, as shown in the screenshot below.

We should replace the 'it works' page in the staging environment to look like the screenshot, so we can more easily test and review changes we make to school registration.

In another ticket #624, Jack sorted out using markdown templates! We should make sure this page works too so we can let the rest of the team make content tweaks. This means we'll have to bother devs less.

## What?

- Add the page for the homepage content - the 'it works' page here, needs to be replaced by this content: https://cpd-ec2-staging-web.test.teacherservices.cloud/
- Switch the template from HTML to markdown (so Claire can edit it :D) 

![Image](https://github.com/user-attachments/assets/bf87619c-e934-427a-9763-0d0a225ea81e)

## Helpful links or other information
[View the prototype for the frontpage here.](https://ecf2-prototy-sprint-8-s-znawg0.herokuapp.com/v2/school/start)

**Comment by TobyRet** [comment]
@claire-hughez @mason-emily 
I think this has been largely done for now? (DfE signin is not active yet though)
https://cpd-ec2-staging-web.test.teacherservices.cloud/schools/what-you-will-need

**Comment by claire-hughez** [comment]
Is it built as a markdown template? If not, it would be great to quickly edit it for that to be the case :)

**Comment by gracecbrennan** [comment]
There is a problem with the AB link - Toby is going to go back and try with different persona.

**Comment by claire-hughez** [comment]
reviewed from me

**Comment by gracecbrennan** [comment]
Toby needs to catch-up with Pete on this one

**Comment by gracecbrennan** [comment]
Emily is going to direct people towards existing spreadsheet on this

**Comment by gracecbrennan** [comment]
There are some links we need to change on this page. lorenzo has left some comments for @peteryates to check.
