### ISSUE TITLE
Claim an ECT - Alerts & Prohibitions

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#431]
![Image](https://github.com/user-attachments/assets/904bd390-16fd-40c9-b482-23bb27bf54cf)

Unhappy paths to cover include:
Right now there is a visual alert if the teacher has been naughty. When accessing the teacher’s record on the AB portal, the status box may be highlighted in red. This indicates that the teacher has one or more of the following:
- has been prohibited from teaching
- has a restriction imposed by the Disclosure and Barring Service (DBS)
- may be the subject of a suspension or conditional order imposed by the General Teaching Council (prior to its abolition) that is still current
- has failed to successfully complete their induction or probation period has been the subject of a decision by the Secretary of State not to impose a prohibition order following a determination by a professional conduct panel of 7 unacceptable professional conduct, conduct that may bring the teaching profession into disrepute or conviction of a relevant offence.

**Comment by kas-madrigal** [comment]
We are not showing ITT data in the end are we @edujackedu ?

**Comment by peteryates** [comment]
We recieve this data back when we look someone up using the TRS API:

```json
{
  "alerts": [
    {
      "alertId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "alertType": {
        "alertTypeId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "alertCategory": {
          "alertCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "name": "string"
        },
        "name": "string"
      },
      "details": "string",
      "startDate": "2024-10-16",
      "endDate": "2024-10-16"
    }
  ],
  "induction": {
    "startDate": "2024-10-16",
    "endDate": "2024-10-16",
    "status": "Exempt",
    "statusDescription": "string",
    "certificateUrl": "string"
  },
  "initialTeacherTraining": [
    {
      "provider": {
        "name": "string",
        "ukprn": "string"
      },
      "qualification": {
        "name": "string"
      },
      "startDate": {
        "hasValue": true,
        "value": "2024-10-16"
      },
      "endDate": {
        "hasValue": true,
        "value": "2024-10-16"
      },
      "programmeType": {
        "hasValue": true,
        "value": "Apprenticeship"
      },
      "programmeTypeDescription": "string",
      "result": {
        "hasValue": true,
        "value": "Pass"
      },
      "ageRange": {
        "description": "string"
      },
      "subjects": [
        {
          "code": "string",
          "name": "string"
        }
      ]
    }
  ],
  "trn": "string",
  "firstName": "string",
  "middleName": "string",
  "lastName": "string",
  "dateOfBirth": "2024-10-16",
  "nationalInsuranceNumber": "string",
  "pendingNameChange": true,
  "pendingDateOfBirthChange": true,
  "emailAddress": "string",
  "qts": {
    "awarded": "2024-10-16",
    "certificateUrl": "string",
    "statusDescription": "string"
  },
  "eyts": {
    "awarded": "2024-10-16",
    "certificateUrl": "string",
    "statusDescription": "string"
  },
  "npqQualifications": [
    {
      "type": {
        "code": "NPQEL",
        "name": "string"
      },
      "awarded": "2024-10-16",
      "certificateUrl": "string"
    }
  ],
  "mandatoryQualifications": [
    {
      "awarded": "2024-10-16",
      "specialism": "string"
    }
  ],
  "higherEducationQualifications": [
    {
      "subjects": [
        {
          "code": "string",
          "name": "string"
        }
      ],
      "name": "string",
      "awarded": "2024-10-16"
    }
  ],
  "previousNames": [
    {
      "firstName": "string",
      "middleName": "string",
      "lastName": "string"
    }
  ],
  "allowIdSignInWithProhibitions": true
}
```

So, given the following sets of people we want to block:

> * has been prohibited from teaching
> * has a restriction imposed by the Disclosure and Barring Service (DBS) may be the subject of a suspension or conditional order imposed by the General Teaching Council (prior to its abolition) that is still current
> * has failed to successfully complete their induction or probation period has been the subject of a decision by the Secretary of State not to impose a prohibition order following a determination by a professional conduct panel of 7 unacceptable professional conduct, conduct that may bring the teaching profession into disrepute or conviction of a relevant offence.

I'm not sure we can identify them given the data above, I think we need to look into that so we can work out how the logic might look at our end.

**Comment by kas-madrigal** [comment]
@peteryates what is the next step from this? should we have a call? I have in my backlog to give a list of requirements for the API to test against and this sounds like a good example, should we put this in?

**Comment by peteryates** [comment]
Here's the full list of alerts:

| Alert Type ID | Alert Type | Alert Category | DQT Sanction Code | Prohibition Level | Migration Status |
| --- | --- | --- | --- | --- | --- |
| 241eeb78-fac7-4c77-8059-c12e93dc2fae | Section 128 barring direction | Section 128 (SoS) | T7 | Leadership Positions | Active |
| 33e00e46-6513-4136-adfd-1352cf34d8ec | No Sanction  -  breach of condition(s) | GTC Decision | A22 | No | Archived |
| 0740f9eb-ece3-4394-a230-453da224d337 | No Sanction  -  conviction for a relevant offence | GTC Decision | A16 | No | Archived |
| b6c8d8f1-723e-49a5-9551-25805e3e29b9 | No Sanction  -  serious professional incompetence | GTC Decision | A12 | No | Archived |
| 78f88de2-9ec1-41b8-948a-33bdff223206 | No Sanction  -  unacceptable professional conduct | GTC Decision | A11 | No | Archived |
| fcff87d6-88f5-4fc5-ac81-5350b4fdd9e1 | Reprimand  -  conviction of a relevant offence | GTC Decision | A17 | No | Archived |
| 3f7de5fd-05a8-404f-a97c-428f54e81322 | Reprimand  -  serious professional incompetence | GTC Decision | A8 | No | Archived |
| 0ae8d4b6-ec9b-47ca-9338-6dae9192afe5 | Reprimand  -  unacceptable professional conduct | GTC Decision | A4 | No | Archived |
| 7924fe90-483c-49f8-84fc-674feddba848 | Secretary of State decision- no prohibition | TRA Decision (SoS) | T6 | No | Active |
| 9fafaa80-f9f8-44a0-b7b3-cffedcbe0298 | Failed induction | Failed induction | C2 | Teaching | Active |
| 651e1f56-3135-4961-bd7e-3f7b2c75cb04 | Prohibited by the Secretary of State  -  failed probation | Failed induction | C1 | Teaching | Archived |
| 5ea8bb68-4774-4ad8-b635-213a0cdda4c3 | Restricted by the Secretary of State  -  failed probation  -  permitted to carry out specified work for a period equal in length to a statutory induction period only | Failed induction | C3 | Teaching | Archived |
| 552ee226-a3a9-4dc3-8d04-0b7e4f641b51 | For internal information only - historic GTC finding of unsuitable for registration | GTC Decision | A15 | No | Archived |
| ae3e385d-03f8-4f12-9ce2-006afe827d23 | FOR INTERNAL INFORMATION ONLY - see alert details | Flag | T9 | No | Active |
| 40794ea8-eda2-40a8-a26a-5f447aae6c99 | A possible matching record was found. Please contact the DBS before employing this person | Restricted/DBS | G1 | Teaching | Active |
| eab8b66d-68d0-4cb9-8e4d-bbd245648fb6 | Barring by the Secretary of State | Prohibition from teaching | B1 | Teaching | Archived |
| 2c496e3f-00d3-4f0d-81f3-21458fe707b3 | Formerly barred by the Independent Safeguarding Authority | Prohibition from teaching | G2 | Teaching | Archived |
| 993daa42-96cb-4621-bd9e-d4b195076bbe | Formerly on List 99 | Prohibition from teaching | B6 | Teaching | Archived |
| a414283f-7d5b-4587-83bf-f6da8c05b8d5 | Interim prohibition by the Secretary of State | Prohibition from teaching | T2 | Teaching | Active |
| 8ef92c14-4b1f-4530-9189-779ad9f3cefd | Prohibited by an Independent Schools Tribunal or Secretary of State | Prohibition from teaching | B3 | Teaching | Archived |
| 50feafbc-5124-4189-b06c-6463c7ebb8a8 | Prohibition by the Secretary of State  -  deregistered by GTC Scotland | Prohibition from teaching | T3 | Teaching | Active |
| 5aa21b8f-2069-43c9-8afd-05b34b02505f | Prohibition by the Secretary of State  -  refer to GTC Northern Ireland | Prohibition from teaching | T5 | Teaching | Active |
| a5bd4352-2cec-4417-87a1-4b6b79d033c2 | Prohibition by the Secretary of State  -  refer to the Education Workforce Council, Wales | Prohibition from teaching | T4 | Teaching | Active |
| ed0cd700-3fb2-4db0-9403-ba57126090ed | Prohibition by the Secretary of State - misconduct | Prohibition from teaching | T1 | Teaching | Active |
| 72e48b6a-e781-4bf3-910b-91f2d28f2eaa | Prohibition Order  -  conviction of a relevant offence  -  eligible to reapply after specified time | GTC Prohibition from teaching | A21B | Teaching | Archived |
| 950d3eed-bef5-448a-b0f0-bf9c54f2103b | Prohibition Order  -  conviction of a relevant offence  -  ineligible to reapply | GTC Prohibition from teaching | A21A | Teaching | Archived |
| cac68337-3f95-4475-97cf-1381e6b74700 | Prohibition Order  -  serious professional incompetence  -  Eligible to reapply after specified time | GTC Prohibition from teaching | A5B | Teaching | Archived |
| c02bdc3a-7a19-4034-aa23-3a23c54e1d34 | Prohibition Order  -  serious professional incompetence  -  Ineligible to reapply | GTC Prohibition from teaching | A5A | Teaching | Archived |
| e3658a61-bee2-4df1-9a26-e010681ee310 | Prohibition Order  -  unacceptable professional conduct  -  Eligible to reapply after specified time | GTC Prohibition from teaching | A1B | Teaching | Archived |
| fa6bd220-61b0-41fc-9066-421b3b9d7885 | Prohibition Order  -  unacceptable professional conduct  -  Ineligible to reapply | GTC Prohibition from teaching | A1A | Teaching | Archived |
| a6fc9f2e-8923-4163-978e-93bd901d146f | Conditional Registration Order  -  conviction of a relevant offence | GTC Decision | A18 | Restrict | Archived |
| 1ebd1620-293d-4169-ba78-0b41a6413ad9 | Conditional Registration Order  -  serious professional incompetence | GTC Decision | A7 | Restrict | Archived |
| 3499860a-a0fb-43e3-878e-c226d14150b0 | Conditional Registration Order  -  unacceptable professional conduct | GTC Decision | A3 | Restrict | Archived |
| 38db7946-2dbf-408e-bc48-1625829e7dfe | Restricted by the Secretary of State  -  Not Permitted to work as teacher | SoS Restriction | B2B | Restrict | Archived |
| 18e04dcb-fb86-4b05-8d5d-ff9c5da738dd | Restricted by the Secretary of State  -  Permitted to work as teacher | SoS Restriction | B2A | Restrict | Archived |
| d372fcfa-1c4a-4fed-84c8-4c7885575681 | Suspension order  -  conviction of a relevant offence  -  with conditions | GTC Restriction | A20 | Restrict | Archived |
| af65c236-47a6-427b-8e4b-930de6d256f0 | Suspension order  -  conviction of a relevant offence  -  without conditions | GTC Restriction | A19 | Restrict | Archived |
| 50508749-7a6b-4175-8538-9a1e55692efd | Suspension order  -  serious professional incompetence  -  with conditions | GTC Restriction | A14 | Restrict | Archived |
| a6f51ccc-a19c-4dc2-ba80-ffb7a95ff2ee | Suspension order  -  serious professional incompetence  -  without conditions | GTC Restriction | A6 | Restrict | Archived |
| 1a2b06ae-7e9f-4761-b95d-397ca5da4b13 | Suspension order  -  unacceptable professional conduct  -  with conditions | GTC Restriction | A13 | Restrict | Archived |
| 872d7700-aa6f-435e-b5f9-821fb087962a | Suspension order  -  unacceptable professional conduct  -  without conditions | GTC Restriction | A2 | Restrict | Archived |
| 17b4fe26-7468-4702-92e5-785b861cf0fa | Suspension order  -  with conditions  -  (arising from breach of previous condition(s)) | GTC Restriction | A24 | Restrict | Archived |
| 3c5fc83b-10e1-4a15-83e6-794fce3e0b45 | Suspension order  -  without conditions  -  (arising from breach of previous condition(s)) | GTC Restriction | A23 | Restrict | Archived |
| 2ca98658-1d5b-49d5-b05f-cc08c8b8502c | Teacher sanctioned in other EEA member state | EEA Decision | T8 | Notify | Active |
| 12435c00-88cb-406b-b2b8-7400c1ced7b8 | FOR INTERNAL USER ONLY – known duplicate record | Flag | T10 | No | Active |
