### ISSUE TITLE
Add AB release ECT flow exit/unhappy paths

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#432]
![Image](https://github.com/user-attachments/assets/e0bd0648-f418-45cc-af23-6e96a3df458a)
![Image](https://github.com/user-attachments/assets/5cf30bf1-de8f-45af-8cc6-07d82fe2fae9)
![Image](https://github.com/user-attachments/assets/1784bf78-98b3-433f-bc47-55ff5d3f7a61)

**System exists for release, outcome and change programme type policies**
- Although under the statutory guidance it states induction cannot be backdated, it is possible to amend an incorrect start or end date of induction.
- The system doesn’t permit same day disowning and claiming,

**Policy exists for release, outcome and change programme type policies**
- Currently there is an auto-populated field for previously inputted induction start date. **Good for a reminder? They can also edit it but that is not a feature that should be on this step**
- Induction end date cannot happen before induction start date.
- An ECT has to do one school term for that induction time to count. If they leave a post before the end of their first school term (e.g. Sept-Dec) that term will not be counted on their record and they must restart term 1. If they complete that term they will count one term on their record and from there onwards we can allow to track half terms. The same counts for part-time ECTs - they need to go through their first term in order to have it count at all, but when they do we can track that time spent as 0.5 terms. SO -  If the time between the start date and end date of the induction period is less than 2 calendar months, then the number of terms recorded against the period must be zero. Else, any number can be recorded against the induction period, including zero and non-integer values.
- If the time between the start date and end date of the induction period is less than 2 months, and the total number of terms recorded against previous induction periods is less than one then an outcome cannot be recorded for the induction.
- TRA needs to be alerted if there is an induction that needs to be appealed. 

**System exist for outcome only flow**
- In the as-is when a teacher completes their induction they are removed from the list of teachers the AB can see. It would be helpful if we could NOT do this, or keep them for X amount of time in case the AB needs to track them upon queries from the LP or even DfE

**Comment by gracecbrennan** [comment]
This is a parent ticket for other tickets that have been completed - this is no longer needed.
