### ISSUE TITLE
Start to ideate on front pages for the new services, for schools, appropriate bodies and internal users 🎨 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#45]
## Why?
We want to have a vague idea of the structure of our services, what they could be named, and to represent them together.

All of this would need to be tested in the future.

## What?
- start a Lucid frame with a set of blank gov guidance / homepage templates (per user group)
-  start to just collate thoughts and ideas for what we'd want to include etc

**Comment by gracecbrennan** [comment]
Jas has started high level ideation on Lucid - lots will be impact through content. 

Started with school users.

**Comment by JSJohal** [comment]
Started work on this [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=LIxXdDFldK~W&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b), high level ideas currently with some lo-fi wireframes.

**Comment by JSJohal** [comment]
### Screenshots of high level ideas so far

#### Schools user group

Basic guidance page - I think we need to think about catering it specifically to what schools need to do - being a bit more direct than previous.
![Image](https://github.com/user-attachments/assets/03236ed0-45dc-4d27-acc0-7f3e641c98cd)

Task-list pattern - we could try something like this for registration periods, to add a bit more structure and a linear journey to be completed, could add some clarity about each step that needs doing and a clear distinction between what's done and what isn't.
![Image](https://github.com/user-attachments/assets/f1c683ad-8465-4d67-8551-f9da23fc0db3)

Something to consider for returning users with previous programmes - adding a way to play back all information about previous year programme and confirming that to be the case for the next year. I think in some cases that wouldn't work (i.e. when partnerships no longer exist). At the moment, we do something like this in the existing service but there's a few questions asked beforehand and only covers some of the data.
![Image](https://github.com/user-attachments/assets/b8ba1178-cd82-442a-a655-989549013aa3)

Screenshots of the 'add multiple things' patterns which are used across gov - we could do something similar if we wanted to find a way to add multiple ECTs to the same programme details. This could do be a way to reduce going through the same add ECT journey multiple times as exists now.
![Image](https://github.com/user-attachments/assets/0db01354-0431-417e-b76e-ffe5924d44be)

**Comment by gracecbrennan** [comment]
Awo is picking up AB stuff

**Comment by aabdi18** [comment]
Have looked at the option of viewing an ABs ECTs through Schools and 'tasks outstanding' (if there are any errors/new updates they need to view/approve), here they can also add a new school and add new ECTs within that tab

![Image](https://github.com/user-attachments/assets/09b8eb47-27d1-42e0-ac4a-b1732541458f)


![Image](https://github.com/user-attachments/assets/bacf1efb-0414-4276-bb50-e8faaf953b96)

**Comment by gracecbrennan** [comment]
@aabdi18 to add first page into designs and we will look to show and share - maybe on Monday?

**Comment by mason-emily** [comment]
To demo in Monday stand up
