### ISSUE TITLE
Allow for PRs with code that impacts what users see to be reviewed by non-devs

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#452]
## Why?
At the moment, if a PR is created, the 'deploy' label has to be added to it for a non-dev to be able to see the changes and review the work that is being done that users will see.

However, sometimes this gets forgotten or the PR gets merged before the deploy label can be added.

Also, sometimes we're adding the deploy label even before it's merged and it's not working. This is going to make it much harder to product review the Add an ECT journey when we start building it imminently.

When the deploy label is added, it also just takes you the generic landing page for the review environment, and nothing relevant or helpful to get you to the code that has actually changed. This means you need to work out how to change the URL to get there, which isn't necessarily straight-forward!

So there's 3 problems:
1) the existing deploy label that posts a link to the review environment for us to review doesn't always work, even before a PR is merged
2) the link that is given isn't that helpful at the moment, and just links to a generic environment page rather than the work in the PR
3) the deploy label has to be added manually and can be forgotten - it would be handy if it could be automated

## What?
- Make it so that a non-dev can review a ticket that changes what users see easily - this could be just writing some clear guidance on how to do this
- Make it so the deploy label works when added, or somehow happens automatically when code is added/changed for things that users will see
- If we can, make it so that it more clearly links to whatever is actually being updated or changed in the PR

**Comment by TobyRet** [comment]
@claire-hughez 

@peteryates and I discussed this at the end of Friday.

- Peter reports that review app deploy is now fixed (when the 'deploy' label is added the review app is created)
- A further improvement could be to 'automatically' deploy the review app when changes to the source code occurs (specifically the app folder). If we do this then we remove the problem of 'forgetting to add the label'. 
- Automatically providing a review app link that take you directly to files (page) that was changed is going to be very tricky and may not be possible. Once way to make it easier for reviewers to know where to go could be to agree a PR template which could act as a checklist for the author to consider when creating their PR description ... E.g 

```
### Goal of the PR


### Link to ticket


### Describe the changes


### Review app links (optional)


### Screenshots (optional)

```
