### ISSUE TITLE
Consider and design validation for 'Add an ECT' flow

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#457]
**Objective:**
Design and implement a validation system for the service to ensure accurate and complete data submission before processing. Specifically, we need to design validation for the 'Add an ECT' flow.

**Things to think about**

Input Validation:

- Ensure all required fields are filled.
- Validate data types (e.g., email format, numeric values).
- Verify field-specific rules (e.g., length limits, format patterns).

TRN Validation:

- Implement TRN check against database or external service.
- Provide error feedback if TRN is missing or incorrect.
- Include manual override option for unvalidated TRNs with warnings.

Real-Time Content Feedback:

- Display errors or confirmation messages as users input data.
- Ensure messages are clear and actionable (e.g., "Please enter a valid email address").

UI/UX Considerations:

- Use clear labeling and validation hints (e.g., red error messages, inline warnings).
- Ensure accessibility for error messaging (e.g., ARIA roles, readable contrast).

Error Handling:

- Create a fallback system for backend validation if the client-side fails.
- Display an appropriate error message for failed submissions.

**Outcome:**

Prototype designs?

**Comment by claire-hughez** [comment]
Need to think about induction start date here.

**Comment by claire-hughez** [comment]
I think from 1373 here will be helpful to help inform this, lists the messages for validation errors in Register trainee teachers: https://github.com/DFE-Digital/register-trainee-teachers/blob/9b2f81cf73efc118e2238b95eeb04937a085915d/config/locales/en.yml#L1587 @mason-emily

**Comment by gracecbrennan** [comment]
Emily still needs to follow up on a few questions

**Comment by gracecbrennan** [comment]
@mason-emily to update ticket

**Comment by mason-emily** [comment]
@Dom-Collins @JSJohal @claire-hughez added to the [spreadsheet](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=GRrh9p) - if we're happy with the rules could you add the error message content @Dom-Collins ?

**Comment by mason-emily** [comment]
Review with Tony scheduled for tomorrow

**Comment by gracecbrennan** [comment]
Emily and Tony reviewed - link to spreadsheet included
