### ISSUE TITLE
Design for when we need to ask a school to give an ECT or mentor's national insurance number or cannot find their record in the TRS

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#459]
## Why?
If we cannot find an ECT or mentor from their TRN or DOB, we need to ask the school user for the ECT or mentor's national insurance number.

If we still can't find it after that, we need to direct them to support.

## What?
- Design the page(s) for what the user will see if the DQT check initially fails and we ask for national insurance number
- Design the page for if after giving the national insurance number we still can't find the record

## Helpful links or other information
![Image](https://github.com/user-attachments/assets/b22b723f-c808-4c1f-81e1-878ce6faaf62)
![Image](https://github.com/user-attachments/assets/645d109b-f0ae-48f1-97a2-09045b020785)

**Comment by claire-hughez** [comment]
@JSJohal do we already have this? If so, would be good to add to this ticket and put to review so we can check it before building it.

**Comment by JSJohal** [comment]
@claire-hughez We do!
This is the NINO page if we've not been able to find on TRN / DOB. [Prototype link](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/nino)
![image](https://github.com/user-attachments/assets/99edbe77-debc-4680-adf0-01d425cf4210)

If still not found, then we have this page. [Prototype link](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/not-found)
![image](https://github.com/user-attachments/assets/b92c28fc-e1b2-405b-87f0-d1cb96481ea9)

**Comment by claire-hughez** [comment]
Amazing! Put to review - would be good for maybe @mason-emily and @tonyheadford to have a look. 

On the prototype I'm not sure how to click through to that 2nd screenshot, as it just takes me to if it was successful. Where does the reviewing their teacher record link go to please? :)

**Comment by JSJohal** [comment]
@claire-hughez I've set it up now so that if from this [page in the prototype](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/find-ect) you enter a TRN as `9999999`, it then redirects to the NINO page. If you enter a NINO starting with `Z`, then it will redirect to the not found page.

The not found page links to [check a teacher record](https://check-a-teachers-record.education.gov.uk/check-records/sign-in), but I wonder if it should be access your teaching qualifications?

**Comment by gracecbrennan** [comment]
@claire-hughez / @mason-emily - can this be written up as a dev ticket now please?
