### ISSUE TITLE
Add content for when a mentor does not have a TRN and they're being registered

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#461]
## Why?
A mentor in our service needs a TRN to be registered.

However, not all mentors are qualified teachers. They may need to get a TRN for the purpose of being registered on our service.

## What?
- Design content to be used when adding a mentor to make clear what to do if the mentor does not have a TRN

## Helpful links or other information
This is how they handle it in ECF1 currently:
![Image](https://github.com/user-attachments/assets/ab66f956-d01c-4527-a792-a59c88822d20)
![Image](https://github.com/user-attachments/assets/ca13503c-2a81-428b-b806-97c4778c8d79)

**Comment by gracecbrennan** [comment]
Jas to pick this one up today

**Comment by JSJohal** [comment]
Added link and content as per ECF1, but will need reviewing by @robthompson16 to see if we want to keep it the same or possibly change.

Screenshots below but can also be seen in the prototype [here](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/school/mentor/find-mentor) and [here](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-mentor/no-trn) - password: review
 
![Image](https://github.com/user-attachments/assets/96e5b94a-8120-4153-a0fe-b41dad70df64)
![Image](https://github.com/user-attachments/assets/408bd4e3-ce56-4ff6-b98c-61839577934d)

**Comment by gracecbrennan** [comment]
Rob to review content that's come across from ECF 1

**Comment by robthompson16** [comment]
@JSJohal I've completed the content review here: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

**Comment by claire-hughez** [comment]
looks great

**Comment by gracecbrennan** [comment]
@mason-emily to add to unhappy path map to remember to dev ticket this up
