### ISSUE TITLE
Add to the content strategy how we want to refer to acronyms and registration and review content so far to make it sure it matches

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#467]
## Why?
In the prototype currently, we use acronyms a bit inconsistently. We should decide how we want to define acronyms/abbreviations and if we need to use ECTs or should just use early career teachers. We should write this in the content strategy so we don't forget.

We should also consider how we use the terms 'adding an ECT' or 'registration', to make sure we're being consistent about what they mean.

We should also think about how we use 'your', particularly in the case of 'your default choices' when it's actually the choices for the whole school, or 'your' for mentors when the user isn't being mentored.

We should also think about explaining to users what we're doing with this information. For example, lead providers, delivery partners, appropriate bodies. We might want to tell schools this will tell the lead provider they're working with them.

## What?
- Review the content generally and see if there's anything else we should specify in the content strategy or a style guide
-  Add to content strategy how to consider all of these: using the same terms for registration, using 'your' and using acronyms
- Make sure they're correct in prod and the prototype

We'll add to Dom's content strategy originally, then think of making it public.

**Comment by gracecbrennan** [comment]
Has just started and ongoing

**Comment by robthompson16** [comment]
Have created a board here: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

Reviewing content and making a note of terms and phrases for us to agree on how we use

**Comment by gracecbrennan** [comment]
Going to put a session in to run-through with the team

**Comment by robthompson16** [comment]
I've updated Dom's content strategy document here: https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/ESJ3am3Xhp5NpRPTgolZQjIB9b3Sl2wukXbzVQ5vLs3Bww?e=nbyVCy
