### ISSUE TITLE
View list of ECTs added in your school

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#468]
## Description
This story delivers a placeholder page that will provide:
- A starting point for the 'Add ECT' journey
- A way to view the ECTs added in a school, so that we can see when an ECT has successfully been added

This page can initially be based on the design of the [AB portal landing page](#395), and will later be iterated following further design and testing.

## User story

**As** a school user
**I need** to view a list of ECTs in my school
**So that** I can see which ECTs have already been added and add more ECTs as needed

## Prototype, screenshots & content
[Link to prototype](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/home/ects)

Example 'View ECTs' page:

![Image](https://github.com/user-attachments/assets/b5930e62-d521-4750-9e72-38ad90f16f17)

Content should be as per the screenshot above.

## Acceptance criteria

- [ ] ~~1. There is a persona linked to a school set up to mimic being signed in (DfE Sign In to be built later).~~
- [x] 2. Caption above H1 should contain the name of the school.
- [x] 3. There is a button/link to start the 'Add an ECT' journey to add an ECT for that school. This button will navigate the user to the ['What you'll need' to register an ECT page](#430).
- [x] 4. There is a list of ECTs that have been added for that school. We need some hard coded / dummy data for a couple of ECTs here for now, and when we've built the 'Add ECT' journey the ECTs that are successfully added will show in this list.
- [ ] ~~5. There is a way to view the details for ECTs that have been added, including their name, TRN, date of birth, and email address.~~

## Technical notes
We need to create a persona linked to a school to mimic being signed in (DfE Sign In to be built later).

Note, whilst this page can be based initially on the AB portal landing page, it is just a placeholder for now and should be built as basic as possible since the design may change significantly.

**Comment by TobyRet** [comment]
@tonyheadford @peteryates 

Should E2E testing be set up as part of this ticket? Or is it too soon ...

**Comment by peteryates** [comment]
I don't think there's any harm in it _but_ as everything's likely to change it can be light touch for now.

We already have `ECTAtSchoolPeriod` records in the seed data so there's something to test with.

I think it makes sense to add pagination to this page while you're implementing this as we'll have to at some point anyway. See [the AB list for inspiration](https://github.com/DFE-Digital/register-early-career-teachers/blob/36965d83ab5bf4e1440825c86a344f7723128ef4/app/controllers/admin/appropriate_bodies_controller.rb#L3).

**Comment by claire-hughez** [comment]
Will raise the PR to get feedback from devs of what is going on underneath the hood.

**Comment by gracecbrennan** [comment]
This is going back to in progress following review

**Comment by TobyRet** [comment]
@claire-hughez @mason-emily 

Regarding the above acceptance criteria ...

1. I've currently hardcoded the school id - this means, no matter what persona you log in as you will see the same ECTs and Mentors for that school. Apologies an over site on my part. Let me know if this is acceptable or if you prefer the school linked to the persona as originally intended

5. Although ECTs and mentors are listed, the links are not currently active - I would have thought that viewing individual ECTs and Mentors would be out of scope for this ticket? If you like I can pick this up next ...

**Comment by mason-emily** [comment]
This looks great to me! https://cpd-ec2-review-500-web.test.teacherservices.cloud/schools/home/ects

I've crossed through AC 1 & 5 as they're not covered in this ticket now and will be picked up separately.
