### ISSUE TITLE
Appropriate body data import

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#472]
We'll be importing data from the current AB portal at some point in January.

We expect to import the following data in CSV format.

> [!NOTE]
> I've recorded the IDs as `integer` but if they're `uuid` in the source data that's fine too.

> [!CAUTION]
> These are not final and need discussion

## Appropriate bodies

| Column | Type | Reason |
| --------- | ----- | ------|
| `id` | `integer` | We won't store this but use it to cross-reference _induction periods_ |
| `name` | `string` | |
| `dfe_sign_in_organisation_id` | `uuid` | We'll need this so we can link incoming users to appropriate bodies #453 |
| `local_authority_code` | `integer` | Used for bulk upload (probably - to confirm) |
| `establishment_number` | `integer` | Used for bulk upload (probably - to confirm) |

## Teachers

| Column | Type | Reason |
| ------- | ----- | ------|
|`trn` | `string` | Even though it is called number, some have leading zeroes so we need to save them as a string |
| `first_name` | `string` |
| `last_name` | `string` |
| `extension_length` | `integer` | |
| `extension_length_unit` | `string` | We'd expect days, months, weeks, terms here, but they might all be recorded in terms. If they're all terms we can omit this. |

## Induction periods

| Column | Type | Reason |
| ------- | ----- | ------|
| `appropriate_body_id` | `integer` | used to cross reference appropriate bodies |
| `trn` | `string` | used to cross reference teachers |
| `started_on` | `date` | |
| `finished_on` | `date` | |
| `induction_programme_choice` | `string` | We're expecting `fip`, `cip` and `diy` here? |
| `number_of_terms` | `integer` | |

**Comment by emily-prudence-dfe** [comment]
This looks good - just to say we'll need to import **extensions** data at some point too, which isn't included here. The good news is that extensions data is just two fields, linked to a person, and currently stored in the `Induction` table in DQT.

| Column | Type | Reason |
| --------- | ----- | ------|
| `extension_length` | `integer` | |
| `extension_length_unit` | `string` | We'd expect days, months, weeks, terms here, but they might all be recorded in terms |

Aware we've not designed this in our new data model so the omission makes sense, but we'll need to go back to this.

**Comment by peteryates** [comment]
Following on from this @gunndabad confirmed:

* nearly all extensions have the unit `terms`
* there are approximately 200 that don't, the others are:
   * days
   * weeks
   * months
   * years

Following on from a chat with the team we think it's worth looking at converting the other units to terms for consistency is a good idea. If the records with non-term units are history we might not even need to import them.

**Comment by peteryates** [comment]
Oops I forgot to add `trn` to induction periods, I've amended the issue above 🤦🏽‍♂️

**Comment by gracecbrennan** [comment]
Still in progress

**Comment by gracecbrennan** [comment]
Made good progress on this yesterday

**Comment by gracecbrennan** [comment]
Should be good to resume today

**Comment by gracecbrennan** [comment]
Working on the induction periods for ECTs that overlap - this might take a bit longer

**Comment by gracecbrennan** [comment]
Pete made progress on this last night. @peteryates what's left for this to be closed?

**Comment by gracecbrennan** [comment]
This still needs to be tested with production data

**Comment by claire-hughez** [comment]
Pete hopefully getting back into this today

**Comment by claire-hughez** [comment]
Making more progress, took Tony through it. Some tricky data bits to work out. Need to test it against real prod data.
