### ISSUE TITLE
Round 2 UR with School Induction Tutors: Registering an ECT iteration and add a mentor

### ISSUE THREAD

**Issue by rosalie-education** [DFE-Digital/register-early-career-teachers#480]
> ### **Why?**

Since the [first round of user research with School Induction Teachers (SITs),](https://github.com.mcas.ms/DFE-Digital/register-early-career-teachers/issues/112?McasTsid=11760&McasCtx=4) we have iterated the 'register an ECT' portion of the journey, and added the 'add a mentor' flow to the prototype. We need to test the new journey with real users of the service, to ensure that it meets their needs, and to understand and resolve any usability issues before it goes to build. 
_[More detail on research aims/questions to be added once research plan developed]_

> ### **What?**

- [x] Discuss and agree research aims/objectives and priority areas for interrogation for round 2 
- [x] Draft research plan and obtain feedback from team 
- [x] Recruit participants via e-mail & obtain prior informed consent
- [x] Schedule sessions for 23rd - 25th October 
- [x] Draft discussion guide and obtain feedback from team 
- [x] Conduct research sessions 
- [x] Analyse data arising out of the research sessions 
- [x] Produce research outputs 
- [x] Mini playback / Insights-to-action session 
- [ ] Team-wide research playback  

> ### When?

- w/c 14 October - recruitment, scheduling, obtaining prior informed consent, crafting discussion guide & obtaining feedback from team;
- w/c 23 October - Monday/Tuesday Jas will be back from leave and can make any final tweaks to the journey that come out of discussions previous week, research sessions to take place on 23rd, 24th & 25th October
- w/c 28 October - research sessions continue
- w/c 4 Nov  mini playback beginning of the week, full playback end of week (insights-to-action TBC)

> ### **Helpful links or other information**

[User research board](https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=a~w3oybAMSbU&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e)

[Sign up sheet](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Test%20and%20prep/User%20Research/Note%20Taker%20Sign%20Up.xlsx?d=w492d489fd5f24c54b3f134e7ee9042db&csf=1&web=1&e=CRiAlO&nav=MTVfe0EwNTBDQjA0LTA0NzYtNDgyOC05M0U4LUY5QzYxRkNFNzQ3Qn0)

Discussion guide: [here](https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7BE5CA7A0E-AEA2-4CA6-BD78-EEE7F4C99AD5%7D&file=171024%20Discussion%20Guide%20Round%202%20SITs%20ECF2%20User%20Research%20-%20testing%20ECT%20iteration%20and%20add%20a%20mentor%20%20DRAFT%20ONE.docx&action=default&mobileredirect=true)

Visual discussion guide on Lucid: [here](https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=e9Wj9RfwPiq~&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e)

**Comment by claire-hughez** [comment]
Got an account with Meisterworks for financial incentives, amended recruitment materials and got a list of emails to send out for first batch of recruitment. Catch up later this afternoon.

**Comment by rosalie-education** [comment]
First batch of recruitment e-mails sent out today. 1 positive response so far to schedule in. Will wait until tomorrow lunch time before sending next batch of invites.

**Comment by kerry-b-dfe** [comment]
Research plan board: https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=WM_hOrak.HYa&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e

Everyone is welcome to add questions

**Comment by gracecbrennan** [comment]
Rosie will make a start on discussion guide today

**Comment by rosalie-education** [comment]
Started DG ([here](https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/doc2.aspx?sourcedoc=%7Be5ca7a0e-aea2-4ca6-bd78-eee7f4c99ad5%7D&action=edit&wdPid=29a19780)) on Friday - to be continued today. Despite initial interest, only 2 participants have confirmed availability for the interview timeslots on 23rd/24th, so will book them in today and send another batch of recruitment e-mails to fill the remaining slots.

**Comment by gracecbrennan** [comment]
Rosie will be going out with another round of recruitment emails.

**Comment by gracecbrennan** [comment]
Discussion guide out today for team review.

Decision to extend the number of days for interviews (finished by next Thursday)

**Comment by rosalie-education** [comment]
Discussion guide: [here](https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7BE5CA7A0E-AEA2-4CA6-BD78-EEE7F4C99AD5%7D&file=171024%20Discussion%20Guide%20Round%202%20SITs%20ECF2%20User%20Research%20-%20testing%20ECT%20iteration%20and%20add%20a%20mentor%20%20DRAFT%20ONE.docx&action=default&mobileredirect=true)
Visual discussion guide on Lucid: [here ](https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=e9Wj9RfwPiq~&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e)
First two sessions complete. Recruitment for next week ongoing. 
Passed on details of p1 to MW for incentive processing. Waiting for consent for p2 to pass on their details

**Comment by claire-hughez** [comment]
1 other session booked in next week. Rosie will send another batch of emails today.

Analysing as they go, so ready for Thursday the 7th playback.

**Comment by gracecbrennan** [comment]
Final session is tomorrow. 

Rosie is starting analysis ont his today

**Comment by gracecbrennan** [comment]
Final session happening today and analysis happening today. 

Wider-session - will try for Thursday 

And one with team before

**Comment by gracecbrennan** [comment]
Playback scheduled for next week

**Comment by gracecbrennan** [comment]
Last session on Thursday last week. 

Will look for some time to have pre-playback discussion ahead of Thursday playback

**Comment by gracecbrennan** [comment]
Pre-playback to happen tomorrow

**Comment by gracecbrennan** [comment]
Session happening later for pre-playback before tomorrow.

**Comment by kerry-b-dfe** [comment]
Pre-playback insights-to-actions session held yesterday.
Board here: [Pre-playback frame](https://lucid.app/lucidspark/49be8a72-cd1a-43a0-aa4b-5452e8a7985a/edit?view_items=UiOoqc9H0UDA&invitationId=inv_a066f0de-5394-400e-9b69-57fc5cdd386e)

**Comment by rosalie-education** [comment]
:user-research: ECF 2 SIT UR playback:
Slides: [ECF 2.0 SIT Research Round 2.pptx](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Test%20and%20prep/User%20Research/ECF%202.0%20SIT%20Research%20Round%202.pptx?d=wb856ba38cf434eb6bd143b2d5326e657&csf=1&web=1&e=VFY0Tr)
Recording: [ECF 2.0 SIT Research Round 2 Recording](https://educationgovuk-my.sharepoint.com/:v:/r/personal/grace_brennan_education_gov_uk/Documents/Recordings/UR%20Playback%20_%20Register%20Early%20Career%20Teachers%20_%20Round%20II%20with%20SITs_%20Registering%20an%20ECT%20and%20add%20a%20mentor-20241107_143552-Meeting%20Recording.mp4?csf=1&web=1&e=aUAZGF&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
