### ISSUE TITLE
Design history for service naming (Dev ticket)

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#483]
Please can we create a design history entry for how we named the service? Content is [here](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/Ee_KhEV-3WdMlVCpMo-Ki4MBVohpz21acqzRZJXJrmRHSQ?e=k4DDjb)

Once ready, the design history entry is to be added [here](https://teacher-cpd.design-history.education.gov.uk/ecf-v2/).

Thank you.

**Comment by Dom-Collins** [comment]
Design history is now merged: https://github.com/DFE-Digital/teacher-cpd-design-history/pull/344

**Comment by gracecbrennan** [comment]
@claire-hughez is going to have one last check and this can be moved to done
