### ISSUE TITLE
Add `/support` contact page

### ISSUE THREAD

**Issue by edujackedu** [DFE-Digital/register-early-career-teachers#486]
## Why?

We would like to keep support's contact information in a single page so we can link to it from other parts of the application.

## What?

- Add a `/support` page with support's contact details
- update [this page](https://github.com/DFE-Digital/register-early-career-teachers/blob/main/app/views/appropriate_bodies/claim_an_ect/find_ect/new.html.erb#L4) to link to the new support page

**Comment by gracecbrennan** [comment]
Still figuring out what to include in this page - start with something low-fi and then we can revise.
