### ISSUE TITLE
Make final content changes and tidy up questions to add an ECT and add a mentor

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#490]
## Why?
There's some last content changes we need to align on.

## What

- [x] Fix the question asking when the ECT starts at the school
- [x] Look at the content that shows when we ask the mentor for an ECT
- [x] Check and update content for What you'll need to do next page for ECTs
- [x] Update statuses on View ECTs page to be slightly more useful - e.g. 'requires mentor' and 'registered' or 'currently training'
- [x] Look at the content for what you'll need to register an ECT, especially focusing on start date and appropriate body
- [x] Tweak check details for the ECT page to remove induction start date and check their order
- [x] Update check your answers page for adding a mentor
- [x] Update last confirmation page for adding a mentor

**Comment by gracecbrennan** [comment]
Met with Claire and Awo to discuss bits of content that need to be updated on prototype. These will be picked up today in time for when testing starts on 23rd.

**Comment by Dom-Collins** [comment]
PR: https://github.com/DFE-Digital/ecf2-prototype/pull/15
