### ISSUE TITLE
Workshop service name with Dom

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#493]
### What

We want to make sure we give the team an opportunity to discuss thoughts and strategies on naming conventions for new AB portal. Things to remember
- the url will be register-early-career-teachers.education.gov.uk/{ab-portal} 

### Our renaming questions

- Do we need 'ECT'?
- Do we NEED 'AB?
- RECORD VS REGISTER & MANAGE?

**Comment by claire-hughez** [comment]
Have options to test.

**Comment by JSJohal** [comment]
![Image](https://github.com/user-attachments/assets/6211d279-32ad-41b8-8978-46bf651c18b5)
![Image](https://github.com/user-attachments/assets/5f0b2f12-59a2-4a40-b0dc-4eb4aa085541)
