### ISSUE TITLE
Complete analysis with reasoning and risks for decommissioning the service for delivery partners

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#506]
## Why?
It was decided early on that the check data for delivery partners service would not be part of the MVP for ECF2.

This was mainly due to wanting to keep our scope as small as possible. It was agreed to be sensible because of the new contracts too.

We should however try and think through greater reasoning for this and the risks involved.

This might be helpful to inform the decisions the programme leads or ECF1 team make for Check data for delivery partners in ECF1. 

## What?
- Write through reasoning for descoping Check data for delivery partners in ECF2
- Write out potential risks involved and any possible mitigations

**Comment by gracecbrennan** [comment]
Claire is going to share a link today on this. Can also be shared with programme leads.

**Comment by claire-hughez** [comment]
https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B31C84CC7-21E5-4C17-B000-3E512AF8517E%7D&file=Removing%20check%20data%20for%20delivery%20partners%20from%20Register%20ECTs%20Analysis.docx&action=default&mobileredirect=true
