### ISSUE TITLE
Run sessions with lead providers BPN and EDT on ECF2

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#507]
## Why?
BPN and EDT weren't at the Lead provider day. We should go over our plans for ECF2 with them

## What?
- Schedule in sessions
- Run them

**Comment by gracecbrennan** [comment]
Claire is trying to go through policy and engagement team to organise sessions here.

**Comment by claire-hughez** [comment]
Still not heard anything from BPN or EDT. Might loop in Colin and co if needed.

**Comment by gracecbrennan** [comment]
We haven't heard back yet.

Will try dropping message in slack to see if we get a response that way.

**Comment by mason-emily** [comment]
Scheduled with EDT for Friday 15th Nov
Waiting to hear back from BPN

**Comment by claire-hughez** [comment]
MIli suggested asking again, I've pinged Colin.

@gracecbrennan do we have the rota for next week? :)

**Comment by gracecbrennan** [comment]
@gracecbrennan to schedule call to chat through

**Comment by gracecbrennan** [comment]
Chatting with Programme Leads this morning to work out if sessions can happen

**Comment by gracecbrennan** [comment]
We're going to go ahead with sessions. 

Mili will attend one of the sessions.

**Comment by claire-hughez** [comment]
For notes: https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/doc.aspx?sourcedoc=%7B0d644ffa-257f-4ba5-87ee-4a6e877e8b5b%7D&action=edit

**Comment by gracecbrennan** [comment]
Grace, Claire and Pete to agree what to present

**Comment by gracecbrennan** [comment]
@gracecbrennan to find time today on how we divide the slides up

**Comment by claire-hughez** [comment]
Claire to send over recording and slides.

**Comment by gracecbrennan** [comment]
@gracecbrennan to share notes
