### ISSUE TITLE
Find out more about DFE Sign In Roles/Sub-services 💭 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#51]
## Why?
We're interested in using DFE sign in. We've found out they offer roles or sub-services, which might help us identify if users are appropriate bodies, lead providers or schools.

Otherwise, we'd have to make that distinction solely in service.

## What?
- Find out more about DFE sign in
- Organise meeting if needed
- Potentially try to find services that use DFE sign in, in this roles-based way
- Consider any next steps, e.g. creating a design history

## Helpful links or other information
[Intranet page for DFE Sign in](https://educationgovuk.sharepoint.com/sites/lvewp00518/SitePages/TopicHome.aspx?csf=1&web=1&e=xizT9Q&CID=7bb51e8a-63f5-4594-9142-c673ee98ac27)

**Comment by gracecbrennan** [comment]
Claire has sent an invite across for Monday to discuss with Steve how he used DfE sign in in a previous project, ahead of speaking with DfE sign in team on Tues.

**Comment by claire-hughez** [comment]
Adding to this discussion thread regularly: https://github.com/DFE-Digital/ecf2/discussions/43

**Comment by gracecbrennan** [comment]
Claire is going to investigate where the data is collected from. 

Emily has suggested a demo on this from one of the other teams using it. Claire is going to contact Tejas on this.

**Comment by gracecbrennan** [comment]
We managed to get an answer on how to check DQT records.

Next Steps - Claire to get into PIMS.

**Comment by claire-hughez** [comment]
We decided:
- We want to explore and test using DFE Sign in for schools, in a way where schools could manage their own onboarding to the ECF2 service
- We want to stick with using Magic sign in for ABs and LPs - potentially DFE Sign in too, but we can't make sure they can access and self-serve their onboarding through DFE Sign in. This is because the organisations aren't recognised as categories in DFE Sign in.

In the future, we could explore offering multiple methods of sign in to users.

**Comment by claire-hughez** [comment]
We'd like to have a techy chat with them and see the payloads from DFE Sign in.

Get the info we need to set it up.

I can contact DFe Sign in for next steps.

**Comment by gracecbrennan** [comment]
@JSJohal is in progress with design history to conclude this ticket.

**Comment by JSJohal** [comment]
Going to try to get through design history post on this today as wasn't able to focus on it too much last few days

**Comment by gracecbrennan** [comment]
Jas has shared with Claire for review.

**Comment by gracecbrennan** [comment]
@claire-hughez has reviewed and @JSJohal to publish today.

**Comment by JSJohal** [comment]
[Design history post published](https://teacher-cpd.design-history.education.gov.uk/ecf-v2/exploring-using-dfe-sign-in/)
