### ISSUE TITLE
Fill in page titles and URLs for the register ects service for schools

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#510]
## Why?
@JSJohal made some good points about why we should not just use the page titles and links in the prototype. These were:
- we don't usually know what the heading / question of a page will be when we first start designing, and usually we'll end up iterating the heading away from from whatever the initial URL was (and it becomes too messy to go back and refactor)
- it's hard to manage when you have various scenarios / dynamic content, as sometimes we have one URL in the prototype serving multiple variations
- it's hard to keep a centralised view and keep on top of managing changes & new pages that have been added
- prototypes are naturally scrappy and messy things :sweat_smile:

As a result, we think we need to track a way of finalising the content for page titles and page URLs. We think we should use a spreadsheet to do this, [and have started this here.](https://educationgovuk.sharepoint.com/sites/TeacherServices/_layouts/15/doc.aspx?sourcedoc={0c1578ea-6431-47b2-9357-c7f610ee178f}&action=edit)

## What?
- Fill in the page titles and page links for what we've developed so far
- Continue to add to this any new pages that are ready for dev

**Comment by claire-hughez** [comment]
As well as showing an error summary, follow the [validation pattern](https://design-system.service.gov.uk/patterns/validation/) - for example, by adding ‘Error: ’ to the beginning of the page <title> so screen readers read it out as soon as possible.

**Comment by JSJohal** [comment]
Going to catch up on this tomorrow morning with @Dom-Collins and try to work through the first set of pages that are being built

**Comment by JSJohal** [comment]
@claire-hughez @mason-emily

Me and @Dom-Collins have populated the [spreadsheet](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=WUitz8&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0) with page titles & URLs
