### ISSUE TITLE
Enter an ECT's national insurance number to match a TRS record

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#512]
## Description
This story is part of the 'Add an ECT' journey.

When an ECT's record cannot be found by searching for the TRN and DOB in TRS, we should ask them for the ECT's national insurance number (NINO). This might help find the record and we would then search in TRS for a match using TRN and National insurance number. If the record still can't be found, the user will not be able to continue the journey.

## User story

**As** a school user
**I need** to find an ECT's record in DQT
**So that** I can validate their teaching record is eligible for funding and training

## Prototype, screenshots & content
This is the NINO page if we've not been able to find on TRN / DOB: [Prototype link](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/nino)

If still not found, then we have this page: [Prototype link](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/not-found)

From this [page in the prototype](https://ecf2-prototy-v3-oz6554dztlkwtv.herokuapp.com/v3/school/find-ect) you enter a TRN as `9999999`, it then redirects to the NINO page. If you enter a NINO starting with `Z`, then it will redirect to the not found page.

Screenshots of the relevant pages:
![image](https://github.com/user-attachments/assets/57571f34-b87f-4eb7-b678-4c508966ea7a)

Content should be as per the prototype.
URLs and validation should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

## Acceptance criteria

- [x] 1. When user submits a valid TRN and date of birth on the 'Find an ECT' page, if the check for a TRS record on TRN and date of birth combined fails to find an ECT's record, user is navigated to the 'We cannot find your ECT's details' page.
- [x] 2. On the 'We cannot find your ECT's details' page:
    - [x] 2a. User is asked to give a National insurance number for that ECT.
    - [x] 2b. Validation and error massages for the NINO field should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).
    - [x] 2c. There will be a 'Back' link which takes the user back to the previous page.
- [x] 3. When user has entered a valid NINO and clicks 'Continue', the NINO is used with TRN to try and find the ECT's TRS record.
- [x] 4. If the ECT's TRS record is found, user progresses to the 'Check if this is your ECT' page (see #478). 
    - [x] 4a. On the 'Check if this is your ECT' page, National Insurance number will be shown in the table ~~instead of~~ as well as the date of birth.
    - [x] 4b. The 'Check if this is your ECT' page will otherwise work in the same way as the existing page for when there is an initial match on TRN and date of birth.
- [x] 5. If the ECT's TRS record can't be found, user is navigated to the 'We were unable to match your ECT's details' page.
    - [x] 5a. On the 'We were unable to match your ECT's details' page, the text 'reviewing their teacher record' will be a hyperlink to https://check-a-teachers-record.education.gov.uk/check-records/sign-in and the text 'Find a lost TRN service' will be a hyperlink to https://find-a-lost-trn.education.gov.uk/start as per the prototype. Both links should navigate the user within the same tab.
    - [x] 5b. There will be a green 'Try again' button which navigates the user to the 'Find an ECT' page where the fields should be reset to blank.
    - [x] 5c. There will be no 'Back' link on the 'We were unable to match your ECT's details' page.

## Technical notes
Note, before we ask for NINO, we will also be adding a check on TRN only to check the TRN exists in TRS - see #685 

## Linked tickets
#459 #685

**Comment by claire-hughez** [comment]
Blocked till tech detail is confirmed.

**Comment by peteryates** [comment]
Can we refer to it as `national_insurance_number` in the code rather than NINO please?

**Comment by peteryates** [comment]
Just had a chat with @gunndabad, the TRS API currently doesn't support searching by national insurance number but it's now on their backlog. It'll work in the same way as `dateOfBirth`, so requests will look like

```
/v3/persons/<TRN>?nationalInsuranceNumber=<ABC123>
```

**Comment by claire-hughez** [comment]
Wow, that was speedy Pete! Thank you.

That's so strange! So the old DQT API does, but the TRS API doesn't yet? Because ECF1 asks for national insurance number currently.

**Comment by TobyRet** [comment]
> Can we refer to it as `national_insurance_number` in the code rather than NINO please?

@claire-hughez @peteryates 
Are we adopting a _general_ rule of having no abbreviations in code (NINO, DOB, TRN) or is this only to be applied to NINO / national insurance number

**Comment by claire-hughez** [comment]
Spell out the abbreviations in database columns, try to use abbreviations where we think there may be ambiguity (e.g. for NINO as national insurance number) but less bothered for TRN (teacher reference number).

**Comment by claire-hughez** [comment]
Gone back to validation one, will pick this up again later.

**Comment by claire-hughez** [comment]
Almost done, PR will be up later.

**Comment by claire-hughez** [comment]
Reviewed by Tony, @mason-emily to have a look on review app.

**Comment by mason-emily** [comment]
Sorry @TobyRet there was a space missing in AC 5a which means the link for finding a lost TRN doesn't work - it should be https://find-a-lost-trn.education.gov.uk/start. Shall I make a separate ticket or can you update in this one?

Otherwise all looks perfect!

**Comment by gracecbrennan** [comment]
we're going to move this back into in progress so @TobyRet can address comment above
