### ISSUE TITLE
Heuristic testing for claim journey (individual activity)

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#533]
## Why?
Since we don't have a lot of time to user test we are going to do some[ heuristic testing](https://www.nngroup.com/articles/ten-usability-heuristics/) on the flows that we finish as we are finishing them. 

## What?
- @edujackedu could you share the list of TRNs we can use in the staging environment? 
- @RoseAsaf let's catch up on this late next week?

**Comment by kas-madrigal** [comment]
Initial work done by Jas, next steps include

For Claim:
- Use error message on form for validation / errors where the user can fix something on the form only
- Use a landing page with more info on the error for all other errors - this means we'll need to update QTS & open induction period errors, and add landing page for exemptions and alerts.
- Design and review landing page separately on channel


For extensions:
- Extensions as secondary action at top of View page
- Add remove to update
- Otherwise, ready to dev the framework - with placeholders for:
- Upfront content - we probably need this, because we know there's lots of info to present to ABs about extensions (at least 2 separate things)
- "What's next" - we may need this to prompt ABs to send stuff to ECTs on appeals, but TBC

**Comment by gracecbrennan** [comment]
Kas has put some time in the end of this Sprint to Heckle sesh the pages

**Comment by gracecbrennan** [comment]
Kas and Rose going to meet on Monday to figure out what activity will look like

**Comment by gracecbrennan** [comment]
Might need to push session back. 

Rose will get some of the framework ready and will check in with Kas when they are back

**Comment by gracecbrennan** [comment]
Kas and Rose going to talk tomorrow on this and find a new date

**Comment by gracecbrennan** [comment]
Kas is going to lead on this whilst Rose is on leave

**Comment by claire-hughez** [comment]
Kas is going to write up the tickets

**Comment by gracecbrennan** [comment]
Rose and Kas going to catch up on this today

**Comment by peteryates** [comment]
I've fixed plenty of the bugs we found [in this PR](https://github.com/DFE-Digital/register-early-career-teachers/pull/707).

**Comment by claire-hughez** [comment]
No need for additional activity beyond what's been covered
