### ISSUE TITLE
Analyse insights around viewing ECT and mentor records

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#540]
## Why?
We're designing (as a lower priority) some features around viewing ECT and mentor records whilst we test the journeys to add an ECT and mentor.

We should think about what insights we could gather around viewing ECT and mentor records from the existing service that might help us understand how users are serving the service and what we might need to include in ECF2.

## What?

Some questions to consider - not necessarily all:

- How many ECTs or mentors do most schools have on their view pages? As a mean, mode, min and max. This is not per academic year, but in total, but would need to scope by the filters used.
- Is it useful to see how many ECTs are currently training by school, completed, left training?
- How are the filters available currently used? Do people use them?
- How often are people clicking into mentors? Do they?
- Try to evaluate what we don't show that they want to get to, or want access to

 ![Image](https://github.com/user-attachments/assets/68f53e16-2583-4df1-bdbf-53d7f5ac2b61)

**Comment by gracecbrennan** [comment]
Emma is looking at this today and tomorrow

**Comment by gracecbrennan** [comment]
Hoping to have something by end of day tomorrow
