### ISSUE TITLE
Design for when a TRN is inactive when trying to add an ECT

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#542]
## Why?
TRNs can be inactive in DQT.

I think this is when the TRN is a duplicate. It's been deduplicated but the teacher or the school they work for hasn't always been informed.

## What?
- Block inactive TRNs from being used when they try to register an ECT
- Show them how to find the correct TRN, most likely from using Check a teacher's record or asking the teacher themselves to use Find a lost TRN

**Comment by JSJohal** [comment]
I think this will be covered by a generic 'cannot be found / unable to match' error page.
![Image](https://github.com/user-attachments/assets/0754fe3b-54b0-4cda-a964-bbb1a756fb7b)
https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-ect/not-found

**Comment by gracecbrennan** [comment]
@claire-hughez is happy with this? Can we move to done?

**Comment by claire-hughez** [comment]
@robthompson16 @JSJohal could we tweak this to remove the 'your'?

'We were unable to match the ECT's details'

**Comment by robthompson16** [comment]
Haven't seen this content before but reckon you could shorten it by merging the H1 and intro line to 'We cannot match the ECT with the details you provided'

You could also shorten the last sentence to: 'Alternatively, you could ask the ECT to <u>check their TRN<u>.

Just helps the user scan through it more quickly.

Also, on the second line the full stop shouldn't be underlined.

**Comment by claire-hughez** [comment]
Thanks Rob! I think it's worth telling them about the service ECTs can use to check their TRN, but otherwise sounds good

**Comment by robthompson16** [comment]
OK no worries Claire, happy to leave the last sentence as is in that case

**Comment by gracecbrennan** [comment]
Meeting about this today to go through unhappy path tickets.

**Comment by JSJohal** [comment]
![image](https://github.com/user-attachments/assets/d4b222d3-40b9-4eba-9198-80d9f71d5847)

https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-ect/not-found (p: review)
