### ISSUE TITLE
Create design for playing back NINO when it's matched and DOB hasn't in add ECT journey

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#543]
## Why?
We've created our designs for confirming teacher details using DoB, but there's also the scenario of when we've used NINO instead.

## What?
- Consider and design for what to do when we match on a TRN and NINO, as DOB wasn't matched
- Design for disregarding the DOB entered, and not shown the one entered (or the correct one) but only show the NINO during the add ECT journey
- Apply this to the confirm the teacher page and also the check your answers page

**Comment by JSJohal** [comment]
Need to check what happens in ECF1 when a ECT is added with a DoB that didn't match but NINO did. DoB shows on manage ECTs view but need to check which DoB this is - the one that the user entered or the one from the DQT

**Comment by JSJohal** [comment]
Check your answers / confirm ECT when using NINO instead of DoB as per screenshots below

![Image](https://github.com/user-attachments/assets/42579222-ed23-49ac-b59f-51579bba2901)
![Image](https://github.com/user-attachments/assets/6c766aac-1b34-48f3-853b-ef106eb05bcd)

**Comment by claire-hughez** [comment]
looks great!

**Comment by JSJohal** [comment]
> I'll be controversial and apologies if treading back over if we already discussed - do we need to playback NiNo and DoB at all on the final CYA page?

i don't think we _need_ to - we've included it as it's an answer that's been given within the journey and the pattern typically plays back all the answers that have been input - although it's a bit odd here because it can't be changed. happy to go either way with keeping or removing - if removing we'd only need to keep the TRN and name

**Comment by JSJohal** [comment]
![image](https://github.com/user-attachments/assets/36cb84fe-8da1-408d-a83e-7e727efc5b3d)
After chat, removed DoB / NINO. Prototype [here](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/school/check-answers)
