### ISSUE TITLE
Iterate check your answers page in add ECT journey

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#544]
## Why?

We've not been able to focus on the way to format the 'check your answers' page in the add ECT journey. We need to figure out how the answers will be formatted and how the change links will work.

## What?
- Consider how to play back all the information, in differing scenarios - considering the TRN, DoB/NINO and name (if they can be changed after confirming)
- Consider how to play back programme information - when the information is entered, but also when the information has been confirmed as using per the defaults
- Possibly add field for when 'saving programme details'
- Consider how to handle playing back when DoB and NINO has been entered (and DoB hasn't matched for example)

**Comment by gracecbrennan** [comment]
This is ongoing - has clarified some point with Emily and Claire. 

Halfway there on this.

**Comment by gracecbrennan** [comment]
A few tweaks to make and this will be moved into review bby the end of the day

**Comment by JSJohal** [comment]
Couple of content bits to review and have a first go at:
- update the H1 on the check your answers page, possibly to mention who's being added
- look at updating the field on the correct name input, to be more explicit to state 'enter full name'

**Comment by JSJohal** [comment]
@claire-hughez I've added a couple of first drafts for content tweaks we could make to:
- update the H1 on check your answers to be clearer about who's being added
- update the field on the enter correct name pages

Happy to go with something else for content if this isn't what you had in mind!

**The GitHub files are:**
- https://github.com/DFE-Digital/ecf2-prototype/blob/v4/app/views/v4/school/check-answers.html
- https://github.com/DFE-Digital/ecf2-prototype/blob/v4/app/views/v4/school/review-ect-details.html
- https://github.com/DFE-Digital/ecf2-prototype/blob/v4/app/views/v4/school/mentor/check-answers.html
- https://github.com/DFE-Digital/ecf2-prototype/blob/v4/app/views/v4/school/mentor/review-mentor-details.html

**Screenshots:**
![Image](https://github.com/user-attachments/assets/3d59acff-4614-4f8f-a964-4cf336ed9ffc)
![Image](https://github.com/user-attachments/assets/b9048369-ad53-4d8d-aa21-bf4f530fcc58)
![Image](https://github.com/user-attachments/assets/d311b5a4-a818-4030-b553-ffb9fd7df0a0)
![Image](https://github.com/user-attachments/assets/4c2c07df-db81-4b12-bbce-7ea6de14dd67)

**Comment by gracecbrennan** [comment]
@claire-hughez to review
