### ISSUE TITLE
Get Staging environment ready for testing by non-developers

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/register-early-career-teachers#548]
The staging env is nearly ready for non-dev testing, the steps to do it are:

* navigate to [the staging env](https://cpd-ec2-staging-web.test.teacherservices.cloud/appropriate-body), note that the path ends with `/appropriate-body`
* you should be prompted to log in, as we're on staging we can use personas where we choose Velma or Fred
* now we're in, you should see a list of ECTs
* staging is configured to use TRS's preprod environment, [these TRN and DOB combinations should work for testing claims](https://github.com/DFE-Digital/register-early-career-teachers/wiki/Teacher-Qualifications-API-test-data-for-preprod)

| AB personas | ECTs |
| ---------- | --------- | 
| ![image](https://github.com/user-attachments/assets/3890c048-c4f1-4f3f-b05f-172695f58463) |![image](https://github.com/user-attachments/assets/fbe2fe68-2faa-49f5-8afa-c2ea7e077b44) |

## Extra steps

* [ ] add a way of easily navigating to unhappy exit pages for use in non-production envs, these could be buttons on the bottom of the page which are in a box that makes it obvious they're not part of the _actual_ app
* [ ] the presence of these boxes should be controllable by an environment variable and enabled in [review](https://github.com/DFE-Digital/register-early-career-teachers/blob/main/config/terraform/application/config/review.yml) and [staging](https://github.com/DFE-Digital/register-early-career-teachers/blob/main/config/terraform/application/config/staging.yml)

**Comment by kas-madrigal** [comment]
@peteryates @edujackedu could you prioritise this for Thursday?? we need it for the group activity
