### ISSUE TITLE
Start scoping document on mentor eligibility and funding rules for 2025

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#552]
## Why?
Programme leads have asked us to have a look at the 2025 changes for mentor eligibility and funding rules.

We'll need to consult others on how to best handle some of this, so good to start early.

## What?
- Emily to add section on 3 year rule for mentor payments
- Claire to add section on ITT mentor eligibility

## Helpful links or other information
Use this template: https://educationgovuk.sharepoint.com/:w:/s/TeacherServices/EWWpBfh6FMFAnp0jgSqtyr4Brsu7JrCJNa0KvEFPf8PBbA?e=a0kxaS

**Comment by mason-emily** [comment]
Claire & Emily to catch up on this

**Comment by gracecbrennan** [comment]
Check where this has been left with Ben - in-time for programme roadmap session on 13th November

**Comment by gracecbrennan** [comment]
Claire has made a start on this 

Emily has nearly completed first draft of rule 3

**Comment by gracecbrennan** [comment]
Could @tonyheadford take a look and see if anything is missing please?

**Comment by claire-hughez** [comment]
https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/doc2.aspx?sourcedoc=%7B41A91DEC-B2AD-48D1-896A-9A4AEA5F1F8D%7D&file=Changes%20to%20funding%20for%20mentor%20training%20for%202025%20-%20ITT%20mentors%20and%20the%203%20year%20rule.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1730822861125&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=e772822a-83df-4676-9594-c77074d5c246&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=c6acb37d-0728-4b50-a185-f679ab9fbd52
