### ISSUE TITLE
Analysis for changes to eligibility mid-induction

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#558]
## Why?

We check eligibility at the beginning of an induction. For most inductions, eligibility to complete an induction won't change between starting and completing an induction, however there are some exceptions to this rule which would change an ECT's eligibility to mid-induction. These are:

- An ECT gains an exemption during their induction
- An alert is added to an ECT during their induction which prohibits them from teaching.

**Exemptions**

**What we know** 
- We know induction exemptions will live in TRS. 
- Induction exemptions are not driven by induction as a process. They usually happens usually BEFORE an induction i.e. the way you get QTS BUT there are exceptions to the rule 
- QTLS is the main example of an exemption which can change over time.
- Teachers who gain QTS via an international route 
- What do we do if there is an exemption midway an induction? i.e. If a person is doing induction and get awarded QTLS they are suddenly exempt from induction and we need to change their status halfway. 

**QTLS""

QTLS is gained after successfully completing a six-month period of professional formation and maintained through membership to the Society for Education and Training (SET). Those six months of training are considered a substitute to induction, so if you have QTLS you don't have to do induction (you are exempt). QTLS _can_ be a route to QTS, but can be gained by someone who has already gained QTS by another route. 

| Scenario | Before QTLS gained | After QTLS gained | After QTLS membership lapsed | What does this mean for the AB Service? |
| --- | --- | --- | --- | --- |
| Teacher gains QTS via QTLS | Not eligible to complete induction due to not having QTS | Exempt from Induction | Not eligible to complete induction due to not having QTS | There is no point in time where this teacher is able to complete an induction - this is not in scope for the AB service |
| Teacher gains QTS via another route, then gains QTLS | Eligible to complete induction | Exempt from Induction | Eligible to complete induction | The teacher's eligibility to complete induction changes over time. This is in scope for the AB Service. |

**Alerts**

An alert can be added to a teacher's record at any time during a teacher's induction.

If a teacher already has an alert which means they are prohibited from teaching when they are claimed by an AB, we are applying a system rule which blocks the user from proceeding, as defined in https://github.com/DFE-Digital/register-early-career-teachers/issues/553, because we know there is no valid way for them to complete an induction. For any other alert type, we allow the Claim process to proceed, but display the alert to the AB so that they are informed and can do additional checks if needed.

If a teacher has a prohibition alert added while their induction is in progress, then there is also no valid way for them to proceed with their induction. For other alert types, the induction can validly continue. On the AB Portal currently alerts are flagged to users via the ECT's record.

## What?

- We need rules on how the CPD service will handle inductions where the ECT has become ineligible or exempt during the course of the induction.
- Should they be allowed to finish inductions/outcome to be recorded/claimed (different cases could have different conclusions)? Conversation with colin. 
- We need to know how the service will "know" when an ECT has become ineligible or exempt to complete induction mid-induction
- We need to define what happens to an ECT's data on the CPD service when they become ineligible or exempt to complete induction mid-induction

## Conclusion 
These cases are quite rare. There is no need for any further API requirements to fulfil this need. We will liaise with TMU team on how to design the manual process with the new team. 

## Out of scope

- The API won't change but the system may create a task. We need to clarify this in future convos. 
- James - support task needs to be created on TRS console to update exemptions. 
- Welsh induction statuses are still missing to be discussed. i.e. if they're done it in Wales they're exempt.

**Comment by kas-madrigal** [comment]
@joe-harrison-dfe / @emily-prudence-dfe could you share your notes from that conversation to add to the nuance of this ticket? I have a lot of notes on difference scenarios that I don't want to add if they are not clear and I'm wondering if anyone else caught them

**Comment by claire-hughez** [comment]
Can try and cover on Friday, if there's time.

**Comment by gracecbrennan** [comment]
@kas-madrigal will update with conclusion on this

**Comment by kas-madrigal** [comment]
added conclusion to the description, this can be moved to done
