### ISSUE TITLE
Design for when email can't be used when adding an ECT because the email already exists

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#565]
## Why?
When adding an ECT, if the email the school user adds already exists for a different person with a different TRN, we need to stop the user from continuing and present an error page.

We're fine when an email is reused when the TRN is the same.
We're not fine with it when the email is reused and the TRN is different.

## What?
- Design a way to block existing emails from being used when they try to register an ECT - if the TRN is different for that email
- Design a way to block existing emails from being used when they try to register a mentor  - if the TRN is different for that email
- Offer a route onwards, such as starting again

This might be legitimate when:
- an ECT has transferred schools, so they keep their email, but they get registered as an ECT again at the 2nd school
- an ECT later becomes a mentor and their email has been kept the same, or vice versa

**Comment by claire-hughez** [comment]
We'll look at this next sprint, get analysis to consider when the same email might be okay.

**Comment by JSJohal** [comment]
![Image](https://github.com/user-attachments/assets/c4278a62-90e1-462c-8488-531095f9a361)
First thoughts

@robthompson16 Lets catch up on ideas for content? Also not sure about 'back' link - I'm thinking it may be worth keeping because the user can go back and put in a different email? Doesn't feel like the end of the journey?

**Comment by JSJohal** [comment]
![image](https://github.com/user-attachments/assets/f208cf67-92b3-4a7c-82f9-e04a5f431d45)

**Comment by claire-hughez** [comment]
Can we be more specific here?

_This email address has already been used to register a different early career teacher or mentor.

Make sure to use an email address that is unique to the person you are registering.

For example, don't use generic email addresses like admin@example.com._

**Comment by gracecbrennan** [comment]
@JSJohal is going to catch up with @robthompson16 on review comments

**Comment by robthompson16** [comment]
@claire-hughez how about this?

**Comment by robthompson16** [comment]
Got a nice low readability score :-) 
<img width="105" alt="image" src="https://github.com/user-attachments/assets/4e76583f-1627-44ca-b459-8f78dbf35afb">

**Comment by JSJohal** [comment]
@robthompson16 @claire-hughez 
should we hyperlink the email address "admin@example.com" as per the screenshot? usually that's the case when we want to make it clickable because you may send an email to that address, which isn't the case for us... although i do get we're usually used to seeing emails that are hyperlinked, but just doesn't make sense in this case?

**Comment by robthompson16** [comment]
Good point @JSJohal I think hyperlinking would help highlight the text and make the point that it's a generic email. In the unlikely scenario that someone did try to send an email it would bounce back anyway

**Comment by JSJohal** [comment]
Updated in prototype [here](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-ect/cant-use-email) (p: review)
