### ISSUE TITLE
Validation rules for existing fields in the Add ECT journey

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#582]
## Description
This story adds validation rules and error message content for the existing fields in the 'Add ECT' journey (TRN, DoB & email).

## User story

**As** a school user
**I need** to know when I have not completed a step of the journey in the desired way
**So that** I can correct my answer and progress through the journey to add an ECT

## Prototype, screenshots & content

Screenshots of relevant pages:

![Image](https://github.com/user-attachments/assets/dac972d7-fa18-45c3-be3b-1d6d123cdfe1)

![image](https://github.com/user-attachments/assets/77a6c909-3356-4c41-ac10-a07aff7a3567)

Validation messages should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

## Acceptance criteria

- [ ] 1. Validation rules and error messages are added for the TRN field.
- [ ] 2. Validation rules and error messages are added for the date of birth field.
- [ ] 3. Validation rules and error messages are added for the email field.

## Technical notes
Note, validation rules and error message are not limited to this page as they apply to the field - to flag to AB portal team too.

## Linked tickets
 #473 #475

**Comment by gracecbrennan** [comment]
This is nearly complete.

**Comment by claire-hughez** [comment]
Toby will ping Emily and I the review link - this won't be a problem when the front page is merged

**Comment by claire-hughez** [comment]
Toby to look at applying validation rules to other parts of the data model/codebase

**Comment by claire-hughez** [comment]
![Image](https://github.com/user-attachments/assets/9e4fcaf6-9be0-4bef-84f2-52f01e00b9b5)
Hi Toby,

These look great and function as expected. Just noticed one minor content issue here. It should say 'the', not 'your'. 
I've added a PR to fix this here:
https://github.com/DFE-Digital/register-early-career-teachers/pull/717

**Comment by mason-emily** [comment]
Looks great - I noticed the points below, shout if they don't make sense!

TRN field - I think this field is set to numbers only and you can't enter more than 7 characters. Please could we update this to use error messages rather than restricting the field input? It should allow letters and '/' to account for historical TRNs that can be in a different format (e.g. 'RP99/12345'), so the only restriction should be no more than 7 digits amongst the total character input, and can't be blank. We have code on ECF1 that ignores any letters or symbols and adds leading 0s to make the TRN 7 digits long for the TRS check - @tonyheadford could you point to this?

DoB - date in the future shows the 'The teacher cannot be less than 18 years old' error rather than 'The date of birth must be in the past' error

Email - email address too long error isn't coming up for me, it says the 'Enter the email address in the correct format' when the issue is that it's more than 254 characters

**Comment by claire-hughez** [comment]
_TRN field - I think this field is set to numbers only and you can't enter more than 7 characters. Please could we update this to use error messages rather than restricting the field input? It should allow letters and '/' to account for historical TRNs that can be in a different format (e.g. 'RP99/12345'), so the only restriction should be no more than 7 digits amongst the total character input, and can't be blank. We have code on ECF1 that ignores any letters or symbols and adds leading 0s to make the TRN 7 digits long for the TRS check - @tonyheadford could you point to this?_
Emily, I wonder if this is from the AB work and not Toby's ticket potentially - might be good to check with Pete on this one.

**Comment by mason-emily** [comment]
Messaged @peteryates on the above - we shouldn't restrict the input to X characters because if people paste in longer values they're silently truncated. @TobyRet are you happy to update the TRN field to use the error messages in [here](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi)?

**Comment by claire-hughez** [comment]
Stick on standup at the end to talk through TRN validation.

**Comment by claire-hughez** [comment]
Let's confirm today on making changes.

**Comment by claire-hughez** [comment]
We're going to stick with stripping letters and symbols from the TRN. So any input can be entered.

**Comment by gracecbrennan** [comment]
We're going to close this ticket for now and @mason-emily will create a new ticket that will include the two new points
