### ISSUE TITLE
Create a validation rules document

### ISSUE THREAD

**Issue by joe-harrison-dfe** [DFE-Digital/register-early-career-teachers#586]
## Why?

Keep track of all the AB validation rules across the journey and the pages on which they occur.

## What?
- A spreadsheet that outlines the data fields by page and their associated validation rules.

## Out of scope

Document here - https://educationgovuk.sharepoint.com.mcas.ms/:x:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B501226ae-6c31-443c-b246-13b8a5970847%7D&action=edit&wdPreviousSession=c6e70b82-f3c4-1046-804c-cea0b46d2a76

**Comment by peteryates** [comment]
Would this make more sense as [a wiki page](https://github.com/DFE-Digital/register-early-career-teachers/wiki)/?

**Comment by gracecbrennan** [comment]
Made a start on this

**Comment by joe-harrison-dfe** [comment]
Update:
- Validation rules documented has been merged into one by Emily M, the sheet shows all validation rules and can be filtered to show RECT and AB rules as well as shared rules.
-  Doc can be found here - https://educationgovuk.sharepoint.com.mcas.ms/:x:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B0C1578EA-6431-47B2-9357-C7F610EE178F%7D&file=Register%20ECTs%20page%20titles%20and%20URLs.xlsx&action=default&mobileredirect=true
