### ISSUE TITLE
Define how we identify and match Appropriate Body data to DfE sign-in records

### ISSUE THREAD

**Issue by joe-harrison-dfe** [DFE-Digital/register-early-career-teachers#593]
## Why?

Make sure we can match up DfE sign in records to AB data in order to identify Appropriate Bodies and make sure that an ECT is associated with the right AB

## What?
- Work with Pete to understand the data fields that come from DfE Sign-In
- Decide on how we can match up DfE Sign-in IDs to CPD AB IDs.
- Ensure that user's are shown records associated to their AB.

**Comment by gracecbrennan** [comment]
Speak to Pete to understand next steps.

**Comment by joe-harrison-dfe** [comment]
Updates from discussion with Pete:

When an unauthorised user enters the service, they are directed to DfE Sign-in. When they have logged in through DfE Sign In, they are redirected to the site with an access token which contains:

| Access Token Data Fields  | 
| --------------|
| id_token | 
| current_user (name, email) |
| urn | 
| school_name|
| dfe_sign_in_organisation_id |
| dfe_sign_in_user_id |

Once we have received the access token, we use the ID information to query the DfE Sign-In API to determine whether the user has an AB role associated with their Organisation ID or not. Further info on how that works can be found here - https://github.com/DFE-Digital/login.dfe.public-api?tab=readme-ov-file#get-organisations-for-user

The existing problem is that there is currently no way of matching up the DfE Sign-In organisation ID with with our list of CPDs, so we need to create a matching attribute for our use. After talking with Pete, it seems like the easiest solution for MVP is to manually create a list of all eligible Appropriate Bodies by Organisation name and then match this against the DfE Sign-In API data which will display an Organisation Name and ID. 

Once we are up and running, if a user comes into the service with an Organisation ID that doesn't match a held AB, we can create an AB record in our database using data from their organisation.

**Comment by joe-harrison-dfe** [comment]
@peteryates Can you just double check that this is all correct and then I am happy to draw up a dev ticket for implementing this !

**Comment by peteryates** [comment]
Yep looks good. We have a few issues on this topic already including #453. Maybe it's worth consolidating them?

**Comment by gracecbrennan** [comment]
@joe-harrison-dfe to write up dev ticket and then this can be closed.
