### ISSUE TITLE
Define a complete list of service rules for Release & Outcomes

### ISSUE THREAD

**Issue by joe-harrison-dfe** [DFE-Digital/register-early-career-teachers#594]
## Why?
Map out business rules for release & outcomes to understand what validation rules are left to introduce and to write out a list for use when sharing with policy colleagues.

## What?
- Service/Business rules document similar to the existing document for Claim an ECT
- Validation rules for Release & Outcomes added to the validation rules spreadsheet
- Analysis on validation rules on when an induction was completed
- Continue work on the terms validation ticket here - https://github.com/orgs/DFE-Digital/projects/48?pane=issue&itemId=81019652&issue=DFE-Digital%7Cregister-early-career-teachers%7C341. Speak to Korin to pick this back up.

**Comment by gracecbrennan** [comment]
Just starting to look at this one now

**Comment by gracecbrennan** [comment]
Kas has shared some more useful docs and Joe will continue to pull together before sharing for review.

**Comment by gracecbrennan** [comment]
This is going to roll over to next sprint

**Comment by joe-harrison-dfe** [comment]
Written first draft of service rules document. 

Needs reviewing by Kas and other team members, I've added in a few questions for additional service rules to be answered too.

Document here - https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/doc2.aspx?sourcedoc=%7B093d10d7-1084-48fc-a731-5d763cd59d22%7D&action=edit&wdPreviousSession=ff3d36b8-d8ed-8299-3dc7-c2bfb608d404

@kas-madrigal

**Comment by claire-hughez** [comment]
Kas needs to have a look at this. @kas-madrigal

**Comment by gracecbrennan** [comment]
This will be picked back up following testing

**Comment by gracecbrennan** [comment]
This can be moved to done as it is replaced by new version @joe-harrison-dfe  has completed
