### ISSUE TITLE
Define Extensions placeholder content

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/register-early-career-teachers#596]
As part of the induction extensions journey, we have designed a placeholder page which sets out key information before starting the journey.

The key points that should be covered off in this content are here:

![Image](https://github.com/user-attachments/assets/5bf2237a-48a4-47e1-98ef-217d619171f0)

**Comment by claire-hughez** [comment]
I wonder if this could be presented like:

1. What you'll need to know before extending a teacher's induction
2. Asking or the fields for that extension
3. Highlighting next steps, including how extensions can be appealed

**Comment by emily-prudence-dfe** [comment]
Before recording an extension, a final assessment must have been completed by the ECT's School Induction Tutor or Headteacher, which provides a recommendation on the ECT's performance against the Teaching Standards. As an Appropriate Body, you must have made a final decision on whether to extend the induction on the basis of this recommendation.

You do **not** need to record an extension when an induction needs to be extended due to a period of extended absence (an "automatic extension")

An ECT may appeal an extension to their induction. You must advise the ECT of their right to appeal and provide them with information about who to appeal to, and the time limit for doing so. More information can be found [here](https://assets.publishing.service.gov.uk/media/668e948349b9c0597fdafa6a/Induction_Appeals_Procedure_July_2024.pdf)
