### ISSUE TITLE
Create a lo-fi journey flow for what registration for a new school user could look like 📝 🎨

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#60]
## Why?
We want to start visualising what a user journey could look like, and we feel like the simplest and easiest one to start with would be the user for a school user to register to provide training information for the first time.

We can only visualise this in a low fidelity way for the moment, as there's some unknowns about all the data we'd be collecting from users.

Outputs could be a Lucid board with a flow, lo-fidelity mockups - something which can be built on, and further refined as we learn more.

## What?
- create a first draft of a user journey flow for new school users
- keep it simple, and something which leaves room for flexibility and is adaptable
- try to base it on what we know now (i.e data requirements)

**Comment by gracecbrennan** [comment]
Jas made a start on this one yesterday.

**Comment by gracecbrennan** [comment]
Jas and Awo working alongside each other on this one - hoping to have something by tomorrow or end of the week to show.

**Comment by JSJohal** [comment]
[Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?viewport_loc=114709%2C9537%2C26299%2C12836%2C0_0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) with thoughts and ideas so far, and a few things to still consider.

May be worth having a design brainstorm / chat around some of these after standup. 

Some of my questions / wonderings:

- Would an academic year level task-list (add your ECTs, add your mentors) and a 'manage' view which lets you add ECTs and mentors or make changes later be too much for MVP? It'd be multiple ways of doing the same thing - one at the beginning of the year (add multiple in one go) and a view for later in the year. 
- Do we need 'defaults' for programme year and appropriate bodies for the user? Do we need to call them out as 'tell us your default' - or can we just ask the user for a programme type / AB when adding an ECT, and then the next time they add one - offer the same one as an easy radio option with a different option for other? Something like that would remove the need to have a 'programme set up' journey as well as journeys for adding participants
- How can we add new mentors before adding new ECTs? If you add a new ECT in ECF1 and haven't got a mentor, the user then has to go create a new mentor and then assign that ECT to that mentor - which feels overly complex

**Comment by JSJohal** [comment]
Update after discussing with team:

- Individual level task list might be worth exploring more than a year based one - as year based one doesn't lend itself well to users understanding that they can come back in the year and make changes
- We don't necessarily need to collect 'default' information in that form, we could make it more intuitive and get rid of it as a journey - for example, when an ECT is added and we collect an AB, next time an ECT is being added we can present previously used ABs in a radio list with an other option, therefore making it easier to select the same option again.
- The need is to make life easier for users, so they can select the same info as most schools will reuse details like AB and programme type - that means the need is not necessarily for a default setting
- Could still possibly look at adding multiple ECTs with basic info in one sitting, such as add another, and then creating task lists / more detailed information for them after. Or alternatively, add multiple ECTs with the same information - i.e. select appropriate body, select programme type, and then mini journeys to add an ECT with add another.
- We can explore in research about schools telling us about LP/DP pairings. No decision on that yet
- We can try to get data about how many schools add only one ECT, how many add multiple in one sitting

**Comment by mason-emily** [comment]
Jas working on options in the board and points above

**Comment by gracecbrennan** [comment]
@JSJohal to share changes this morning

**Comment by gracecbrennan** [comment]
@JSJohal has shared link for review

**Comment by JSJohal** [comment]
Screenshots added for review of what we've covered as part of this ticket
More detail and information on the [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=y~416yQXBSsW&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)
![Sprint Review - Page 1 (1)](https://github.com/user-attachments/assets/9f43cddd-c400-40d1-8264-52d8b16c8160)
![Sprint Review - Page 1 (2)](https://github.com/user-attachments/assets/54c67408-55ba-4175-917a-30f8e0c2883c)
![Sprint Review - Page 1 (3)](https://github.com/user-attachments/assets/2e16f7f1-619f-42ce-b6e7-4796c95b49f3)
![Sprint Review - Page 1 (4)](https://github.com/user-attachments/assets/d870a4f9-c51a-4e76-a794-a0ae340a1fd1)
![Sprint Review - Page 1 (5)](https://github.com/user-attachments/assets/945c0a74-9057-4876-83b9-1387cd7d5e1f)
