### ISSUE TITLE
Design history post on what we're building for add an ECT so far

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#606]
## Why?
We want to publish a design history post detailing what we've designed and learnt about adding an ECT in the early rounds of research.

## What?
- Include what we've designed and why
- What we're most unsure about (asking DP / LP / AB)
- Iterations we've made
- How we're approaching saving defaults
- Why saving and returning later is out of scope for our MVP

**Comment by aabdi18** [comment]
I've written up the general structure on a [word doc](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Add%20an%20ECT%20design%20history.docx?d=w81cb6d6e88854a248ab44d6706b87bcc&csf=1&web=1&e=HzcSik), 
so far completed the intro, explanation of default programme choice design, adding clarity in terminology, adding mentor records through the ECT journey

Need to add:
- what we're unsure about 
-why saving and returning later is out of scope
-future plans/conclusion 
advice on the above would be great, and then I can put into code and upload, happy to hear thoughts on what I have so far also :)

**Comment by gracecbrennan** [comment]
Awo to catch up on points in the ticket with Jas and Claire

**Comment by aabdi18** [comment]
Ready for review on the[ word doc](https://educationgovuk-my.sharepoint.com/:w:/r/personal/awo_abdi_education_gov_uk/Documents/ECF2/Add%20an%20ECT%20design%20history.docx?d=we359382f372a494aa3f9040993e41da7&csf=1&web=1&e=MB8rJJ)
not sure if a future plans paragraph is needed but happy to add one in if relevant. would appreciate any corrections and then i put it into code and upload :)

**Comment by gracecbrennan** [comment]
@claire-hughez, @jas to take a look

**Comment by claire-hughez** [comment]
Lead provider and DP: https://educationgovuk.sharepoint.com/sites/TeacherServices/_layouts/15/doc.aspx?sourcedoc={3d163c02-a3ff-4202-9fa3-faaad100fab4}&action=edit

**Comment by claire-hughez** [comment]
Corrected name: https://educationgovuk.sharepoint.com/sites/TeacherServices/_layouts/15/doc.aspx?sourcedoc={dfcc3e30-868e-4416-89c6-670d2d19d80b}&action=edit

**Comment by JSJohal** [comment]
Start date: https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Asking%20for%20an%20ECT%27s%20start%20date.docx?d=w662ea4f0f53c4813b18fd229c070e898&csf=1&web=1&e=BgtHLH

**Comment by JSJohal** [comment]
Started adding on this branch https://github.com/DFE-Digital/teacher-cpd-design-history/tree/add-an-ect

Yet to add start date, assigning mentors and default choices

**Comment by gracecbrennan** [comment]
A few more docs to add here.

**Comment by JSJohal** [comment]
https://github.com/DFE-Digital/teacher-cpd-design-history/pull/345
merged
