### ISSUE TITLE
Increase number of instances on Azure

### ISSUE THREAD

**Issue by gracecbrennan** [DFE-Digital/register-early-career-teachers#607]
## Why?
We are currently restricted on how much Azure resource we can use due to our plan being on the cheapest number of instances in a few cases. This means, when we attempt migration of data, it quickly becomes very slow. For example, it took ten hours to complete half of the teacher migration

## What?
Grace to explore options for upping the number of instances we have.

**Comment by peteryates** [comment]
This ticket is closely related to #523 - probably makes sense for them to be done together.

**Comment by claire-hughez** [comment]
This is done.
