### ISSUE TITLE
Confirm what data is needed to be collected during initial registration for schools for both mentors and ECTs

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#61]
## **Why?**
We need to understand the data that we need to collect as part of the school registration journey so we can create relevant designs to test. We are designing the journey for both ECTs and mentors.

## **What?**
Write up data needed for ECTs and mentors.

## **Helpful links or other information**
[Data we need board](https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=y01YD2y_B7-k&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6)

#18 #4

**Comment by gracecbrennan** [comment]
Separating what we needs from schools vs providers. Working on this today.

**Comment by gracecbrennan** [comment]
Session happening with Pete and Tony to discuss.

**Comment by mason-emily** [comment]
See https://github.com/DFE-Digital/ecf2/issues/18#issuecomment-2271688441

**Comment by gracecbrennan** [comment]
@mason-emily to write up into Service Rules
