### ISSUE TITLE
Start migrating training periods from ECF1 to ECF2

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#612]
## Why?
Training periods will tell us about the time an ECT or mentor spends training.

We need to try and see what we can migrate from ECF1 and get this process started.

## What?
- Set up training period migrator
- This will need to process validated induction records for ECTs and mentors in a similar manner to `SchoolPeriodExtractor` to obtain the periods of training with different providers or training programmes.
- Create `TrainingPeriod` records from this extract

## Out of scope
Consider if this needs to work within induction periods?
Whether this should involve checking finance data to verify/support this.

**Comment by gracecbrennan** [comment]
This is ongoing. Tony is trying to write some specs. 

Will likely share a PR today

**Comment by claire-hughez** [comment]
Nearly at the end of this, for good enough to get into migration environment.
