### ISSUE TITLE
Start migrating mentorships from ECF1 to ECF2

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#613]
## Why?
Mentorships are the time an ECT spends being mentored by a mentor.

We need to get started on migrating this information from ECF1 to ECF2.

## What?
- Process validated induction records of ECTs in a similar manner to `SchoolPeriodExtractor` to obtain the periods of time they have been mentored
- Create `MentorshipPeriod` records for the extracted data.

**Comment by gracecbrennan** [comment]
This is in progress still

**Comment by claire-hughez** [comment]
🚢 Getting some bits up and running in migration env, Pete has upped the power of it. Kicked it off again this morning.

**Comment by gracecbrennan** [comment]
There's a PR open for this. Tony is going to do some local testing and needs to get into migration before he can test properly.

Lorenzo to review
