### ISSUE TITLE
Work out a way to share the RECT data model and keep it updated in 1 place

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#614]
## Why?
At the moment, the data model exists as screenshots that others can't easily edit or update.

We want a single place for the data model to be updated and looked at by others, so we have 1 source of truth.

## What?
- Re-create the data model we've started in a medium where it can be shared and updated easily by others
- Make the changes agreed to induction periods

**Comment by gracecbrennan** [comment]
for review: https://github.com/DFE-Digital/register-early-career-teachers/wiki/Data-schema
