### ISSUE TITLE
Engagement with 3rd parties (ECT manager and Mosaic)

### ISSUE THREAD

**Issue by gracecbrennan** [DFE-Digital/register-early-career-teachers#618]
## Why?
We want to engage with external digital organisations involved in induction. This will help us work out how we can best support ABs that use their services.

It might also help us better support schools, because they also tend to use these digital services, and we might want to be consistent with how we refer to certain things or show information.

## What?
- Plan session for engagement with the 2 digital services we're meeting with so far
- Have list of questions ready to ask them

## List of questions so far

How do you record the number of terms of induction?  (We think this is to 1 dp, but we want to confirm)
How do you organise showing schools or ABs their ECT records? Do you do anything for academic year or cohort?
How are you using the API and will there be an impact on what data you can get for ECTs once the AB portal is decommissioned?

**Comment by gracecbrennan** [comment]
Chat with Colin/Tejas on who should be pulling these lines together

**Comment by claire-hughez** [comment]
Comms have gone out to ECTMAN and Mosaic to have conversations on how to manage the relationship with DfE as CPD take over AB portal. We need to agree on

a) Messaging of integration
b) Stance on our relationship with them
c) Any needs we require of them for the future we may want to communicate
d) Limit on updates and changes we want to communicate and create a few lines on what the MVP looks like

**Comment by gracecbrennan** [comment]
Session happening today

**Comment by kas-madrigal** [comment]
https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/doc2.aspx?sourcedoc=%7Ba4bca019-cb77-464a-a410-9d25b245405a%7D&action=edit&wdPid=4210b03

**Comment by claire-hughez** [comment]
Update yesterday, next steps to reengage in December. Chatting to Mosaic tomorrow.
