### ISSUE TITLE
Work out requirements for initial registration of ECTs and mentors for schools and create a new service rules document to contain them

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#62]
# **Why?**
To prepare for building the registration for ECTs and mentors, we need to confirm the new service rules for how these journeys will work.

# **What?**
New service rules document for ECT and mentor registration journeys.

# **Helpful links or other information**
#61 #4

**Comment by gracecbrennan** [comment]
Emily has started going through Service rules to start writing up new version for school registration elements.

**Comment by gracecbrennan** [comment]
Updated rules need writing up and running past Claire.

**Comment by mason-emily** [comment]
https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/ECF%202.0/Test%20and%20prep/Analysis/ECF%202.0%20New%20service%20rules%20-%20Copy.docx?d=w12ab8dee2d1248c380bf0bf12b04c02e&csf=1&web=1&e=TiDLvj

**Comment by gracecbrennan** [comment]
Service rules updated and ticket to be closed
