### ISSUE TITLE
When asking schools for certain information, specify what we're doing with it and why we need it

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#627]
## Why?
In user research, schools sometimes didn't understand why we were gathering certain information. They weren't sure where they needed to register first, or if what they send to DFE gets passed onto ABs, LPs and DPs.

Given how important getting some of the information right in the flow is to register an early career teacher, we should specify why we're collecting it.

## What?
I've specified below roughly what I think the reasons are for collecting the information. There needs to be a judgement call on what ones we want to surface. From UR, we might wanna surface why we're capturing those datapoints.

TRN, date of birth, NINO - To help us find their official teaching record to check they're eligible to undertake ECF training

Corrected name - so lead providers and delivery partners can communicate correctly with that ECT and so lead providers can sign them up for learning platforms

Email address - so the ECT can be emailed a privacy policy to consent to their data being shared and so lead providers and delivery partners can communicate with them about their training

Start school date - so we can work out when they'll be eligible to start training, what organisations they might be working with and  how they'll be funded?

Appropriate body - so we can double-check with the appropriate body that both the school and AB has registered them? to pass on to ABs that the school wants to work with them? we should specify we're passing on the ECT's personal details to them though, at least in ECF1. I think we should have a go at this roughly because it will need to be defined better later. _Need to be cautious about it giving the impression that ABs will definitely follow up based on this?_ 

Training programme - So we know how much funding the school should receive and if they require training with a LP and DP

Lead provider - So we can tell lead providers the school wants to work with them and they can reach out to sort the training

DP - same as above? But we might not be keeping so let's clarify there.

I don't think we need to show reasoning for all of these, but where we can and it's useful, we should. **Particularly for the organisation roles.** Email address might be important too.

**Comment by robthompson16** [comment]
I've started a board here: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

**Comment by gracecbrennan** [comment]
will review as a team early this week

**Comment by robthompson16** [comment]
Content agreed with Claire. Jas to add to prototype

**Comment by JSJohal** [comment]
Updating in prototype today

**Comment by JSJohal** [comment]
Updated this [version of the prototype](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/school/setup-scenario-1) (p: ecf2)
