### ISSUE TITLE
Remove mentor question from 'add ECT' flow

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#631]
## Why?

We've tested the 'add ECT' flow with the 'who is mentoring' question in both rounds. We've decided to remove it from the 'add ECT' flow and test with the mentor as a separate action to complete after adding an ECT.

## What?

- Remove mentor question from add ECT flow
- Also ensure it is removed from the check your answers page
- Ensure the journey connects to the mentor action following adding an ECT

**Comment by JSJohal** [comment]
Removed the mentor question from the add ECT journey in the [prototype](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v4/school/setup-scenario-1) (password: ecf2)

Also removed from the check your answers page.

The content on the confirmation button and how it links into adding a mentor is being reviewed separately - but flow should be as we want it now.

**Comment by claire-hughez** [comment]
Looks great to me. I don't think this needs a follow up dev ticket.
