### ISSUE TITLE
Find research and insights on transfers

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#634]
## Why?
We want to find out about what existing research and insights we have on transfers.

This is when an ECT has moved schools and the new school goes to register them.

Screenshots of the existing transfer journey in ECF1, historic UR or analysis would all be really helpful to inform this. 

## What?
- Compile insights together
- Make sure they're ready for the 14th, so we can kick off together in person! :) 

## Out of scope
We're most interested in transfers in.

This is the scenario when:
- School 1 has registered an ECT Bob
- Bob moves to School 2 partway through his training
- School 2 goes to register Bob
- This triggers currently the transfer journey, where School 2 can report he has moved to their school to continue his training and induction

Currently, we do not want to focus on when schools report someone is leaving. This could be when a school tells us Bob is moving to another school or when he's taking a break or leaving teaching altogether. If you find insights on this, it would be great to save for later, but it's not the focus of this epic or ticket.

**Comment by claire-hughez** [comment]
Ticket up next steps

**Comment by gracecbrennan** [comment]
Three more tickets have been made as next steps
