### ISSUE TITLE
Work out the tricky induction periods we need to migrate from the TRS

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#663]
## What?
 Work out the tricky induction periods we need to migrate from the TRS. Connected to https://github.com/DFE-Digital/register-early-career-teachers/issues/577

**Comment by kas-madrigal** [comment]
@joe-harrison-dfe is this blocked?

**Comment by gracecbrennan** [comment]
This is an old ticket that has been covered in the 'analyse bad data'
