### ISSUE TITLE
Create term validation lofi screens to test on UR round 2

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#664]
## Why?
Preparing screens to present to ABs to check if the way we want to record terms is
a) usable
b) makes sense in the way they track time

**Comment by kas-madrigal** [comment]
@peteryates @edujackedu This can be a staging screen instead of lofi designs, but I don't want to overwhelm you, let me know what your capacity is this week and we can adjust this ticket as needed.

**Comment by kas-madrigal** [comment]
@peteryates I saw were were already asking for terms (without decimals) on the happy paths, do we want to just edit that and see how the respond or do we want to create some figma screens? Both are really quick, I don't mind doing high res or low res stuff for this. @RoseAsaf let's discuss what will be better for UR testing depending on the type we are going to do

**Comment by claire-hughez** [comment]
![Image](https://github.com/user-attachments/assets/42c0e529-5c7b-444a-862f-bf0273dc7e2f)

**Comment by claire-hughez** [comment]
Decided not to test multiple different kinds of screens.
