### ISSUE TITLE
Finalise data relationship between CPD and TRS consoles

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#666]
## Why?
Define admin console rules for CPD, and a set of rules which dictate when updates should / shouldn't be possible in CPD or TRS console (including exemption rules). 

## Helpful links or other information
https://educationgovuk-my.sharepoint.com/:x:/r/personal/kas_madrigal_education_gov_uk/Documents/Admin%20console%20data%20considerations.xlsx?d=w0bf2a240d8334f328a8013bd88cc81db&csf=1&web=1&e=mfBiq1 

https://educationgovuk.sharepoint.com/:x:/r/sites/TRATransformationTeamDocs/Shared%20Documents/General/TRS%20Products/Induction%20Data%20Migration/Induction%20events.xlsx?d=w027ec7affa99439d8c23ab05b87b19a3&csf=1&web=1&e=46JMGj

**Comment by joe-harrison-dfe** [comment]
Notes from Emily P:

- None - editable by TRS & CPD
- Required to complete - Editable by TRS & CPD

Both editable by both TRS & CPD but only editable by TRS in the following scenarios:
- Updating induction status to Exempt
- Updating historic inductions 

- Exempt - editable only by TRS
- In progress - editable by both TRS & CPD

For in progress, we can define a rule around 'allowed' status transitions here. Think the only valid status update via TRS here is In Progress -> Exempt. We're planning on creating records for all "in flight" inductions in CPD. So if someone approached us with evidence they'd passed their induction, but they hadn't, we'd need to make sure this was **only** done via CPD, so we could close their record down.

- Passed - editable by both TRS & CPD but time bound?
- Fail - editable by both TRS & CPD but time bound?

There are a couple of scenarios where updating a Pass/Fail status might require an induction to continue:
- AB mistakenly recorded an outcome and wants to hit the "undo" button - we'd need to update the induction in CPD in order for the induction to continue and the actual outcome to be recorded at the right time.
- An ECT lodges a complaint against a Fail outcome, and there is a decision to overturn and award an extension instead. We'd need to update the induction in CPD with the extension, and allow an outcome to be recorded at the end of the extension. Should be a rare event though!

Both of the above should happen quite soon after an outcome is recorded (Think appeals need to be lodged within 30 days of the outcome, but the appeal outcome may take a little longer) so it feels like we could set some sensible time restrictions, where anything outside of this must be handled manually.

- Passed in Wales - editable only by TRS
- Failed in Wales - editable only by TRS

**Comment by peteryates** [comment]
When we say "editable by both TRS and CPD", given that we will only be storing each value once so there's no room for confusion over source of truth, I assume that means we'll just send changes directly to TRS via the API without recording anything in the CPD database?

Any form of two way sync will be painful.

**Comment by kas-madrigal** [comment]
Lea's summary call - 

We successfully aligned on TRS vs CPD involvement with induction data, and therefore reached an agreement on what is editable in each console:

CPD can modify the following information about Induction data in their console: Passed, Failed, In Progress, Required to Complete
TRS can modify the following information about Induction data in their console: Exempt, Failed in Wales, None
When an Induction status is In Progress, all the induction steps are managed  by CPD - providing the teacher is stored in CPD and within their retention period - until it changes to Failed or Completed, at which point it goes back to TRS.
Edge cases to resolve with policy input:
How does TRS communicate to CPD when an individual no longer has QTS?
If somebody get exemption after they started induction, what does TRS do with the status and where does that status get set? how does that flow to CPD?
when an AB enters an incorrent status of Passed or Failed, they can make a request to CPD team who can set it back to In Progress via CPD console. The API would allow the status to go back one level, unless it's been marked as exempt.
If there is an appeal on a Failed status and it is successful, the staus should change from Failed to Passed, who gets told first and then needs to update the other team?

**Comment by gracecbrennan** [comment]
@kas-madrigal is going to make a ticket to turn this into service rules

**Comment by claire-hughez** [comment]
Meeting on Friday, any other feedback to be gathered from our team or TRA before this

**Comment by claire-hughez** [comment]
Analysis here: https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7BF1E89E56-02EE-4864-82A6-7BC2E9636E8B%7D&file=How%20to%20handle%20data%20updates%20between%20TRS%20and%20the%20new%20CPD%20induction%20service.docx&nav=eyJjIjoyOTI3MDQ0Njl9&action=default&mobileredirect=true

**Comment by gracecbrennan** [comment]
Claire has come back with comments on the document. We need to focus on getting this agreed. 

@emily-prudence-dfe could have a look that would be helpful
