### ISSUE TITLE
Service rules for user flows in admin console

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#667]
## Why?
Going line by line on this doc to map out user actions in lofi screens + business rules for admin console

**Comment by kas-madrigal** [comment]
started, need to check with Pete and Joe

**Comment by gracecbrennan** [comment]
This has been deprioritised this week but will pick back up when Kas has availability.

**Comment by gracecbrennan** [comment]
This is going to part of the admin console epic

**Comment by gracecbrennan** [comment]
This is going to be moved to done as we're covering as part of the content eepic
