### ISSUE TITLE
Mapping DQT and DFE Sign-in data to understand shared fields

### ISSUE THREAD

**Issue by joe-harrison-dfe** [DFE-Digital/register-early-career-teachers#669]
## Why?
Identify shared fields between DQT and DfE Sign-in to determine if the DfE Sign-in ID matches the organisation ID held on DQT

## What?
- Speak to James Gunn to see if we can get the CSV upload from DQT to DfE Sign-in to check for any shared fields between the two databases for our matching purposes

**Comment by joe-harrison-dfe** [comment]
Speaking to James Gunn on the 13th for this.

**Comment by joe-harrison-dfe** [comment]
James Gunn DSI notes:
- Current AB portal uses ancient version of DSI ID 
- DSI have a mapping from legacy IDs to new ones, they have API that we call internally that goes from new to old ID.
- If we gave list of old IDs to DSI they could return a mapping to new IDs
- Other way we could do it would be via LA code or URN but might be messy

Next Steps:
- speak to Jared Marsh in first instance to get the mapping table to use for our old IDs

**Comment by joe-harrison-dfe** [comment]
Sent email to Jared - waiting on response

**Comment by joe-harrison-dfe** [comment]
Spoken to Jared and submitted a request through service desk. He is pulling together a list of all the Organisation identifiers (ID, Legacy ID, URN, UKPRN, etc.) in the Prod AB policy and how they differ across environments.

**Comment by gracecbrennan** [comment]
Waiting on response from Service Desk

**Comment by gracecbrennan** [comment]
Joe is going to write up findings

**Comment by gracecbrennan** [comment]
Still needs to write up what came through friday avro

**Comment by joe-harrison-dfe** [comment]
The team at Dfe Sign-In sent over a sheet which gives a breakdown of establishments in the AB production data by all the available identifiers they hold. I have looked through the sheet and created a mapping table to link each organisation name against both the legacy ID and the modern DsI ID. We can use this table to match-up data received from DfE Sign-In to our own list of legacy IDs to make sure we are linking users with their correct ABs.

The mapping table is attached to this table and can be found under the ID Mapping Table sheet in the file. As expected, not all organisations in the list have a URN, Establishment Number or UKPRN and so we will need to use IDs when matching.

@peteryates Does the mapping table here help with what we were discussing a while ago on this? Can we just use this table to link up the data between DfE Sign In and CPD?

**Comment by gracecbrennan** [comment]
@joe-harrison-dfe to run through with the team tomorrow stand-up

**Comment by gracecbrennan** [comment]
This ticket can be closed for now. 

Pete is returning to DfE sign-in today and this will feed into it at a later date when we have API access
