### ISSUE TITLE
Design to 'autosave' last used programme details rather than asking users to save

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#676]
## Why?

We've created a design where we ask schools for programme details and then ask them if they want to save those details for later use. While this tested OK, some users didn't immediately understand the ask. After considering how we could change this page, we've decided we want to test a version where we remove this page and remove asking users if they want to save their programme details for future use. Instead of this, we want to test autosaving this information and asking users if they wish to reuse their last used details when they return to add a new ECT.

## What?
- Remove the 'save programme details' page
- Update the content on 'do you want to use these details' page so it instead reflects that these are the details you used last time
- Think about scenarios such as rollover from previous years and transfers(?)
- Update [design history post](https://teacher-cpd.design-history.education.gov.uk/ecf-v2/saving-default-choices/) relating to programme details

**Comment by gracecbrennan** [comment]
just picked up yesterday

**Comment by gracecbrennan** [comment]
Jas has made a start and will need some time with Rob on this

**Comment by JSJohal** [comment]
Screenshot of what we've come up with for this.

This is for when we present previously used programme details when adding an ECT - this would be in replacement of the AB / programme type / DP / LP questions. The idea would be a user could see what they used last time and choose to use those details again, or they could say no and provide different details.

Be good to get thoughts @claire-hughez @mason-emily @TobyRet @tonyheadford @ltello 

![Image](https://github.com/user-attachments/assets/6a5b0996-c87b-4155-9127-d655becab738)

**Comment by mason-emily** [comment]
Looks great to me!

**Comment by gracecbrennan** [comment]
@claire-hughez anymore thoughts before we close this one?

**Comment by claire-hughez** [comment]
looks great!

**Comment by JSJohal** [comment]
[Prototype link (p: ecf2)
](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/school/will-you-use-defaults)

[Updated mapping on Lucid](https://lucid.app/lucidspark/ae6e1ba4-53c3-4683-a7aa-1587a7ecab29/edit?view_items=HtBwB9euKz_C&invitationId=inv_95c1686d-e3cf-4d15-a750-f966bc1587e1)

[Design history post updated, PR to be reviewed @claire-hughez pls](https://github.com/DFE-Digital/teacher-cpd-design-history/pull/352/files)

**Comment by claire-hughez** [comment]
Reviewed PR. looks good, left 1 suggestion.

**Comment by JSJohal** [comment]
Merged and will move to done :)
