### ISSUE TITLE
Review and edit programme choices displayed when adding a new mentor

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#683]
## Why?
Currently, we've designed a page which plays users back the schools default programme choices (LP/DP) when adding a mentor. This is so users can select yes or no to using the same details for when they're adding a mentor. However, we want to change this so the user is presented the option of saying yes or no here instead to the programme choices that are being used for the ECT they will be mentoring.

## What?
- Change the page so it displays the ECTs LP & DP and ask if the mentor that is mentoring will be using the same choices

**Comment by gracecbrennan** [comment]
Just picked up

**Comment by gracecbrennan** [comment]
will catch up with Rob on this later

**Comment by claire-hughez** [comment]
Meeting today.

**Comment by robthompson16** [comment]
Content agreed with Claire. There is a question mark over whether we need to include a row in the table on programme type which we'll clarify with Nathan in our next catch up

**Comment by JSJohal** [comment]
Updating in prototype today

**Comment by JSJohal** [comment]
Updated this [version of the prototype](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/school/setup-scenario-1) (p: ecf2)
