### ISSUE TITLE
School user is unable to match an ECT's TRN with a TRS record

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#685]
## Description
This story delivers the functionality to check whether the TRN entered by the user is a TRN that exists in the TRS. TRN is needed for any TRS matching, so there is no point in asking for further details (National Insurance number) from the user if the TRN cannot be matched when trying to register an ECT.

If the TRN cannot be matched in TRS, there will be a 'dead end' page in the 'Add ECT' journey to signpost the user to relevant next steps or to start the journey again.

## User story

**As** a school user
**I need** to be told if the TRN I'm using to register an ECT doesn't exist in the TRS 
**So that** I can understand the appropriate next steps for resolving this to be able to register the ECT

## Prototype, screenshots & content
[Link to prototype of the relevant screen](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-ect/trn-not-found)

Screenshots of relevant screens:
![image](https://github.com/user-attachments/assets/2cbe4f51-61b3-4331-a3c9-a516adbd9f5a)

Content should be as per the prototype.
URL should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

## Acceptance criteria

- [ ] 1. When user submits a valid TRN and date of birth on the <ins>'Find an ECT'</ins> page, if there is no match with a TRS record for the TRN entered (regardless of if DoB matches too), user will be navigated to the <ins>'We're unable to match the ECT with the details you provided'</ins> page. Note, existing validation and error messages for TRN and DoB should not change.
- [ ] 2. On the <ins>'We're unable to match the ECT with the details you provided'</ins> page:
  - [ ] 2a. The text 'reviewing their teacher record' will be a hyperlink to https://check-a-teachers-record.education.gov.uk/check-records/sign-in as per the prototype. This link should navigate the user within the same tab.
  - [ ] 2b. The text 'Find a lost TRN service' will be a hyperlink to https://find-a-lost-trn.education.gov.uk/start as per the prototype. This link should navigate the user within the same tab.
  - [ ] 2c. There will be a green 'Try again' button which navigates the user to the 'Find an ECT' page where the fields should be reset to blank
- [ ] 3. There will be no 'Back' link on the <ins>'We're unable to match the ECT with the details you provided'</ins> page.

## Technical notes
https://teacher-qualifications-api.education.gov.uk/swagger/index.html

## Linked tickets
#473

**Comment by claire-hughez** [comment]
Just to be really clear, we should not play back the name or have a successful match unless either:
- both TRN and Date of birth match
- both TRN and national insurance number match

It's just if we can't find the TRN at all in the TRS, we can tell the user immediately the record cannot be found.

**Comment by claire-hughez** [comment]
updated screenshot

**Comment by claire-hughez** [comment]
almost done!

**Comment by gracecbrennan** [comment]
lorenzo and emily to review

**Comment by TobyRet** [comment]
Holding fire on merging this until @ltello has had a chance to refactor the Register ECT journey. 
Plan is to rebase onto his changes once he has merged ...

**Comment by mason-emily** [comment]
Looks great!

Couple points:
- The content on the 'We're unable to match the ECT with the details you provided' page needs to be updated slightly to match the prototype - H1 needs updating and the first line below that needs removing
- https://find-a-lost-trn.education.gov.uk/start link isn't working

**Comment by gracecbrennan** [comment]
Toby will action review points. 

Merging will be blocked until Lorenzo's refactoring work is complete

**Comment by TobyRet** [comment]
Copy corrected on 'teacher not found' page. 

![Image](https://github.com/user-attachments/assets/a147eac6-db09-4299-9133-224899012d11)

**Comment by gracecbrennan** [comment]
Content updates have been made. 

Just waiting for refactoring ticket to finish and might need to do some small edits to bring it in line
