### ISSUE TITLE
ECT being registered has an induction status of 'exempt'

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#688]
## Description
This story delivers the functionality to check for an induction status of 'exempt' associated with the ECT's TRS record when we find a match. ECTs who have an induction status of exempt should not be registered in the service as they are exempt from completing induction, so we end the registration journey in this case.

## User story

**As** a school user
**I need** to be told if the ECT I'm registering is exempt from induction
**So that** I know why I cannot register the ECT

## Prototype, screenshots & content
[Prototype link to the 'You cannot register [ECT name]' page](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-ect/induction-status-exempt)

Screenshots of relevant screens for if the ECT ****does have an induction status of exempt** on their TRS record:
![image](https://github.com/user-attachments/assets/6d99c0eb-f4dc-4e36-8287-94bd31331c9e)

Content should be as per the prototype.
URL should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

## Acceptance criteria

- [x] 1. When user submits a valid TRN and date of birth on the <ins>'Find an ECT'</ins> page and a match is found for the ECT's TRS record using both TRN and date of birth:
    - [x] 1a. If the ECT's record **has** an induction status of 'exempt', user will be navigated to the <ins>'You cannot register [ECT name]'</ins> page. 
    - [x] 1b. If the ECT's record **does not have** an induction status of 'exempt', user will continue to be navigated to the <ins>'Check if this is your ECT'</ins> page.
- [x] 2. On the <ins>'You cannot register [ECT name]'</ins> page:
    - [x] 2a. H1 text will include the ECT's first and last name from their TRS record 
    - [x] 2b. Content will be as per the prototype - note, this is slightly different to #687.
    - [x] 2c. There will be a link to 'Register another ECT' which navigates the user to the <ins>'Find an ECT'<ins> page where the fields should be reset to blank.
    - [x] 2d. There will be no 'Back' link on the <ins>'You cannot register [ECT name]'</ins> page.
- [x] 3. AC 1&2 above will be replicated for the <ins>'We cannot find your ECT's details'</ins> page when a TRS match is found using TRN and NINO.

## Technical notes
https://teacher-qualifications-api.education.gov.uk/swagger/index.html

AB portal have also done some relevant work so worth speaking to Pete.

## Linked tickets
Dependent on #512 
Very similar to #687 
Linked to #473 #689

**Comment by claire-hughez** [comment]
Just need to size

**Comment by gracecbrennan** [comment]
Just need dev review on this now 


Small content tweak to make on this ticket.

**Comment by claire-hughez** [comment]
I've prod reviewed. Toby has updated the content from Tony's suggestion and all the AC is met. 🎊
