### ISSUE TITLE
Design asking schools if an ECT is part-time

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#709]
## Why?
Understanding if an ECt is part time will help us know if they might be having an extended induction or extended training. It's useful information to pass on to lead providers.

We're not sure we'll include this yet, but we think it's worth considering as it often impacts schedules.

## What?
- Ask a school user if an ECT is part-time or full-time
- Consider placement of this question: does it link to any other questions such as start date, could it be wrapped up into one?
- Update routes in prototype to add question in, including adding to check your answers page
- Validation and URL

## Out of scope
Asking if training is full time or part time

## Helpful links or other information
https://lucid.app/lucidspark/4324b079-3c21-496d-947c-04f04c3ef18e/edit?view_items=nq1EvaN2tWgs&invitationId=inv_20e35c6f-9dd3-4eb4-8194-fe608bcd2bda

**Comment by aabdi18** [comment]
designed low -fi  versions and decided how to proceed with Jas - will draw up a hi-fi mock up today for content review

**Comment by aabdi18** [comment]
![Image](https://github.com/user-attachments/assets/6535f09f-7e36-4756-81c0-2403ffa73216)
mocked up 2 options in [this frame](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=CxrwY9It9X-b&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b) ready for prod and content review

**Comment by claire-hughez** [comment]
Others to review

**Comment by gracecbrennan** [comment]
This has been shared on main slack channel for review.

**Comment by aabdi18** [comment]
putting better option of the 2 into the prototype and tweaking content with Rob

**Comment by aabdi18** [comment]
Merged into prototype- Jas updated check answers page to match, Rob is happy with the content ![Image](https://github.com/user-attachments/assets/049b068f-9897-4f1f-9698-adf5fc30975a)

**Comment by JSJohal** [comment]
Updated screenshots with content changes
![Image](https://github.com/user-attachments/assets/0af5abcd-0c29-478a-8e2a-eacb92b127cc)
![Image](https://github.com/user-attachments/assets/aa6daec4-aee9-46e1-ae28-4ced6b266f53)
[Prototype link (p: ecf2)](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/school/part-time)

**Comment by gracecbrennan** [comment]
@claire-hughez to review and confirm
