### ISSUE TITLE
Ascertain need for UR to fill knowledge gaps around transfers

### ISSUE THREAD

**Issue by rosalie-education** [DFE-Digital/register-early-career-teachers#714]
## Why?

As part of [this ticket](https://github.com/DFE-Digital/register-early-career-teachers/issues/634) we uncovered some research and analysis on transfers (when an ECT has moved schools and the new school goes to register them) undertaken by previous teams in CPD. On 14 November, we met as a team to look at some of this past UR/analysis together. We need to decide whether we know enough about transfers to proceed for the moment, or whether there is any need for user research to fill remaining knowledge gaps.

## What?

- [x] Do a final search for historical UR 
- [ ] Meet as a team to discuss and agree on the need for user research 

## Helpful links or other information
[lucid board on transfers](https://lucid.app/lucidspark/6a8a4633-b33d-4417-9a13-d93429fe223b/edit?invitationId=inv_80557b81-aebe-4aa6-9126-1d90bb0d72a9&page=0_0#)

**Comment by gracecbrennan** [comment]
Rosie is going to do a final search of UR. 

Kerry, Awo and Rosie meeting later this morning to discuss next steps.

**Comment by claire-hughez** [comment]
Kerry has made follow up tickets. 1 more day to pull UR together for Rosie. As a team, make a decision on if we want exploratory UR.

**Comment by gracecbrennan** [comment]
This is going to be on pause until we've got further on transfer discussions will return to this

**Comment by gracecbrennan** [comment]
Rosie to schedule call to discuss options for UR ahead of testing

**Comment by rosalie-education** [comment]
Session booked in for 11am today - will update with meeting outcomes

**Comment by gracecbrennan** [comment]
Decided on one more usability round before Christmas

This will take place w/c 9th Dec
