### ISSUE TITLE
Design for blocking registration when an ECT or mentor has a prohibition from teaching alert

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#715]
## Why?
Individuals who are prohibited from teaching are not eligible for induction or funded training. There is an alert category in TRS that will flag these individuals. 

If a school tries to register an ECT of mentor with a prohibition from teaching alert, we will block the registration journey. We will not surface information about the fact that the individual has an alert but we will let the user know the individual cannot be registered.

## What?
- Design for blocking the journey when an ECT or mentor has a prohibition alert (hopefully reusable across mentors/ECTs)
- We don't want to be specific as to the individual being prohibited or even having an alert
- We don't need to give any additional context - it should just block the user from continuing - in theory, this page should never be seen
- This needs to cover both ECTs and mentors

**Comment by JSJohal** [comment]
> We don't want to be specific as to the individual being prohibited or even having an alert
We don't need to give any additional context - it should just block the user from continuing - in theory, this page should never be seen

Screenshot attached below, good to get thoughts @claire-hughez @mason-emily 

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/a03fccef-86fe-4205-8047-82a130de6b2e">

**Comment by claire-hughez** [comment]
looks great!

**Comment by mason-emily** [comment]
Looks great! Do we need to tweak slightly to make it work for mentors too since it's not necessarily about training for them?

**Comment by gracecbrennan** [comment]
@robthompson16 to take a look

**Comment by robthompson16** [comment]
How about: 

Our records show that John Smith cannot be registered for training or mentoring.

**Comment by claire-hughez** [comment]
We're good with this line.

**Comment by JSJohal** [comment]
[Prototype link (p: ecf2)](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/other-pages/add-ect/cant-register)

[Lucid board with mapping](https://lucid.app/lucidspark/ae6e1ba4-53c3-4683-a7aa-1587a7ecab29/edit?view_items=ffCw3vgw_s8~&invitationId=inv_95c1686d-e3cf-4d15-a750-f966bc1587e1)
