### ISSUE TITLE
Rd 2 AB UR Recruitment

### ISSUE THREAD

**Issue by RoseAsaf** [DFE-Digital/register-early-career-teachers#745]
We need to recruit participants for Rd 2 of AB UR

**Comment by gracecbrennan** [comment]
Has reached out with Colin to help get put in contact with non TSH ABs 

Then comms can go out.

**Comment by gracecbrennan** [comment]
Comms going out midday today

**Comment by gracecbrennan** [comment]
Sent out for one more TSH sign-up
