### ISSUE TITLE
Home page - heuristic improvements

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#748]
## Description

The issues are as follows, ranked by size 

### Extra Small 
- [x] Add subtexts under 'search for an ECT': 'you can search by name or TRN' 
- [x] Turn 'Claim an ECT' into primary button (green).
- [x] Make 'Search' a secondary button. (didn't do this after chatting with @JSJohal)

### Small 
- [x] Add functional 'clear filter' button

## Prototype, screenshots & content
![Image](https://github.com/user-attachments/assets/8a25b7de-2951-42ef-848f-9efce5840f67)

Content should be as per the screenshots above.
URL and validation messages should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

**Comment by kas-madrigal** [comment]
@peteryates @edujackedu I haven't added sorting or pagination to this (even thought we should add it for MVP) since I figured they were bigger tickets not completely needed for UR. If you think they are really easy to tackle I can add them to this ticket

**Comment by peteryates** [comment]
There should only be one primary action per page, so also make `Search` a secondary button?

**Comment by claire-hughez** [comment]
![Image](https://github.com/user-attachments/assets/5cc6181a-c94a-40db-ba13-085a545dfbeb)

**Comment by kas-madrigal** [comment]
> There should only be one primary action per page, so also make `Search` a secondary button?

sounds good!

**Comment by gracecbrennan** [comment]
@edujackedu to review
