### ISSUE TITLE
Change title of service

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#754]
## Description

Banner: 
Register early career teachers

Title:
Record induction as an appropriate body

## Reasoning

We can't have 2 titles separated by a` : ` according to best practice. Hence if we decide to use 'Register early career teachers as an appropriate body' we are duplicating the name that is in the banner of the page as well which is 'register early career teachers'. The combined name was agreed to be an interesting middle point, hence using 'record induction as an appropriate body' is the best practice solution to it. 

![Image](https://github.com/user-attachments/assets/2b01679b-87f1-4ff6-b739-9e31b043104f)
![Image](https://github.com/user-attachments/assets/fc70001c-7de4-4c64-a413-7a5697982c9c)

#755

**Comment by kas-madrigal** [comment]
@peteryates @edujackedu @joe-harrison-dfe @RoseAsaf @emily-prudence-dfe 

Me and Rose just had a chat about this but if anyone has any other thoughts just say

**Comment by kas-madrigal** [comment]
#755 - Rose pull request to make change

**Comment by peteryates** [comment]
@RoseAsaf's suggestion gets a ➕ from me!
