### ISSUE TITLE
Find a mentor to add for an ECT at your school using TRN and DoB

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#759]
## Description
This story will deliver the functionality to find a mentor's record in the TRS that matches a TRN and date of birth entered by a school user. It will also involve blocking the journey if a record can't be matched, or if there is a match, playing back the name associated with the TRS record so that the user can check the right person has been found.

## User story

**As** school user
**I need** to find a mentor's record in TRS
**So that** I can continue the journey of registering the right mentor and assigning them to an ECT at my school

## Prototype, screenshots & content
[Prototype mentor journey
](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/school/mentor/what-youll-need)
[Prototype for no match on TRN](https://ecf2-prototy-v4-k7mv50fp1jl0ue.herokuapp.com/v4/other-pages/add-mentor/not-found)

**Screenshots of relevant screens:**
Note, the 'corrected name' question is in the prototype but not in scope for this ticket - will be added later.

![Image](https://github.com/user-attachments/assets/132ef644-85e5-4b29-bcfe-adfae81064a8)

Content should be as per the prototype.
URLs and validation messages should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

## Acceptance criteria

- [x] 1. When user clicks 'Continue' on the <ins>'What you'll need to add a new mentor for [ECT name]'</ins> page, they will be navigated to the <ins>'Find a mentor'</ins> page.
- [x] 2. On the <ins>'Find a mentor'</ins> page:
    - [x] 2a. User can enter a TRN and date of birth. 
    - [x] 2b. Validation and error messages for TRN and date of birth will be the same as for the ECT fields as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).
    - [x] 2c. There will be a 'back' link on the page which takes the user back to the <ins>'What you'll need to add a new mentor for [ECT name]'</ins> page.
    - [x] 2d. Test data for TRN and date of birth should be provided on the 'Find a mentor' page in the same way as in the ECT journey staging environment.
- [x] 3. When user clicks 'Continue' on the <ins>'Find a mentor'</ins> page, the TRN and DoB entered will be used to call the TRS API to check for a match with a teacher record. Note, this page has been built for finding an ECT (#473).
    - [x] 3a. If the TRN does not match any TRS record, user will be navigated to the <ins>'We're unable to match the mentor with the TRN you provided'</ins> page.
    - [x] 3b. If the TRN matches a TRS record but the date of birth does not, user will not be able to continue past the <ins>'Find a mentor'</ins> page. Note, we will update the journey for when DoB doesn't match in a separate ticket (#764).
    - [x] 3c. If there is a match with a TRS record for both TRN and date of birth, user will be navigated to the <ins>'Check mentor details'</ins> page.
- [x] 4. On the <ins>'We're unable to match the mentor with the TRN you provided'</ins> page:
    - [x] 4a. The text 'reviewing their teacher record' will be a hyperlink to https://check-a-teachers-record.education.gov.uk/check-records/sign-in as per the prototype. This link should navigate the user within the same tab.
    - [x] 4b. The text 'Find a lost TRN service' will be a hyperlink to https://find-a-lost-trn.education.gov.uk/start as per the prototype. This link should navigate the user within the same tab.
    - [x] 4c. There will be a green 'Try again' button which navigates the user to the 'Find an ECT' page where the fields should be reset to blank
    - [x] 4d. There will be no 'Back' link on the <ins>'We're unable to match the ECT with the details you provided'</ins> page.
- [ ] 5. On the <ins>'Check mentor details'</ins> page (when there is a TRS match):
    - [x] 5a. User will be shown the first and last name associated with the matched TRS record, as well as the TRN and date of birth. Note, there is also a middle name in TRS which we have agreed not to show. Do not show the National Insurance Number.
    - [x] 5b. At the bottom of the 'Check mentor details' page, there will be a link to go back and 'check details' which will navigate the user back to the 'Find an ECT' page. If user goes back via the 'check details' link, the fields on the 'Find an ECT' page will be reset to blank and the user can enter new details to find a different person's TRS record.
    - [ ] 5c. Update the 'Check ECT details' view in the register ECT journey to not display the National Insurance Number and be consistent with this one.

## Technical notes
A very similar flow has been built for the ECT journey.

For the test data, we can use the same data as for ECTs.

## Linked tickets
#764 

Equivalent in the ECT journey #473

**Comment by claire-hughez** [comment]
When I enter letters in the TRN field, it's blocking me. We agreed to include letters or any input to the TRN field. Bizarrely it lets me put a lower case e, but nothing else haha. Should I create a separate bug ticket to fix this?

**Comment by claire-hughez** [comment]
It looks good, but I'm struggling to review because of potentially another problem.

On AC 3a, instead of the page to say they can't find the TRN, I get to the page that states 'Sorry there's a problem with the service.' Same when I try AC3b, like TRN exists but DOB doesn't match. This blocks me from reviewing the other AC points for now. I've ticked off what works for me.

**Comment by claire-hughez** [comment]
On the check a teacher's record, we link to a sign in page that redirects immediately which I think could be confusing. In both the ECT and mentor pages, I think we should link to https://www.gov.uk/guidance/check-a-teachers-record instead. Will check with designers in standup.

**Comment by mason-emily** [comment]
TRN validation was on me to create a separate ticket - it's on my list to add today!
