### ISSUE TITLE
Assign a mentor to an ECT when there are mentors currently active at the school

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#777]
## Description
This story will deliver functionality for users to assign a mentor to an ECT when there are mentors already active at the school. In this case, users will be able to assign an existing active mentor or register a new mentor.

## User story

**As** school user
**I need** to assign a mentor for an ECT
**So that**  the mentor is reported to DfE so that they can gain access to the ECT's materials and in some cases access to mentor training

## Prototype, screenshots & content
[Link to prototype ](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/school/home/ects) p: ecf2
[Link to confirmation page in prototype] (https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/school/mentor/assigned)

**Screenshots of relevant screens:**
![image](https://github.com/user-attachments/assets/4bd4afd1-6e6f-4b08-8581-6cabebe28884)

Content should be as per the prototype above.
URL and validation messages should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

## Acceptance criteria

- [x] 1. On the <ins>'View list of ECTs'</ins> page, when user clicks on the link to 'assign a mentor or register a new one':
    - [x] 1a. If there are **no** mentors currently active at the school, user will be navigated to the <ins>'What you'll need to add a new mentor for [ECT name]'</ins> page where they can continue the journey for registering an ECT as per #758. 
    - [x] 1b. If there **are** mentors currently active at the school, user will be navigated to the <ins>'Who will mentor [ECT name?'</ins> page.
- [ ] 2. On the <ins>'Who will mentor [ECT name?'</ins> page:
    - [x] 2a. User will be shown radio options for all currently active mentors at the school, or the option to 'Register a new mentor'. 
    - [ ] 2b. User must select an option to continue or error messaged will be shown as per[ this doc ](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).
    - [x] 2c. There will be a 'back' link on the page which takes the user back to the <ins>'View list of ECTs'</ins> page.
    - [x] 2d. If user selects the option to 'Register a new mentor', they will be navigated to the <ins>'What you'll need to add a new mentor for [ECT name]'</ins> page where they can continue the journey for registering an ECT as per #758.
    - [x] 2e. If user selects the option of an existing mentor at the school, the selected mentor will be assigned to the ECT and the user will be navigated to the Confirmation page.
- [x] 3. On the Confirmation page:
    - [x] 3a. User will be shown the success message including the mentor's name and their ECT's name as per the prototype.
    - [x] 3b. There will be a 'Back to your ECTs' link which navigates the user to the <ins>'View list of ECTs'</ins> page. 
    - [x] 3c. There will be no 'back' link on the page.

## Technical notes
We already have mentor seed data.

## Linked tickets
#758

**Comment by gracecbrennan** [comment]
Still need today to complete

**Comment by gracecbrennan** [comment]
Ongoing

**Comment by gracecbrennan** [comment]
Nearly complete pending review of linked ticket

**Comment by claire-hughez** [comment]
PR coming in a minute

**Comment by claire-hughez** [comment]
Reviewed @ltello, looks great, left some feedback in the PR for success criteria 2b, I think the wrong content has been used for the validation error.

**Comment by claire-hughez** [comment]
Looks great, thanks @ltello, ready to move to done when you are.
