### ISSUE TITLE
Design lo-fidelity mockups for happy path transferring in ECTs

### ISSUE THREAD

**Issue by JSJohal** [DFE-Digital/register-early-career-teachers#803]
## Why?

We want to design a version of the 'add ECT' journey that accommodates ECTs that are transferring from another school. Before designing something detailed, we want to design a lo-fidelity version that can visualise what the journey could look like, and allow us to identify any potential variations or painpoints. 

## What?

- Create a mockup journey for a provider-led ECT being transferred to a school, where they will also be provider-led trained
- Design for the participant to change from the previous school training provider to use the one the new school use (which is the most common journey)

## Out of scope

- Anything to do with notifying the previous school or the previous training provider
- Unhappy paths
- Variations to the happy paths such as provider-led to school-led, or vice versa

## Helpful links or other information

Maybe some rough needs:
As a school admin, I need to understand that the registration and status of my ECTs are correct so I am reassured I've fulfilled my responsibilities
As a school admin, I need to register ECTs that are part-way through their training and continue their training so they are best supported
As a lead provider, I need to understand when ECTs are partially trained, so I know how to continue their training and the ECT can become a great teacher

**Comment by gracecbrennan** [comment]
Picked this up yesterday

**Comment by aabdi18** [comment]
done most of the journey - needs to add confirmation page and status change - on [this frame](https://lucid.app/lucidspark/6a8a4633-b33d-4417-9a13-d93429fe223b/edit?viewport_loc=14142%2C-11176%2C2703%2C1385%2C0_0&invitationId=inv_80557b81-aebe-4aa6-9126-1d90bb0d72a9)

**Comment by gracecbrennan** [comment]
Awo would like to walk through with Jas today before sharing with team

**Comment by gracecbrennan** [comment]
Jas and Claire have reviewed - going to schedule something with the team for early next week

**Comment by claire-hughez** [comment]
Will put time in today or tomorrow to look through this together.

**Comment by aabdi18** [comment]
Had really useful meeting with some of the team yesterday, will catch up with both Jas and Rob today to hash out what needs changing

**Comment by JSJohal** [comment]
Going to start putting the happy path flow we've discussed as a team into the prototype, to then work on content and changes.

**Comment by gracecbrennan** [comment]
Still a bit left on this to do so will keep working on it today

**Comment by JSJohal** [comment]
Work in progress, I've put latest thoughts onto this [board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=tdzxm6F8R8Hh&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b), but will need further thought regarding content and guidance regarding 'transfer'

**Comment by gracecbrennan** [comment]
Jas would like some feedback from Tony on this

**Comment by JSJohal** [comment]
Had some time to discuss with Tony and Claire to get feedback.
Will catchup with @robthompson16 to discuss next steps

**Comment by JSJohal** [comment]
Added content changes discussed with @robthompson16 in [prototype (p: ecf2)](https://ecf2-prototype-e3c7aba62d82.herokuapp.com/v5/school/setup-scenario-3) and on [Lucid board](https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?view_items=lMKynp47BjD0&invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b)

**Comment by gracecbrennan** [comment]
@claire-hughez to take a look ahead of tomorrow if possible

**Comment by claire-hughez** [comment]
This looks good to me. I think it's a great start to bring to testing. 

_Confirm details to move John Smith from their previous school to your school to continue their training._


There's still something that intuitively feels a bit uncomfy to me with only fiagging the move from an old school to the new on the last page. I think because if there was an issue with that content, we're telling them so late that they would have wasted quite a bit of time.

I also think in some circumstances, that person might have left that old school a loooooong time ago. They can't report leavers in ECF1 at the moment.. So they're not really moving them. They're just telling them they're starting at a new school, and at some point they were at a previous school. I dunno if that makes sense.

But let's see how it tests! :D
