### ISSUE TITLE
Write initial ECT data to DB

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#804]
## Description
This ticket is to persist the data from the 'Add an ECT' journey to the DB

At the successful end of the journey once the "Check your answers" step has been accepted we should persist the data we have collected.

Once the transfer and training parts of the journey have been tested and agreed we can add an additional tickets to handle those cases, but for now creating a `Teacher` and associating them correctly with the `School` is enough.

Note, we're not including ECT email address as part of this ticket as we first need to explore how we'll handle this data #642 

## Acceptance criteria

- [ ] 1. Create and populate a new `Teacher` record with the name and TRN details entered
- [ ] 2. Create an `ECTAtSchoolPeriod` record to associated the `Teacher` with the `School` that is being administered. This should have the appropriate `starting_on` date.

## Linked tickets
#478

**Comment by claire-hughez** [comment]
Will merge personas one, and then will clean up the PR for this. Will then get some feedback from Lorenzo.

**Comment by gracecbrennan** [comment]
Going to bring @tonyheadford in on discussion on this

**Comment by TobyRet** [comment]
I've set up a meeting with AB and ECF devs on Friday morning to discuss this PR and general approaches we may want to align on as add to the code base.

### Meeting summary

_I’ve raised a PR related to writing data to the DB in the Register ECT flow, [which has led to some interesting discussions](https://github.com/DFE-Digital/register-early-career-teachers/pull/859#discussion_r1865897901) and some bigger questions about use of wizards and how we implement the designs.

Given similar work may be happening in AB-land, Tony and I thought might be a good to take stock and have a broader discussion about the development work done so far in Register ECT and Mentors and AB. Specifically, we wondered if it may be useful to align on high-level approaches across apps —such as patterns, wizards, name-spacing, and the use of service objects, to name a few.

While we’re still in the early stages and there’s limited value in aligning on every detail just yet, but there could be value in identifying commonalities, pain points, and whether we can agree on some key principles moving forward._

**Comment by gracecbrennan** [comment]
Discussion ongoing about what we do with this.

**Comment by gracecbrennan** [comment]
Reraised a PR for this
