### ISSUE TITLE
Analyse how to manage historic data with TRA and data retention periods

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#809]
## What?

Questions to clarify 
- What is our data retention period?
- How will data become 'historic'?
- Who needs access to existing historic data?
- Where will historic data be stored?

## Helpful links or other information
- The current CPD/ECF service's retention period is 'infinite' as deleting data from ECF1 is too difficult

Quote from Phil on data retention years
> I think you should consider the holding data for longer than 6 years. My first question is will all ECTs conclude their induction programmes within 6 years? I think there will be ECTs who take longer. If they have only partially completed their induction how important is it for ABS to be able to access the CPD holds about that partially completed induction? If that data is still of value I think it should be retained for longer. From my own experience we routinely find that we have to refer to historic Induction data to respond to requests enquiries from teachers who do not believe their induction status in the DQT is correct. However, the fact we need to do that exposes flaws in historic data collection processes - it may not be relevant moving forward if there are more effective data collection processes in place.

**Comment by claire-hughez** [comment]
_I think you should consider the holding data for longer than 6 years. My first question is will all ECTs conclude their induction programmes within 6 years?_ 

In the analysis I wrote, a lot of this depends at the point in which you 'start timing' from. Phil is right this would be an issue if you started timing from the creation of the record. However, if you start timing from a 'pass or fail' outcome, then this would probably be fine. :)
