### ISSUE TITLE
Add style guide to service manual

### ISSUE THREAD

**Issue by robthompson16** [DFE-Digital/register-early-career-teachers#812]
## Why?
The team has agreed a style guide for how we use specific language in the service. The style guide is a starting point is will evolve as we build the service and the supporting policy is updated.

Some entries in the style guide will be annotated with additional comments if we expect them to change in the future due to policy decisions.

The style guide will help us ensure that we use language consistently across the service, for example how we use particular acronyms like ECT.

The style guide needs to be added to the service manual so it's easily accessible to all team members.

## What?
- Create a new page in the service manual and add the style guide content.
- Ensure the content receives a 2i review before publishing.

## Out of scope
n/a

## Helpful links or other information
Content strategy document: https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/ESJ3am3Xhp5NpRPTgolZQjIB9b3Sl2wukXbzVQ5vLs3Bww?e=nbyVCy

Service manual: https://ecf-service-manual.education.gov.uk/

Lucid board with style guide session notes: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

**Comment by claire-hughez** [comment]
Claire can talk through with Rob how to get it on.

**Comment by gracecbrennan** [comment]
Claire has chatted through how to get this on Github

**Comment by robthompson16** [comment]
Now live: https://ecf-service-manual.education.gov.uk/content-strategy/
