### ISSUE TITLE
Write descriptive 'one liners' for organisation roles

### ISSUE THREAD

**Issue by robthompson16** [DFE-Digital/register-early-career-teachers#813]
## Why?
We know users are confused by some of the terms for organisations we use in the service like appropriate body, lead provider and delivery partner.

It would be useful for the service to have some agreed descriptions we could use to describe the roles of these various entities.

## What?
Write brief descriptions, preferably a single sentence, to describe the role of the following:
- appropriate body
- lead provider
- delivery partner

## Out of scope
n/a

## Helpful links or other information
Managing training for ECTs guidance https://www.gov.uk/guidance/managing-training-for-early-career-teachers

**Comment by peteryates** [comment]
It might make sense to use these as the opening sentence/paragraph for the service rules. I started reorganising them in [this PR](https://github.com/DFE-Digital/register-early-career-teachers/pull/693/commits/1c3ec9d20e3d9da288bb3bf020532f12f6814325#diff-f5e57816f5cdb347c03dcca5e9e8f4dab60b65dd696ab9e1a9aea510e1015b2cR5).

> Appropriate bodies [assure the quality of statutory teacher induction](https://www.gov.uk/government/publications/statutory-teacher-induction-appropriate-bodies/find-an-appropriate-body#role-of-appropriate-bodies). They assure that:
>
> * relevant people know of their responsibilities for monitoring support and assessment during teacher induction, and are capable of meeting them
> * monitoring, support, assessment and guidance procedures in place are fair and appropriate
```

**Comment by robthompson16** [comment]
Started a board here to add examples we currently have in guidance and the service: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

**Comment by gracecbrennan** [comment]
This will move into review today

**Comment by robthompson16** [comment]
I've written some descriptions which are designed to be used in the service where users will already have some context. It's probably not suitable to use these lines without any additional context outside of the service. To produce these lines I first analysed descriptions we have in existing guidance, the prototype, UR materials as well as descriptions used by other organisations. You can view the board here along with the proposed descriptions: https://lucid.app/lucidspark/0fc74abe-118f-4cda-92fb-de87e4b8a36a/edit?invitationId=inv_e37a643a-8ad0-4321-9455-4e30f29ef89b&page=0_0#

**Comment by gracecbrennan** [comment]
@claire-hughez to find some time today

**Comment by claire-hughez** [comment]
This looks great to me. I wonder for delivery partners, just to differentiate them a bit further, there's something on events like we refer to in the current designs for delivery partner?

_The delivery partner is usually a teaching school hub, university or trust that organises and runs conferences, events and day-to-day training for ECTs._

There's just something to me in how they do the in-person stuff. But maybe I'm wrong.

Also, is it worth checking these with Stephen?

**Comment by robthompson16** [comment]
Good suggestion! How about this: 

Delivery partners are responsible for delivering training and events to ECTs and mentors.

I will run past Stephen too

**Comment by claire-hughez** [comment]
Looks great! Should it be 'for' instead of 'to' now it includes events?

**Comment by robthompson16** [comment]
Yes I think you're right. Makes it sound more participatory! I'll amend that

**Comment by robthompson16** [comment]
@claire-hughez from Stephen: 'As one liners, absolutely fine. I did ping the image over to a policy person and you have a positive fact-check'

**Comment by robthompson16** [comment]
Do we want to add them to the content strategy?

**Comment by gracecbrennan** [comment]
@robthompson16 to add to strategy/glossary

**Comment by robthompson16** [comment]
I've created 2 pull requests for the glossary and content strategy. I thought it made sense to reference them in both places

**Comment by gracecbrennan** [comment]
Rob to check with @peteryates before merging

**Comment by gracecbrennan** [comment]
@JSJohal to double check if these are merged.

**Comment by robthompson16** [comment]
All changes have now been merged to glossary and content strategy
