### ISSUE TITLE
Update TRN validation

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#835]
## Description
This ticket is to update the TRN field validation rules in both the ECT and mentor journeys to copy ECF1 and other DfE services.

## Acceptance criteria

- [x] 1. User can enter any characters into the TRN box. 
- [x] 2. Validation and error messages will be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).
- [x] 3. If  a user enters any characters other than numbers,  (e.g. with slashes or RPs) these will be removed and zero-pad it if necessary.
- [x] 4. If user enters fewer than 7 digits, leading 0s will be added to create a seven digit TRN for the TRS check.
- [x] 5. If user enters more than 7 digits, error message will be shown as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).
- [x] 6. If we find a TRS match and the user can progress through the journey, when we playback the TRN on the <ins>'Check if this is your ECT'</ins> or <ins>'Check mentor details'</ins> page, and everywhere else in the service, we will show the TRN that matches the TRS record, **not** the TRN the user entered (which may have included letters etc)

## Technical notes
This should replicate TRN rules in ECF1.

## Linked tickets
#582

**Comment by claire-hughez** [comment]
We may receive TRNs from users interacting with the UI or from external services. We need to make sure that any TRN values we store are normalised to 7-digits and stored as a "string" value to allow for zero padding where necessary.

This means:

Strip any non-numeric characters (typically if entered by a user)
Remove any white space
Pad with leading zeroes if necessary
We have a [helper class](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/lib/teacher_reference_number.rb) and a [model validator](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/validators/teacher_reference_number_validator.rb) to do this for us in ECFv1 that we could re-use.

**Comment by gracecbrennan** [comment]
Claire to take a look

**Comment by claire-hughez** [comment]
Looks great, thanks Toby.. I can't test AC4 there because we don't have any TRNs that start with a 0. I've just asked James Gunn and Rob for one, and maybe we can add to the review box? (the infinitely expanding review box...)

I think we can move this to done and we can address later though.

**Comment by claire-hughez** [comment]
Data to test:

0105612 13/04/1995
0205845 13/07/1990

I dunno how much often we'll need these. We could add them to the review box. Whatcha think Toby?

**Comment by claire-hughez** [comment]
With that data, I can confirm all AC is met. 

WAHOO
