### ISSUE TITLE
Allow to release with 0 number of terms

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#844]
## User story

**As** 
**I need** 
**So that** 

## Prototype, screenshots & content

Screenshots of relevant screens:

Content should be as per the screenshots above.
URL and validation messages should be as per [this doc](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Beta/Design/Register%20ECTs%20page%20titles%20and%20URLs.xlsx?d=w0c1578ea643147b29357c7f610ee178f&csf=1&web=1&e=U8iIdi).

## Acceptance criteria

- [] 1. XXX

**Comment by gracecbrennan** [comment]
To make a note of this as a rule in service rules. 

Ticket to be closed now.
