### ISSUE TITLE
Prototype school user start page

### ISSUE THREAD

**Issue by Dom-Collins** [DFE-Digital/register-early-career-teachers#85]
We have a draft of what the start pages will look like for both the appropriate body and school users. 

When possible, we would need to test the content with our users to ensure it is effective and fit for purpose. We need to create a prototype of each page to do this.

[Start page content.](https://educationgovuk-my.sharepoint.com/:w:/g/personal/dominic_collins_education_gov_uk/ESsxdLL6wqVFgAbMaEfMIYgBvV05ryFuSCZA5_dqFFpicw?e=kB0toc)

**Comment by gracecbrennan** [comment]
Ticket to be scoped just to schools pages until we've reached a decision on the AB portal work.

**Comment by gracecbrennan** [comment]
Dom is blocked on this one until his access is sorted. Pete has raised a request and can check-in when Dom is back in tomorrow.

**Comment by gracecbrennan** [comment]
Nathan has come back with comments on start-page drafts. Dom is responding to these. 

To catch up with Pete to get code spaces installed.

**Comment by Dom-Collins** [comment]
### Both design options are now prototyped

### Option 1

![Image](https://github.com/user-attachments/assets/c457a8de-fa77-45ce-bda1-a66311388e20)

### Option 2

![Image](https://github.com/user-attachments/assets/78fa5967-5476-4db4-873b-a04f99c75930)

**Comment by claire-hughez** [comment]
Dom to add link

**Comment by Dom-Collins** [comment]
Here is the [PR link](https://github.com/DFE-Digital/ecf2-prototype/pull/1)
