### ISSUE TITLE
Work out how we'll handle CIP and DIY programme types merging into School-led

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#873]
## Why?
From 2025, we'll use school-led and provider-led as programme types. 

We need to work out how to handle historic data however.

## What?
Write up the scoping doc and agree:
https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B7C185FD1-8FF0-4CED-B43D-38B7CD88B1ED%7D&file=ECF%20Programme%20type%20changes.docx&action=default&mobileredirect=true

**Comment by gracecbrennan** [comment]
Claire has made a start and will try to finish

**Comment by claire-hughez** [comment]
Meeting with policy unit: https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B49EC09E3-4886-4216-BB22-3C4924AE0BA8%7D&file=Meeting%20on%20programme%20type%20change%20policy%2022-11-2024.docx&action=default&mobileredirect=true

**Comment by peteryates** [comment]
Remember [there's a discussion on the topic](https://github.com/DFE-Digital/register-early-career-teachers/discussions/214) with some useful stuff in it..

**Comment by gracecbrennan** [comment]
This is very nearly complete and will be ready for review

**Comment by gracecbrennan** [comment]
@JSJohal and @tonyheadford to take a look at this

**Comment by JSJohal** [comment]
Thanks for sharing @claire-hughez. Looks good to me!

**Comment by gracecbrennan** [comment]
Another section needs to be added on induction stuff - these will be a priority ahead of June

**Comment by tonyheadford** [comment]
@claire-hughez I've left a couple of comments/questions but I think it looks fine otherwise 👍

**Comment by gracecbrennan** [comment]
@claire-hughez is going to share this on main channel.
